/-
GENERATED by scripts/gen_lean_cover.py -- DO NOT EDIT BY HAND (tests/test_lean_cover.py regenerates and diffs).
cell: K5_9_5   q=5 n=9 R=5 M=50
source: data/codes/q5_n9_R5_M50.txt
canonical_sha256: 6125e06ca894e33348805fc2682f1e0a833ab44ac05c8174051564ea7bdfb46f
canonical form: sha256 of the sorted codewords joined by LF with trailing LF (data/certificates/K5_9_5.json)
encoding: codeword w_0..w_{n-1}  ->  sum_i w_i * q^i  (little-endian base q), listed in strictly increasing order
-/
namespace CoveringCerts.Data

def K5_9_5 : List Nat := [
  0, 77877, 92504, 96502, 185876, 189879, 279253, 282626,
  372000, 376003, 409463, 429086, 505960, 522463, 599337, 618335,
  633587, 692089, 707336, 726339, 838424, 858047, 872674, 931796,
  949548, 966046, 1042920, 1061923, 1135672, 1155295, 1173730, 1192733,
  1266482, 1286105, 1359859, 1378857, 1455731, 1472234, 1490606, 1549108,
  1602066, 1621694, 1695443, 1714441, 1729693, 1788190, 1803442, 1823065,
  1899944, 1915817
]

end CoveringCerts.Data
