import CoveringLean.K2_Core
import CoveringLean.C1_Data_K5_10_4

/-!
GENERATED by gen.py (frente 1b, 2026-10-02; copy of ~/h/b/gen/gen.py + Final via cert_of_go) -- kernel tier, `decide +kernel` only.
cell: K5_10_4  q=5 n=10 R=4 M=625; data = `CoveringCerts.Data.K5_10_4` (C1_Data_K5_10_4.lean, sha256 in its header).
leaves: all 5^4 prefixes of length 4; each leaf is `go 5 6 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K5_10_4_q1304 : go 5 6 (stepAll 5 4 (stepAll 5 0 (stepAll 5 3 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1310 : go 5 6 (stepAll 5 0 (stepAll 5 1 (stepAll 5 3 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1311 : go 5 6 (stepAll 5 1 (stepAll 5 1 (stepAll 5 3 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1312 : go 5 6 (stepAll 5 2 (stepAll 5 1 (stepAll 5 3 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1313 : go 5 6 (stepAll 5 3 (stepAll 5 1 (stepAll 5 3 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1314 : go 5 6 (stepAll 5 4 (stepAll 5 1 (stepAll 5 3 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1320 : go 5 6 (stepAll 5 0 (stepAll 5 2 (stepAll 5 3 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1321 : go 5 6 (stepAll 5 1 (stepAll 5 2 (stepAll 5 3 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1322 : go 5 6 (stepAll 5 2 (stepAll 5 2 (stepAll 5 3 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1323 : go 5 6 (stepAll 5 3 (stepAll 5 2 (stepAll 5 3 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1324 : go 5 6 (stepAll 5 4 (stepAll 5 2 (stepAll 5 3 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1330 : go 5 6 (stepAll 5 0 (stepAll 5 3 (stepAll 5 3 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1331 : go 5 6 (stepAll 5 1 (stepAll 5 3 (stepAll 5 3 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1332 : go 5 6 (stepAll 5 2 (stepAll 5 3 (stepAll 5 3 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1333 : go 5 6 (stepAll 5 3 (stepAll 5 3 (stepAll 5 3 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1334 : go 5 6 (stepAll 5 4 (stepAll 5 3 (stepAll 5 3 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1340 : go 5 6 (stepAll 5 0 (stepAll 5 4 (stepAll 5 3 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

end CoveringKernel
