import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q0651 : go 7 5 (stepAll 7 1 (stepAll 7 5 (stepAll 7 6 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0652 : go 7 5 (stepAll 7 2 (stepAll 7 5 (stepAll 7 6 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0653 : go 7 5 (stepAll 7 3 (stepAll 7 5 (stepAll 7 6 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0654 : go 7 5 (stepAll 7 4 (stepAll 7 5 (stepAll 7 6 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0655 : go 7 5 (stepAll 7 5 (stepAll 7 5 (stepAll 7 6 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0656 : go 7 5 (stepAll 7 6 (stepAll 7 5 (stepAll 7 6 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0660 : go 7 5 (stepAll 7 0 (stepAll 7 6 (stepAll 7 6 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0661 : go 7 5 (stepAll 7 1 (stepAll 7 6 (stepAll 7 6 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0662 : go 7 5 (stepAll 7 2 (stepAll 7 6 (stepAll 7 6 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0663 : go 7 5 (stepAll 7 3 (stepAll 7 6 (stepAll 7 6 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0664 : go 7 5 (stepAll 7 4 (stepAll 7 6 (stepAll 7 6 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0665 : go 7 5 (stepAll 7 5 (stepAll 7 6 (stepAll 7 6 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0666 : go 7 5 (stepAll 7 6 (stepAll 7 6 (stepAll 7 6 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1000 : go 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 0 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1001 : go 7 5 (stepAll 7 1 (stepAll 7 0 (stepAll 7 0 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1002 : go 7 5 (stepAll 7 2 (stepAll 7 0 (stepAll 7 0 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1003 : go 7 5 (stepAll 7 3 (stepAll 7 0 (stepAll 7 0 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1004 : go 7 5 (stepAll 7 4 (stepAll 7 0 (stepAll 7 0 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1005 : go 7 5 (stepAll 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1006 : go 7 5 (stepAll 7 6 (stepAll 7 0 (stepAll 7 0 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1010 : go 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 0 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1011 : go 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 0 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1012 : go 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 0 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1013 : go 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 0 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1014 : go 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 0 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1015 : go 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 0 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1016 : go 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 0 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
