import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q2304 : go 7 5 (stepAll 7 4 (stepAll 7 0 (stepAll 7 3 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2305 : go 7 5 (stepAll 7 5 (stepAll 7 0 (stepAll 7 3 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2306 : go 7 5 (stepAll 7 6 (stepAll 7 0 (stepAll 7 3 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2310 : go 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 3 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2311 : go 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 3 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2312 : go 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 3 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2313 : go 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 3 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2314 : go 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 3 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2315 : go 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 3 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2316 : go 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 3 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2320 : go 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 3 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2321 : go 7 5 (stepAll 7 1 (stepAll 7 2 (stepAll 7 3 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2322 : go 7 5 (stepAll 7 2 (stepAll 7 2 (stepAll 7 3 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2323 : go 7 5 (stepAll 7 3 (stepAll 7 2 (stepAll 7 3 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2324 : go 7 5 (stepAll 7 4 (stepAll 7 2 (stepAll 7 3 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2325 : go 7 5 (stepAll 7 5 (stepAll 7 2 (stepAll 7 3 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2326 : go 7 5 (stepAll 7 6 (stepAll 7 2 (stepAll 7 3 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2330 : go 7 5 (stepAll 7 0 (stepAll 7 3 (stepAll 7 3 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2331 : go 7 5 (stepAll 7 1 (stepAll 7 3 (stepAll 7 3 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2332 : go 7 5 (stepAll 7 2 (stepAll 7 3 (stepAll 7 3 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2333 : go 7 5 (stepAll 7 3 (stepAll 7 3 (stepAll 7 3 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2334 : go 7 5 (stepAll 7 4 (stepAll 7 3 (stepAll 7 3 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2335 : go 7 5 (stepAll 7 5 (stepAll 7 3 (stepAll 7 3 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2336 : go 7 5 (stepAll 7 6 (stepAll 7 3 (stepAll 7 3 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2340 : go 7 5 (stepAll 7 0 (stepAll 7 4 (stepAll 7 3 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
