import CoveringLean.K2_Core
import CoveringLean.C1_Data_K5_10_4

/-!
GENERATED by gen.py (frente 1b, 2026-10-02; copy of ~/h/b/gen/gen.py + Final via cert_of_go) -- kernel tier, `decide +kernel` only.
cell: K5_10_4  q=5 n=10 R=4 M=625; data = `CoveringCerts.Data.K5_10_4` (C1_Data_K5_10_4.lean, sha256 in its header).
leaves: all 5^4 prefixes of length 4; each leaf is `go 5 6 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K5_10_4_q2412 : go 5 6 (stepAll 5 2 (stepAll 5 1 (stepAll 5 4 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2413 : go 5 6 (stepAll 5 3 (stepAll 5 1 (stepAll 5 4 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2414 : go 5 6 (stepAll 5 4 (stepAll 5 1 (stepAll 5 4 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2420 : go 5 6 (stepAll 5 0 (stepAll 5 2 (stepAll 5 4 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2421 : go 5 6 (stepAll 5 1 (stepAll 5 2 (stepAll 5 4 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2422 : go 5 6 (stepAll 5 2 (stepAll 5 2 (stepAll 5 4 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2423 : go 5 6 (stepAll 5 3 (stepAll 5 2 (stepAll 5 4 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2424 : go 5 6 (stepAll 5 4 (stepAll 5 2 (stepAll 5 4 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2430 : go 5 6 (stepAll 5 0 (stepAll 5 3 (stepAll 5 4 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2431 : go 5 6 (stepAll 5 1 (stepAll 5 3 (stepAll 5 4 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2432 : go 5 6 (stepAll 5 2 (stepAll 5 3 (stepAll 5 4 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2433 : go 5 6 (stepAll 5 3 (stepAll 5 3 (stepAll 5 4 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2434 : go 5 6 (stepAll 5 4 (stepAll 5 3 (stepAll 5 4 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2440 : go 5 6 (stepAll 5 0 (stepAll 5 4 (stepAll 5 4 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2441 : go 5 6 (stepAll 5 1 (stepAll 5 4 (stepAll 5 4 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2442 : go 5 6 (stepAll 5 2 (stepAll 5 4 (stepAll 5 4 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2443 : go 5 6 (stepAll 5 3 (stepAll 5 4 (stepAll 5 4 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

end CoveringKernel
