import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q5041 : go 7 5 (stepAll 7 1 (stepAll 7 4 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5042 : go 7 5 (stepAll 7 2 (stepAll 7 4 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5043 : go 7 5 (stepAll 7 3 (stepAll 7 4 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5044 : go 7 5 (stepAll 7 4 (stepAll 7 4 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5045 : go 7 5 (stepAll 7 5 (stepAll 7 4 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5046 : go 7 5 (stepAll 7 6 (stepAll 7 4 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5050 : go 7 5 (stepAll 7 0 (stepAll 7 5 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5051 : go 7 5 (stepAll 7 1 (stepAll 7 5 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5052 : go 7 5 (stepAll 7 2 (stepAll 7 5 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5053 : go 7 5 (stepAll 7 3 (stepAll 7 5 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5054 : go 7 5 (stepAll 7 4 (stepAll 7 5 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5055 : go 7 5 (stepAll 7 5 (stepAll 7 5 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5056 : go 7 5 (stepAll 7 6 (stepAll 7 5 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5060 : go 7 5 (stepAll 7 0 (stepAll 7 6 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5061 : go 7 5 (stepAll 7 1 (stepAll 7 6 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5062 : go 7 5 (stepAll 7 2 (stepAll 7 6 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5063 : go 7 5 (stepAll 7 3 (stepAll 7 6 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5064 : go 7 5 (stepAll 7 4 (stepAll 7 6 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5065 : go 7 5 (stepAll 7 5 (stepAll 7 6 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5066 : go 7 5 (stepAll 7 6 (stepAll 7 6 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5100 : go 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 1 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5101 : go 7 5 (stepAll 7 1 (stepAll 7 0 (stepAll 7 1 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5102 : go 7 5 (stepAll 7 2 (stepAll 7 0 (stepAll 7 1 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5103 : go 7 5 (stepAll 7 3 (stepAll 7 0 (stepAll 7 1 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5104 : go 7 5 (stepAll 7 4 (stepAll 7 0 (stepAll 7 1 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
