import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q6430 : go 7 5 (stepAll 7 0 (stepAll 7 3 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6431 : go 7 5 (stepAll 7 1 (stepAll 7 3 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6432 : go 7 5 (stepAll 7 2 (stepAll 7 3 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6433 : go 7 5 (stepAll 7 3 (stepAll 7 3 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6434 : go 7 5 (stepAll 7 4 (stepAll 7 3 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6435 : go 7 5 (stepAll 7 5 (stepAll 7 3 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6436 : go 7 5 (stepAll 7 6 (stepAll 7 3 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6440 : go 7 5 (stepAll 7 0 (stepAll 7 4 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6441 : go 7 5 (stepAll 7 1 (stepAll 7 4 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6442 : go 7 5 (stepAll 7 2 (stepAll 7 4 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6443 : go 7 5 (stepAll 7 3 (stepAll 7 4 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6444 : go 7 5 (stepAll 7 4 (stepAll 7 4 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6445 : go 7 5 (stepAll 7 5 (stepAll 7 4 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6446 : go 7 5 (stepAll 7 6 (stepAll 7 4 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6450 : go 7 5 (stepAll 7 0 (stepAll 7 5 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6451 : go 7 5 (stepAll 7 1 (stepAll 7 5 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6452 : go 7 5 (stepAll 7 2 (stepAll 7 5 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6453 : go 7 5 (stepAll 7 3 (stepAll 7 5 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6454 : go 7 5 (stepAll 7 4 (stepAll 7 5 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6455 : go 7 5 (stepAll 7 5 (stepAll 7 5 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6456 : go 7 5 (stepAll 7 6 (stepAll 7 5 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6460 : go 7 5 (stepAll 7 0 (stepAll 7 6 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6461 : go 7 5 (stepAll 7 1 (stepAll 7 6 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6462 : go 7 5 (stepAll 7 2 (stepAll 7 6 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6463 : go 7 5 (stepAll 7 3 (stepAll 7 6 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
