import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q1054 : go 7 5 (stepAll 7 4 (stepAll 7 5 (stepAll 7 0 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1055 : go 7 5 (stepAll 7 5 (stepAll 7 5 (stepAll 7 0 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1056 : go 7 5 (stepAll 7 6 (stepAll 7 5 (stepAll 7 0 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1060 : go 7 5 (stepAll 7 0 (stepAll 7 6 (stepAll 7 0 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1061 : go 7 5 (stepAll 7 1 (stepAll 7 6 (stepAll 7 0 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1062 : go 7 5 (stepAll 7 2 (stepAll 7 6 (stepAll 7 0 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1063 : go 7 5 (stepAll 7 3 (stepAll 7 6 (stepAll 7 0 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1064 : go 7 5 (stepAll 7 4 (stepAll 7 6 (stepAll 7 0 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1065 : go 7 5 (stepAll 7 5 (stepAll 7 6 (stepAll 7 0 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1066 : go 7 5 (stepAll 7 6 (stepAll 7 6 (stepAll 7 0 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1100 : go 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1101 : go 7 5 (stepAll 7 1 (stepAll 7 0 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1102 : go 7 5 (stepAll 7 2 (stepAll 7 0 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1103 : go 7 5 (stepAll 7 3 (stepAll 7 0 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1104 : go 7 5 (stepAll 7 4 (stepAll 7 0 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1105 : go 7 5 (stepAll 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1106 : go 7 5 (stepAll 7 6 (stepAll 7 0 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1110 : go 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1111 : go 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1112 : go 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1113 : go 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1114 : go 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1115 : go 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1116 : go 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1120 : go 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
