import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q3555 : go 7 5 (stepAll 7 5 (stepAll 7 5 (stepAll 7 5 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3556 : go 7 5 (stepAll 7 6 (stepAll 7 5 (stepAll 7 5 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3560 : go 7 5 (stepAll 7 0 (stepAll 7 6 (stepAll 7 5 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3561 : go 7 5 (stepAll 7 1 (stepAll 7 6 (stepAll 7 5 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3562 : go 7 5 (stepAll 7 2 (stepAll 7 6 (stepAll 7 5 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3563 : go 7 5 (stepAll 7 3 (stepAll 7 6 (stepAll 7 5 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3564 : go 7 5 (stepAll 7 4 (stepAll 7 6 (stepAll 7 5 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3565 : go 7 5 (stepAll 7 5 (stepAll 7 6 (stepAll 7 5 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3566 : go 7 5 (stepAll 7 6 (stepAll 7 6 (stepAll 7 5 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3600 : go 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3601 : go 7 5 (stepAll 7 1 (stepAll 7 0 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3602 : go 7 5 (stepAll 7 2 (stepAll 7 0 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3603 : go 7 5 (stepAll 7 3 (stepAll 7 0 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3604 : go 7 5 (stepAll 7 4 (stepAll 7 0 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3605 : go 7 5 (stepAll 7 5 (stepAll 7 0 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3606 : go 7 5 (stepAll 7 6 (stepAll 7 0 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3610 : go 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3611 : go 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3612 : go 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3613 : go 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3614 : go 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3615 : go 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3616 : go 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3620 : go 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3621 : go 7 5 (stepAll 7 1 (stepAll 7 2 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
