import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q6055 : go 7 5 (stepAll 7 5 (stepAll 7 5 (stepAll 7 0 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6056 : go 7 5 (stepAll 7 6 (stepAll 7 5 (stepAll 7 0 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6060 : go 7 5 (stepAll 7 0 (stepAll 7 6 (stepAll 7 0 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6061 : go 7 5 (stepAll 7 1 (stepAll 7 6 (stepAll 7 0 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6062 : go 7 5 (stepAll 7 2 (stepAll 7 6 (stepAll 7 0 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6063 : go 7 5 (stepAll 7 3 (stepAll 7 6 (stepAll 7 0 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6064 : go 7 5 (stepAll 7 4 (stepAll 7 6 (stepAll 7 0 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6065 : go 7 5 (stepAll 7 5 (stepAll 7 6 (stepAll 7 0 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6066 : go 7 5 (stepAll 7 6 (stepAll 7 6 (stepAll 7 0 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6100 : go 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6101 : go 7 5 (stepAll 7 1 (stepAll 7 0 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6102 : go 7 5 (stepAll 7 2 (stepAll 7 0 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6103 : go 7 5 (stepAll 7 3 (stepAll 7 0 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6104 : go 7 5 (stepAll 7 4 (stepAll 7 0 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6105 : go 7 5 (stepAll 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6106 : go 7 5 (stepAll 7 6 (stepAll 7 0 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6110 : go 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6111 : go 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6112 : go 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6113 : go 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6114 : go 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6115 : go 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6116 : go 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6120 : go 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6121 : go 7 5 (stepAll 7 1 (stepAll 7 2 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
