import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_8_3

/-!
GENERATED by gen.py (frente 1a, 2026-10-02) -- kernel tier, `decide +kernel` only.
cell: K7_8_3  q=7 n=8 R=3 M=1893; data = `CoveringCerts.Data.K7_8_3` (C1_Data_K7_8_3.lean, sha256 in its header).
leaves: all 7^3 prefixes of length 3; each leaf is `go 7 5 (stepAll ... (wordItems 3 W)) = true`.
-/

namespace CoveringKernel

theorem K7_8_3_q640 : go 7 5 (stepAll 7 0 (stepAll 7 4 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q641 : go 7 5 (stepAll 7 1 (stepAll 7 4 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q642 : go 7 5 (stepAll 7 2 (stepAll 7 4 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q643 : go 7 5 (stepAll 7 3 (stepAll 7 4 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q644 : go 7 5 (stepAll 7 4 (stepAll 7 4 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q645 : go 7 5 (stepAll 7 5 (stepAll 7 4 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q646 : go 7 5 (stepAll 7 6 (stepAll 7 4 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q650 : go 7 5 (stepAll 7 0 (stepAll 7 5 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q651 : go 7 5 (stepAll 7 1 (stepAll 7 5 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q652 : go 7 5 (stepAll 7 2 (stepAll 7 5 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q653 : go 7 5 (stepAll 7 3 (stepAll 7 5 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q654 : go 7 5 (stepAll 7 4 (stepAll 7 5 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q655 : go 7 5 (stepAll 7 5 (stepAll 7 5 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q656 : go 7 5 (stepAll 7 6 (stepAll 7 5 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

end CoveringKernel
