import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q4063 : go 7 5 (stepAll 7 3 (stepAll 7 6 (stepAll 7 0 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4064 : go 7 5 (stepAll 7 4 (stepAll 7 6 (stepAll 7 0 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4065 : go 7 5 (stepAll 7 5 (stepAll 7 6 (stepAll 7 0 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4066 : go 7 5 (stepAll 7 6 (stepAll 7 6 (stepAll 7 0 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4100 : go 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 1 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4101 : go 7 5 (stepAll 7 1 (stepAll 7 0 (stepAll 7 1 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4102 : go 7 5 (stepAll 7 2 (stepAll 7 0 (stepAll 7 1 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4103 : go 7 5 (stepAll 7 3 (stepAll 7 0 (stepAll 7 1 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4104 : go 7 5 (stepAll 7 4 (stepAll 7 0 (stepAll 7 1 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4105 : go 7 5 (stepAll 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4106 : go 7 5 (stepAll 7 6 (stepAll 7 0 (stepAll 7 1 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4110 : go 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 1 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4111 : go 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 1 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4112 : go 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 1 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4113 : go 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 1 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4114 : go 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 1 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4115 : go 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4116 : go 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 1 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4120 : go 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 1 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4121 : go 7 5 (stepAll 7 1 (stepAll 7 2 (stepAll 7 1 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4122 : go 7 5 (stepAll 7 2 (stepAll 7 2 (stepAll 7 1 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4123 : go 7 5 (stepAll 7 3 (stepAll 7 2 (stepAll 7 1 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4124 : go 7 5 (stepAll 7 4 (stepAll 7 2 (stepAll 7 1 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4125 : go 7 5 (stepAll 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4126 : go 7 5 (stepAll 7 6 (stepAll 7 2 (stepAll 7 1 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
