import CoveringLean.K2_Core
import CoveringLean.C1_CoverCheck
import CoveringLean.K3_K5_9_5_P1
import CoveringLean.K3_K5_9_5_P2

/-!
GENERATED by gen.py (frente 1b, 2026-10-02; copy of ~/h/b/gen/gen.py + Final via cert_of_go) -- kernel tier, `decide +kernel` only.
cell: K5_9_5  q=5 n=9 R=5 M=50; data = `CoveringCerts.Data.K5_9_5` (C1_Data_K5_9_5.lean, sha256 in its header).
leaves: all 5^2 prefixes of length 2; each leaf is `go 5 7 (stepAll ... (wordItems 5 W)) = true`.
-/

namespace CoveringKernel

theorem K5_9_5_q0 : go 5 8 (stepAll 5 0 (wordItems 5 CoveringCerts.Data.K5_9_5)) = true :=
  go_split 5 7 (stepAll 5 0 (wordItems 5 CoveringCerts.Data.K5_9_5)) (by
  intro v hv
  interval_cases v
  · exact K5_9_5_q00
  · exact K5_9_5_q01
  · exact K5_9_5_q02
  · exact K5_9_5_q03
  · exact K5_9_5_q04
  )

theorem K5_9_5_q1 : go 5 8 (stepAll 5 1 (wordItems 5 CoveringCerts.Data.K5_9_5)) = true :=
  go_split 5 7 (stepAll 5 1 (wordItems 5 CoveringCerts.Data.K5_9_5)) (by
  intro v hv
  interval_cases v
  · exact K5_9_5_q10
  · exact K5_9_5_q11
  · exact K5_9_5_q12
  · exact K5_9_5_q13
  · exact K5_9_5_q14
  )

theorem K5_9_5_q2 : go 5 8 (stepAll 5 2 (wordItems 5 CoveringCerts.Data.K5_9_5)) = true :=
  go_split 5 7 (stepAll 5 2 (wordItems 5 CoveringCerts.Data.K5_9_5)) (by
  intro v hv
  interval_cases v
  · exact K5_9_5_q20
  · exact K5_9_5_q21
  · exact K5_9_5_q22
  · exact K5_9_5_q23
  · exact K5_9_5_q24
  )

theorem K5_9_5_q3 : go 5 8 (stepAll 5 3 (wordItems 5 CoveringCerts.Data.K5_9_5)) = true :=
  go_split 5 7 (stepAll 5 3 (wordItems 5 CoveringCerts.Data.K5_9_5)) (by
  intro v hv
  interval_cases v
  · exact K5_9_5_q30
  · exact K5_9_5_q31
  · exact K5_9_5_q32
  · exact K5_9_5_q33
  · exact K5_9_5_q34
  )

theorem K5_9_5_q4 : go 5 8 (stepAll 5 4 (wordItems 5 CoveringCerts.Data.K5_9_5)) = true :=
  go_split 5 7 (stepAll 5 4 (wordItems 5 CoveringCerts.Data.K5_9_5)) (by
  intro v hv
  interval_cases v
  · exact K5_9_5_q40
  · exact K5_9_5_q41
  · exact K5_9_5_q42
  · exact K5_9_5_q43
  · exact K5_9_5_q44
  )

theorem K5_9_5_q : go 5 9 (wordItems 5 CoveringCerts.Data.K5_9_5) = true :=
  go_split 5 8 (wordItems 5 CoveringCerts.Data.K5_9_5) (by
  intro v hv
  interval_cases v
  · exact K5_9_5_q0
  · exact K5_9_5_q1
  · exact K5_9_5_q2
  · exact K5_9_5_q3
  · exact K5_9_5_q4
  )

theorem K5_9_5_le_50_kernel_le :
    ∃ C : Finset (Fin 9 → ZMod 5), C.card ≤ 50 ∧ CoveringA2.Covers 5 C := by
  have h := cover_simple 5 9 5 CoveringCerts.Data.K5_9_5 K5_9_5_q
  have hl : CoveringCerts.Data.K5_9_5.length = 50 := by decide +kernel
  rw [hl] at h
  exact h

end CoveringKernel

#print axioms CoveringKernel.K5_9_5_le_50_kernel_le
