import CoveringLean.K2_Core
import CoveringLean.C1_Data_K5_9_3

/-!
GENERATED by gen.py (frente 1b, 2026-10-02; copy of ~/h/b/gen/gen.py + Final via cert_of_go) -- kernel tier, `decide +kernel` only.
cell: K5_9_3  q=5 n=9 R=3 M=1250; data = `CoveringCerts.Data.K5_9_3` (C1_Data_K5_9_3.lean, sha256 in its header).
leaves: all 5^4 prefixes of length 4; each leaf is `go 5 5 (stepAll ... (wordItems 3 W)) = true`.
-/

namespace CoveringKernel

theorem K5_9_3_q2211 : go 5 5 (stepAll 5 1 (stepAll 5 1 (stepAll 5 2 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2212 : go 5 5 (stepAll 5 2 (stepAll 5 1 (stepAll 5 2 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2213 : go 5 5 (stepAll 5 3 (stepAll 5 1 (stepAll 5 2 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2214 : go 5 5 (stepAll 5 4 (stepAll 5 1 (stepAll 5 2 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2220 : go 5 5 (stepAll 5 0 (stepAll 5 2 (stepAll 5 2 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2221 : go 5 5 (stepAll 5 1 (stepAll 5 2 (stepAll 5 2 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2222 : go 5 5 (stepAll 5 2 (stepAll 5 2 (stepAll 5 2 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2223 : go 5 5 (stepAll 5 3 (stepAll 5 2 (stepAll 5 2 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2224 : go 5 5 (stepAll 5 4 (stepAll 5 2 (stepAll 5 2 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2230 : go 5 5 (stepAll 5 0 (stepAll 5 3 (stepAll 5 2 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2231 : go 5 5 (stepAll 5 1 (stepAll 5 3 (stepAll 5 2 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2232 : go 5 5 (stepAll 5 2 (stepAll 5 3 (stepAll 5 2 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2233 : go 5 5 (stepAll 5 3 (stepAll 5 3 (stepAll 5 2 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2234 : go 5 5 (stepAll 5 4 (stepAll 5 3 (stepAll 5 2 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2240 : go 5 5 (stepAll 5 0 (stepAll 5 4 (stepAll 5 2 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2241 : go 5 5 (stepAll 5 1 (stepAll 5 4 (stepAll 5 2 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2242 : go 5 5 (stepAll 5 2 (stepAll 5 4 (stepAll 5 2 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2243 : go 5 5 (stepAll 5 3 (stepAll 5 4 (stepAll 5 2 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2244 : go 5 5 (stepAll 5 4 (stepAll 5 4 (stepAll 5 2 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2300 : go 5 5 (stepAll 5 0 (stepAll 5 0 (stepAll 5 3 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2301 : go 5 5 (stepAll 5 1 (stepAll 5 0 (stepAll 5 3 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2302 : go 5 5 (stepAll 5 2 (stepAll 5 0 (stepAll 5 3 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2303 : go 5 5 (stepAll 5 3 (stepAll 5 0 (stepAll 5 3 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2304 : go 5 5 (stepAll 5 4 (stepAll 5 0 (stepAll 5 3 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2310 : go 5 5 (stepAll 5 0 (stepAll 5 1 (stepAll 5 3 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2311 : go 5 5 (stepAll 5 1 (stepAll 5 1 (stepAll 5 3 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2312 : go 5 5 (stepAll 5 2 (stepAll 5 1 (stepAll 5 3 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2313 : go 5 5 (stepAll 5 3 (stepAll 5 1 (stepAll 5 3 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2314 : go 5 5 (stepAll 5 4 (stepAll 5 1 (stepAll 5 3 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2320 : go 5 5 (stepAll 5 0 (stepAll 5 2 (stepAll 5 3 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2321 : go 5 5 (stepAll 5 1 (stepAll 5 2 (stepAll 5 3 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2322 : go 5 5 (stepAll 5 2 (stepAll 5 2 (stepAll 5 3 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2323 : go 5 5 (stepAll 5 3 (stepAll 5 2 (stepAll 5 3 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2324 : go 5 5 (stepAll 5 4 (stepAll 5 2 (stepAll 5 3 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2330 : go 5 5 (stepAll 5 0 (stepAll 5 3 (stepAll 5 3 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2331 : go 5 5 (stepAll 5 1 (stepAll 5 3 (stepAll 5 3 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2332 : go 5 5 (stepAll 5 2 (stepAll 5 3 (stepAll 5 3 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2333 : go 5 5 (stepAll 5 3 (stepAll 5 3 (stepAll 5 3 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2334 : go 5 5 (stepAll 5 4 (stepAll 5 3 (stepAll 5 3 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2340 : go 5 5 (stepAll 5 0 (stepAll 5 4 (stepAll 5 3 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2341 : go 5 5 (stepAll 5 1 (stepAll 5 4 (stepAll 5 3 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2342 : go 5 5 (stepAll 5 2 (stepAll 5 4 (stepAll 5 3 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2343 : go 5 5 (stepAll 5 3 (stepAll 5 4 (stepAll 5 3 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2344 : go 5 5 (stepAll 5 4 (stepAll 5 4 (stepAll 5 3 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2400 : go 5 5 (stepAll 5 0 (stepAll 5 0 (stepAll 5 4 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2401 : go 5 5 (stepAll 5 1 (stepAll 5 0 (stepAll 5 4 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2402 : go 5 5 (stepAll 5 2 (stepAll 5 0 (stepAll 5 4 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2403 : go 5 5 (stepAll 5 3 (stepAll 5 0 (stepAll 5 4 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2404 : go 5 5 (stepAll 5 4 (stepAll 5 0 (stepAll 5 4 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2410 : go 5 5 (stepAll 5 0 (stepAll 5 1 (stepAll 5 4 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2411 : go 5 5 (stepAll 5 1 (stepAll 5 1 (stepAll 5 4 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

end CoveringKernel
