import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q2236 : go 7 5 (stepAll 7 6 (stepAll 7 3 (stepAll 7 2 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2240 : go 7 5 (stepAll 7 0 (stepAll 7 4 (stepAll 7 2 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2241 : go 7 5 (stepAll 7 1 (stepAll 7 4 (stepAll 7 2 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2242 : go 7 5 (stepAll 7 2 (stepAll 7 4 (stepAll 7 2 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2243 : go 7 5 (stepAll 7 3 (stepAll 7 4 (stepAll 7 2 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2244 : go 7 5 (stepAll 7 4 (stepAll 7 4 (stepAll 7 2 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2245 : go 7 5 (stepAll 7 5 (stepAll 7 4 (stepAll 7 2 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2246 : go 7 5 (stepAll 7 6 (stepAll 7 4 (stepAll 7 2 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2250 : go 7 5 (stepAll 7 0 (stepAll 7 5 (stepAll 7 2 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2251 : go 7 5 (stepAll 7 1 (stepAll 7 5 (stepAll 7 2 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2252 : go 7 5 (stepAll 7 2 (stepAll 7 5 (stepAll 7 2 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2253 : go 7 5 (stepAll 7 3 (stepAll 7 5 (stepAll 7 2 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2254 : go 7 5 (stepAll 7 4 (stepAll 7 5 (stepAll 7 2 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2255 : go 7 5 (stepAll 7 5 (stepAll 7 5 (stepAll 7 2 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2256 : go 7 5 (stepAll 7 6 (stepAll 7 5 (stepAll 7 2 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2260 : go 7 5 (stepAll 7 0 (stepAll 7 6 (stepAll 7 2 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2261 : go 7 5 (stepAll 7 1 (stepAll 7 6 (stepAll 7 2 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2262 : go 7 5 (stepAll 7 2 (stepAll 7 6 (stepAll 7 2 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2263 : go 7 5 (stepAll 7 3 (stepAll 7 6 (stepAll 7 2 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2264 : go 7 5 (stepAll 7 4 (stepAll 7 6 (stepAll 7 2 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2265 : go 7 5 (stepAll 7 5 (stepAll 7 6 (stepAll 7 2 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2266 : go 7 5 (stepAll 7 6 (stepAll 7 6 (stepAll 7 2 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2300 : go 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 3 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2301 : go 7 5 (stepAll 7 1 (stepAll 7 0 (stepAll 7 3 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2302 : go 7 5 (stepAll 7 2 (stepAll 7 0 (stepAll 7 3 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2303 : go 7 5 (stepAll 7 3 (stepAll 7 0 (stepAll 7 3 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
