import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q4333 : go 7 5 (stepAll 7 3 (stepAll 7 3 (stepAll 7 3 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4334 : go 7 5 (stepAll 7 4 (stepAll 7 3 (stepAll 7 3 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4335 : go 7 5 (stepAll 7 5 (stepAll 7 3 (stepAll 7 3 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4336 : go 7 5 (stepAll 7 6 (stepAll 7 3 (stepAll 7 3 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4340 : go 7 5 (stepAll 7 0 (stepAll 7 4 (stepAll 7 3 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4341 : go 7 5 (stepAll 7 1 (stepAll 7 4 (stepAll 7 3 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4342 : go 7 5 (stepAll 7 2 (stepAll 7 4 (stepAll 7 3 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4343 : go 7 5 (stepAll 7 3 (stepAll 7 4 (stepAll 7 3 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4344 : go 7 5 (stepAll 7 4 (stepAll 7 4 (stepAll 7 3 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4345 : go 7 5 (stepAll 7 5 (stepAll 7 4 (stepAll 7 3 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4346 : go 7 5 (stepAll 7 6 (stepAll 7 4 (stepAll 7 3 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4350 : go 7 5 (stepAll 7 0 (stepAll 7 5 (stepAll 7 3 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4351 : go 7 5 (stepAll 7 1 (stepAll 7 5 (stepAll 7 3 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4352 : go 7 5 (stepAll 7 2 (stepAll 7 5 (stepAll 7 3 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4353 : go 7 5 (stepAll 7 3 (stepAll 7 5 (stepAll 7 3 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4354 : go 7 5 (stepAll 7 4 (stepAll 7 5 (stepAll 7 3 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4355 : go 7 5 (stepAll 7 5 (stepAll 7 5 (stepAll 7 3 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4356 : go 7 5 (stepAll 7 6 (stepAll 7 5 (stepAll 7 3 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4360 : go 7 5 (stepAll 7 0 (stepAll 7 6 (stepAll 7 3 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4361 : go 7 5 (stepAll 7 1 (stepAll 7 6 (stepAll 7 3 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4362 : go 7 5 (stepAll 7 2 (stepAll 7 6 (stepAll 7 3 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4363 : go 7 5 (stepAll 7 3 (stepAll 7 6 (stepAll 7 3 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4364 : go 7 5 (stepAll 7 4 (stepAll 7 6 (stepAll 7 3 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4365 : go 7 5 (stepAll 7 5 (stepAll 7 6 (stepAll 7 3 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4366 : go 7 5 (stepAll 7 6 (stepAll 7 6 (stepAll 7 3 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4400 : go 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 4 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
