import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q0546 : go 7 5 (stepAll 7 6 (stepAll 7 4 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0550 : go 7 5 (stepAll 7 0 (stepAll 7 5 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0551 : go 7 5 (stepAll 7 1 (stepAll 7 5 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0552 : go 7 5 (stepAll 7 2 (stepAll 7 5 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0553 : go 7 5 (stepAll 7 3 (stepAll 7 5 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0554 : go 7 5 (stepAll 7 4 (stepAll 7 5 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0555 : go 7 5 (stepAll 7 5 (stepAll 7 5 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0556 : go 7 5 (stepAll 7 6 (stepAll 7 5 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0560 : go 7 5 (stepAll 7 0 (stepAll 7 6 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0561 : go 7 5 (stepAll 7 1 (stepAll 7 6 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0562 : go 7 5 (stepAll 7 2 (stepAll 7 6 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0563 : go 7 5 (stepAll 7 3 (stepAll 7 6 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0564 : go 7 5 (stepAll 7 4 (stepAll 7 6 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0565 : go 7 5 (stepAll 7 5 (stepAll 7 6 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0566 : go 7 5 (stepAll 7 6 (stepAll 7 6 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0600 : go 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 6 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0601 : go 7 5 (stepAll 7 1 (stepAll 7 0 (stepAll 7 6 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0602 : go 7 5 (stepAll 7 2 (stepAll 7 0 (stepAll 7 6 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0603 : go 7 5 (stepAll 7 3 (stepAll 7 0 (stepAll 7 6 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0604 : go 7 5 (stepAll 7 4 (stepAll 7 0 (stepAll 7 6 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0605 : go 7 5 (stepAll 7 5 (stepAll 7 0 (stepAll 7 6 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0606 : go 7 5 (stepAll 7 6 (stepAll 7 0 (stepAll 7 6 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0610 : go 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 6 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0611 : go 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 6 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0612 : go 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 6 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0613 : go 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 6 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
