import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q2505 : go 7 5 (stepAll 7 5 (stepAll 7 0 (stepAll 7 5 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2506 : go 7 5 (stepAll 7 6 (stepAll 7 0 (stepAll 7 5 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2510 : go 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 5 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2511 : go 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 5 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2512 : go 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 5 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2513 : go 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 5 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2514 : go 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 5 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2515 : go 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 5 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2516 : go 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 5 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2520 : go 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 5 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2521 : go 7 5 (stepAll 7 1 (stepAll 7 2 (stepAll 7 5 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2522 : go 7 5 (stepAll 7 2 (stepAll 7 2 (stepAll 7 5 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2523 : go 7 5 (stepAll 7 3 (stepAll 7 2 (stepAll 7 5 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2524 : go 7 5 (stepAll 7 4 (stepAll 7 2 (stepAll 7 5 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2525 : go 7 5 (stepAll 7 5 (stepAll 7 2 (stepAll 7 5 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2526 : go 7 5 (stepAll 7 6 (stepAll 7 2 (stepAll 7 5 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2530 : go 7 5 (stepAll 7 0 (stepAll 7 3 (stepAll 7 5 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2531 : go 7 5 (stepAll 7 1 (stepAll 7 3 (stepAll 7 5 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2532 : go 7 5 (stepAll 7 2 (stepAll 7 3 (stepAll 7 5 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2533 : go 7 5 (stepAll 7 3 (stepAll 7 3 (stepAll 7 5 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2534 : go 7 5 (stepAll 7 4 (stepAll 7 3 (stepAll 7 5 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2535 : go 7 5 (stepAll 7 5 (stepAll 7 3 (stepAll 7 5 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2536 : go 7 5 (stepAll 7 6 (stepAll 7 3 (stepAll 7 5 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2540 : go 7 5 (stepAll 7 0 (stepAll 7 4 (stepAll 7 5 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2541 : go 7 5 (stepAll 7 1 (stepAll 7 4 (stepAll 7 5 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2542 : go 7 5 (stepAll 7 2 (stepAll 7 4 (stepAll 7 5 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
