import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q5312 : go 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 3 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5313 : go 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 3 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5314 : go 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 3 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5315 : go 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 3 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5316 : go 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 3 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5320 : go 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 3 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5321 : go 7 5 (stepAll 7 1 (stepAll 7 2 (stepAll 7 3 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5322 : go 7 5 (stepAll 7 2 (stepAll 7 2 (stepAll 7 3 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5323 : go 7 5 (stepAll 7 3 (stepAll 7 2 (stepAll 7 3 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5324 : go 7 5 (stepAll 7 4 (stepAll 7 2 (stepAll 7 3 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5325 : go 7 5 (stepAll 7 5 (stepAll 7 2 (stepAll 7 3 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5326 : go 7 5 (stepAll 7 6 (stepAll 7 2 (stepAll 7 3 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5330 : go 7 5 (stepAll 7 0 (stepAll 7 3 (stepAll 7 3 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5331 : go 7 5 (stepAll 7 1 (stepAll 7 3 (stepAll 7 3 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5332 : go 7 5 (stepAll 7 2 (stepAll 7 3 (stepAll 7 3 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5333 : go 7 5 (stepAll 7 3 (stepAll 7 3 (stepAll 7 3 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5334 : go 7 5 (stepAll 7 4 (stepAll 7 3 (stepAll 7 3 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5335 : go 7 5 (stepAll 7 5 (stepAll 7 3 (stepAll 7 3 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5336 : go 7 5 (stepAll 7 6 (stepAll 7 3 (stepAll 7 3 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5340 : go 7 5 (stepAll 7 0 (stepAll 7 4 (stepAll 7 3 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5341 : go 7 5 (stepAll 7 1 (stepAll 7 4 (stepAll 7 3 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5342 : go 7 5 (stepAll 7 2 (stepAll 7 4 (stepAll 7 3 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5343 : go 7 5 (stepAll 7 3 (stepAll 7 4 (stepAll 7 3 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5344 : go 7 5 (stepAll 7 4 (stepAll 7 4 (stepAll 7 3 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5345 : go 7 5 (stepAll 7 5 (stepAll 7 4 (stepAll 7 3 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
