import CoveringLean.K2_Core
import CoveringLean.C1_Data_K5_10_4

/-!
GENERATED by gen.py (frente 1b, 2026-10-02; copy of ~/h/b/gen/gen.py + Final via cert_of_go) -- kernel tier, `decide +kernel` only.
cell: K5_10_4  q=5 n=10 R=4 M=625; data = `CoveringCerts.Data.K5_10_4` (C1_Data_K5_10_4.lean, sha256 in its header).
leaves: all 5^4 prefixes of length 4; each leaf is `go 5 6 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K5_10_4_q3433 : go 5 6 (stepAll 5 3 (stepAll 5 3 (stepAll 5 4 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3434 : go 5 6 (stepAll 5 4 (stepAll 5 3 (stepAll 5 4 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3440 : go 5 6 (stepAll 5 0 (stepAll 5 4 (stepAll 5 4 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3441 : go 5 6 (stepAll 5 1 (stepAll 5 4 (stepAll 5 4 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3442 : go 5 6 (stepAll 5 2 (stepAll 5 4 (stepAll 5 4 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3443 : go 5 6 (stepAll 5 3 (stepAll 5 4 (stepAll 5 4 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3444 : go 5 6 (stepAll 5 4 (stepAll 5 4 (stepAll 5 4 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4000 : go 5 6 (stepAll 5 0 (stepAll 5 0 (stepAll 5 0 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4001 : go 5 6 (stepAll 5 1 (stepAll 5 0 (stepAll 5 0 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4002 : go 5 6 (stepAll 5 2 (stepAll 5 0 (stepAll 5 0 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4003 : go 5 6 (stepAll 5 3 (stepAll 5 0 (stepAll 5 0 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4004 : go 5 6 (stepAll 5 4 (stepAll 5 0 (stepAll 5 0 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4010 : go 5 6 (stepAll 5 0 (stepAll 5 1 (stepAll 5 0 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4011 : go 5 6 (stepAll 5 1 (stepAll 5 1 (stepAll 5 0 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4012 : go 5 6 (stepAll 5 2 (stepAll 5 1 (stepAll 5 0 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4013 : go 5 6 (stepAll 5 3 (stepAll 5 1 (stepAll 5 0 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4014 : go 5 6 (stepAll 5 4 (stepAll 5 1 (stepAll 5 0 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

end CoveringKernel
