import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q6362 : go 7 5 (stepAll 7 2 (stepAll 7 6 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6363 : go 7 5 (stepAll 7 3 (stepAll 7 6 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6364 : go 7 5 (stepAll 7 4 (stepAll 7 6 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6365 : go 7 5 (stepAll 7 5 (stepAll 7 6 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6366 : go 7 5 (stepAll 7 6 (stepAll 7 6 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6400 : go 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6401 : go 7 5 (stepAll 7 1 (stepAll 7 0 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6402 : go 7 5 (stepAll 7 2 (stepAll 7 0 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6403 : go 7 5 (stepAll 7 3 (stepAll 7 0 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6404 : go 7 5 (stepAll 7 4 (stepAll 7 0 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6405 : go 7 5 (stepAll 7 5 (stepAll 7 0 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6406 : go 7 5 (stepAll 7 6 (stepAll 7 0 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6410 : go 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6411 : go 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6412 : go 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6413 : go 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6414 : go 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6415 : go 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6416 : go 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6420 : go 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6421 : go 7 5 (stepAll 7 1 (stepAll 7 2 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6422 : go 7 5 (stepAll 7 2 (stepAll 7 2 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6423 : go 7 5 (stepAll 7 3 (stepAll 7 2 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6424 : go 7 5 (stepAll 7 4 (stepAll 7 2 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6425 : go 7 5 (stepAll 7 5 (stepAll 7 2 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6426 : go 7 5 (stepAll 7 6 (stepAll 7 2 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
