import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_8_3

/-!
GENERATED by gen.py (frente 1a, 2026-10-02) -- kernel tier, `decide +kernel` only.
cell: K7_8_3  q=7 n=8 R=3 M=1893; data = `CoveringCerts.Data.K7_8_3` (C1_Data_K7_8_3.lean, sha256 in its header).
leaves: all 7^3 prefixes of length 3; each leaf is `go 7 5 (stepAll ... (wordItems 3 W)) = true`.
-/

namespace CoveringKernel

theorem K7_8_3_q000 : go 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q001 : go 7 5 (stepAll 7 1 (stepAll 7 0 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q002 : go 7 5 (stepAll 7 2 (stepAll 7 0 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q003 : go 7 5 (stepAll 7 3 (stepAll 7 0 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q004 : go 7 5 (stepAll 7 4 (stepAll 7 0 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q005 : go 7 5 (stepAll 7 5 (stepAll 7 0 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q006 : go 7 5 (stepAll 7 6 (stepAll 7 0 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q010 : go 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q011 : go 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q012 : go 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q013 : go 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q014 : go 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q015 : go 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q016 : go 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

end CoveringKernel
