import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_8_3

/-!
GENERATED by gen.py (frente 1a, 2026-10-02) -- kernel tier, `decide +kernel` only.
cell: K7_8_3  q=7 n=8 R=3 M=1893; data = `CoveringCerts.Data.K7_8_3` (C1_Data_K7_8_3.lean, sha256 in its header).
leaves: all 7^3 prefixes of length 3; each leaf is `go 7 5 (stepAll ... (wordItems 3 W)) = true`.
-/

namespace CoveringKernel

theorem K7_8_3_q020 : go 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q021 : go 7 5 (stepAll 7 1 (stepAll 7 2 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q022 : go 7 5 (stepAll 7 2 (stepAll 7 2 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q023 : go 7 5 (stepAll 7 3 (stepAll 7 2 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q024 : go 7 5 (stepAll 7 4 (stepAll 7 2 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q025 : go 7 5 (stepAll 7 5 (stepAll 7 2 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q026 : go 7 5 (stepAll 7 6 (stepAll 7 2 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q030 : go 7 5 (stepAll 7 0 (stepAll 7 3 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q031 : go 7 5 (stepAll 7 1 (stepAll 7 3 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q032 : go 7 5 (stepAll 7 2 (stepAll 7 3 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q033 : go 7 5 (stepAll 7 3 (stepAll 7 3 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q034 : go 7 5 (stepAll 7 4 (stepAll 7 3 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q035 : go 7 5 (stepAll 7 5 (stepAll 7 3 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q036 : go 7 5 (stepAll 7 6 (stepAll 7 3 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

end CoveringKernel
