import CoveringLean.K2_Core
import CoveringLean.C1_Data_K4_10_4

/-!
GENERATED by gen.py (frente 1b, 2026-10-02; copy of ~/h/b/gen/gen.py + Final via cert_of_go) -- kernel tier, `decide +kernel` only.
cell: K4_10_4  q=4 n=10 R=4 M=192; data = `CoveringCerts.Data.K4_10_4` (C1_Data_K4_10_4.lean, sha256 in its header).
leaves: all 4^3 prefixes of length 3; each leaf is `go 4 7 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K4_10_4_q333 : go 4 7 (stepAll 4 3 (stepAll 4 3 (stepAll 4 3 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

end CoveringKernel
