import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q1223 : go 7 5 (stepAll 7 3 (stepAll 7 2 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1224 : go 7 5 (stepAll 7 4 (stepAll 7 2 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1225 : go 7 5 (stepAll 7 5 (stepAll 7 2 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1226 : go 7 5 (stepAll 7 6 (stepAll 7 2 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1230 : go 7 5 (stepAll 7 0 (stepAll 7 3 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1231 : go 7 5 (stepAll 7 1 (stepAll 7 3 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1232 : go 7 5 (stepAll 7 2 (stepAll 7 3 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1233 : go 7 5 (stepAll 7 3 (stepAll 7 3 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1234 : go 7 5 (stepAll 7 4 (stepAll 7 3 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1235 : go 7 5 (stepAll 7 5 (stepAll 7 3 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1236 : go 7 5 (stepAll 7 6 (stepAll 7 3 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1240 : go 7 5 (stepAll 7 0 (stepAll 7 4 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1241 : go 7 5 (stepAll 7 1 (stepAll 7 4 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1242 : go 7 5 (stepAll 7 2 (stepAll 7 4 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1243 : go 7 5 (stepAll 7 3 (stepAll 7 4 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1244 : go 7 5 (stepAll 7 4 (stepAll 7 4 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1245 : go 7 5 (stepAll 7 5 (stepAll 7 4 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1246 : go 7 5 (stepAll 7 6 (stepAll 7 4 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1250 : go 7 5 (stepAll 7 0 (stepAll 7 5 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1251 : go 7 5 (stepAll 7 1 (stepAll 7 5 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1252 : go 7 5 (stepAll 7 2 (stepAll 7 5 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1253 : go 7 5 (stepAll 7 3 (stepAll 7 5 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1254 : go 7 5 (stepAll 7 4 (stepAll 7 5 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1255 : go 7 5 (stepAll 7 5 (stepAll 7 5 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
