import CoveringLean.K2_Core
import CoveringLean.C1_Data_K5_10_4

/-!
GENERATED by gen.py (frente 1b, 2026-10-02; copy of ~/h/b/gen/gen.py + Final via cert_of_go) -- kernel tier, `decide +kernel` only.
cell: K5_10_4  q=5 n=10 R=4 M=625; data = `CoveringCerts.Data.K5_10_4` (C1_Data_K5_10_4.lean, sha256 in its header).
leaves: all 5^4 prefixes of length 4; each leaf is `go 5 6 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K5_10_4_q2444 : go 5 6 (stepAll 5 4 (stepAll 5 4 (stepAll 5 4 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3000 : go 5 6 (stepAll 5 0 (stepAll 5 0 (stepAll 5 0 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3001 : go 5 6 (stepAll 5 1 (stepAll 5 0 (stepAll 5 0 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3002 : go 5 6 (stepAll 5 2 (stepAll 5 0 (stepAll 5 0 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3003 : go 5 6 (stepAll 5 3 (stepAll 5 0 (stepAll 5 0 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3004 : go 5 6 (stepAll 5 4 (stepAll 5 0 (stepAll 5 0 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3010 : go 5 6 (stepAll 5 0 (stepAll 5 1 (stepAll 5 0 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3011 : go 5 6 (stepAll 5 1 (stepAll 5 1 (stepAll 5 0 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3012 : go 5 6 (stepAll 5 2 (stepAll 5 1 (stepAll 5 0 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3013 : go 5 6 (stepAll 5 3 (stepAll 5 1 (stepAll 5 0 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3014 : go 5 6 (stepAll 5 4 (stepAll 5 1 (stepAll 5 0 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3020 : go 5 6 (stepAll 5 0 (stepAll 5 2 (stepAll 5 0 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3021 : go 5 6 (stepAll 5 1 (stepAll 5 2 (stepAll 5 0 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3022 : go 5 6 (stepAll 5 2 (stepAll 5 2 (stepAll 5 0 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3023 : go 5 6 (stepAll 5 3 (stepAll 5 2 (stepAll 5 0 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3024 : go 5 6 (stepAll 5 4 (stepAll 5 2 (stepAll 5 0 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3030 : go 5 6 (stepAll 5 0 (stepAll 5 3 (stepAll 5 0 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

end CoveringKernel
