import CoveringLean.K2_Core
import CoveringLean.C1_Data_K5_10_4

/-!
GENERATED by gen.py (frente 1b, 2026-10-02; copy of ~/h/b/gen/gen.py + Final via cert_of_go) -- kernel tier, `decide +kernel` only.
cell: K5_10_4  q=5 n=10 R=4 M=625; data = `CoveringCerts.Data.K5_10_4` (C1_Data_K5_10_4.lean, sha256 in its header).
leaves: all 5^4 prefixes of length 4; each leaf is `go 5 6 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K5_10_4_q4134 : go 5 6 (stepAll 5 4 (stepAll 5 3 (stepAll 5 1 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4140 : go 5 6 (stepAll 5 0 (stepAll 5 4 (stepAll 5 1 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4141 : go 5 6 (stepAll 5 1 (stepAll 5 4 (stepAll 5 1 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4142 : go 5 6 (stepAll 5 2 (stepAll 5 4 (stepAll 5 1 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4143 : go 5 6 (stepAll 5 3 (stepAll 5 4 (stepAll 5 1 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4144 : go 5 6 (stepAll 5 4 (stepAll 5 4 (stepAll 5 1 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4200 : go 5 6 (stepAll 5 0 (stepAll 5 0 (stepAll 5 2 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4201 : go 5 6 (stepAll 5 1 (stepAll 5 0 (stepAll 5 2 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4202 : go 5 6 (stepAll 5 2 (stepAll 5 0 (stepAll 5 2 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4203 : go 5 6 (stepAll 5 3 (stepAll 5 0 (stepAll 5 2 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4204 : go 5 6 (stepAll 5 4 (stepAll 5 0 (stepAll 5 2 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4210 : go 5 6 (stepAll 5 0 (stepAll 5 1 (stepAll 5 2 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4211 : go 5 6 (stepAll 5 1 (stepAll 5 1 (stepAll 5 2 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4212 : go 5 6 (stepAll 5 2 (stepAll 5 1 (stepAll 5 2 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4213 : go 5 6 (stepAll 5 3 (stepAll 5 1 (stepAll 5 2 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4214 : go 5 6 (stepAll 5 4 (stepAll 5 1 (stepAll 5 2 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4220 : go 5 6 (stepAll 5 0 (stepAll 5 2 (stepAll 5 2 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

end CoveringKernel
