import CoveringLean.K2_Core
import CoveringLean.C1_Data_K5_9_3

/-!
GENERATED by gen.py (frente 1b, 2026-10-02; copy of ~/h/b/gen/gen.py + Final via cert_of_go) -- kernel tier, `decide +kernel` only.
cell: K5_9_3  q=5 n=9 R=3 M=1250; data = `CoveringCerts.Data.K5_9_3` (C1_Data_K5_9_3.lean, sha256 in its header).
leaves: all 5^4 prefixes of length 4; each leaf is `go 5 5 (stepAll ... (wordItems 3 W)) = true`.
-/

namespace CoveringKernel

theorem K5_9_3_q0000 : go 5 5 (stepAll 5 0 (stepAll 5 0 (stepAll 5 0 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0001 : go 5 5 (stepAll 5 1 (stepAll 5 0 (stepAll 5 0 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0002 : go 5 5 (stepAll 5 2 (stepAll 5 0 (stepAll 5 0 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0003 : go 5 5 (stepAll 5 3 (stepAll 5 0 (stepAll 5 0 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0004 : go 5 5 (stepAll 5 4 (stepAll 5 0 (stepAll 5 0 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0010 : go 5 5 (stepAll 5 0 (stepAll 5 1 (stepAll 5 0 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0011 : go 5 5 (stepAll 5 1 (stepAll 5 1 (stepAll 5 0 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0012 : go 5 5 (stepAll 5 2 (stepAll 5 1 (stepAll 5 0 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0013 : go 5 5 (stepAll 5 3 (stepAll 5 1 (stepAll 5 0 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0014 : go 5 5 (stepAll 5 4 (stepAll 5 1 (stepAll 5 0 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0020 : go 5 5 (stepAll 5 0 (stepAll 5 2 (stepAll 5 0 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0021 : go 5 5 (stepAll 5 1 (stepAll 5 2 (stepAll 5 0 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0022 : go 5 5 (stepAll 5 2 (stepAll 5 2 (stepAll 5 0 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0023 : go 5 5 (stepAll 5 3 (stepAll 5 2 (stepAll 5 0 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0024 : go 5 5 (stepAll 5 4 (stepAll 5 2 (stepAll 5 0 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0030 : go 5 5 (stepAll 5 0 (stepAll 5 3 (stepAll 5 0 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0031 : go 5 5 (stepAll 5 1 (stepAll 5 3 (stepAll 5 0 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0032 : go 5 5 (stepAll 5 2 (stepAll 5 3 (stepAll 5 0 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0033 : go 5 5 (stepAll 5 3 (stepAll 5 3 (stepAll 5 0 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0034 : go 5 5 (stepAll 5 4 (stepAll 5 3 (stepAll 5 0 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0040 : go 5 5 (stepAll 5 0 (stepAll 5 4 (stepAll 5 0 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0041 : go 5 5 (stepAll 5 1 (stepAll 5 4 (stepAll 5 0 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0042 : go 5 5 (stepAll 5 2 (stepAll 5 4 (stepAll 5 0 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0043 : go 5 5 (stepAll 5 3 (stepAll 5 4 (stepAll 5 0 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0044 : go 5 5 (stepAll 5 4 (stepAll 5 4 (stepAll 5 0 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0100 : go 5 5 (stepAll 5 0 (stepAll 5 0 (stepAll 5 1 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0101 : go 5 5 (stepAll 5 1 (stepAll 5 0 (stepAll 5 1 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0102 : go 5 5 (stepAll 5 2 (stepAll 5 0 (stepAll 5 1 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0103 : go 5 5 (stepAll 5 3 (stepAll 5 0 (stepAll 5 1 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0104 : go 5 5 (stepAll 5 4 (stepAll 5 0 (stepAll 5 1 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0110 : go 5 5 (stepAll 5 0 (stepAll 5 1 (stepAll 5 1 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0111 : go 5 5 (stepAll 5 1 (stepAll 5 1 (stepAll 5 1 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0112 : go 5 5 (stepAll 5 2 (stepAll 5 1 (stepAll 5 1 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0113 : go 5 5 (stepAll 5 3 (stepAll 5 1 (stepAll 5 1 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0114 : go 5 5 (stepAll 5 4 (stepAll 5 1 (stepAll 5 1 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0120 : go 5 5 (stepAll 5 0 (stepAll 5 2 (stepAll 5 1 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0121 : go 5 5 (stepAll 5 1 (stepAll 5 2 (stepAll 5 1 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0122 : go 5 5 (stepAll 5 2 (stepAll 5 2 (stepAll 5 1 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0123 : go 5 5 (stepAll 5 3 (stepAll 5 2 (stepAll 5 1 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0124 : go 5 5 (stepAll 5 4 (stepAll 5 2 (stepAll 5 1 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0130 : go 5 5 (stepAll 5 0 (stepAll 5 3 (stepAll 5 1 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0131 : go 5 5 (stepAll 5 1 (stepAll 5 3 (stepAll 5 1 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0132 : go 5 5 (stepAll 5 2 (stepAll 5 3 (stepAll 5 1 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0133 : go 5 5 (stepAll 5 3 (stepAll 5 3 (stepAll 5 1 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0134 : go 5 5 (stepAll 5 4 (stepAll 5 3 (stepAll 5 1 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0140 : go 5 5 (stepAll 5 0 (stepAll 5 4 (stepAll 5 1 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0141 : go 5 5 (stepAll 5 1 (stepAll 5 4 (stepAll 5 1 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0142 : go 5 5 (stepAll 5 2 (stepAll 5 4 (stepAll 5 1 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0143 : go 5 5 (stepAll 5 3 (stepAll 5 4 (stepAll 5 1 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0144 : go 5 5 (stepAll 5 4 (stepAll 5 4 (stepAll 5 1 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q0200 : go 5 5 (stepAll 5 0 (stepAll 5 0 (stepAll 5 2 (stepAll 5 0 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

end CoveringKernel
