import CoveringLean.K2_Core
import CoveringLean.C1_Data_K4_10_4

/-!
GENERATED by gen.py (frente 1b, 2026-10-02; copy of ~/h/b/gen/gen.py + Final via cert_of_go) -- kernel tier, `decide +kernel` only.
cell: K4_10_4  q=4 n=10 R=4 M=192; data = `CoveringCerts.Data.K4_10_4` (C1_Data_K4_10_4.lean, sha256 in its header).
leaves: all 4^3 prefixes of length 3; each leaf is `go 4 7 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K4_10_4_q222 : go 4 7 (stepAll 4 2 (stepAll 4 2 (stepAll 4 2 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q223 : go 4 7 (stepAll 4 3 (stepAll 4 2 (stepAll 4 2 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q230 : go 4 7 (stepAll 4 0 (stepAll 4 3 (stepAll 4 2 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q231 : go 4 7 (stepAll 4 1 (stepAll 4 3 (stepAll 4 2 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q232 : go 4 7 (stepAll 4 2 (stepAll 4 3 (stepAll 4 2 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q233 : go 4 7 (stepAll 4 3 (stepAll 4 3 (stepAll 4 2 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q300 : go 4 7 (stepAll 4 0 (stepAll 4 0 (stepAll 4 3 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q301 : go 4 7 (stepAll 4 1 (stepAll 4 0 (stepAll 4 3 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q302 : go 4 7 (stepAll 4 2 (stepAll 4 0 (stepAll 4 3 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q303 : go 4 7 (stepAll 4 3 (stepAll 4 0 (stepAll 4 3 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q310 : go 4 7 (stepAll 4 0 (stepAll 4 1 (stepAll 4 3 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q311 : go 4 7 (stepAll 4 1 (stepAll 4 1 (stepAll 4 3 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q312 : go 4 7 (stepAll 4 2 (stepAll 4 1 (stepAll 4 3 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q313 : go 4 7 (stepAll 4 3 (stepAll 4 1 (stepAll 4 3 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q320 : go 4 7 (stepAll 4 0 (stepAll 4 2 (stepAll 4 3 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q321 : go 4 7 (stepAll 4 1 (stepAll 4 2 (stepAll 4 3 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q322 : go 4 7 (stepAll 4 2 (stepAll 4 2 (stepAll 4 3 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q323 : go 4 7 (stepAll 4 3 (stepAll 4 2 (stepAll 4 3 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q330 : go 4 7 (stepAll 4 0 (stepAll 4 3 (stepAll 4 3 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q331 : go 4 7 (stepAll 4 1 (stepAll 4 3 (stepAll 4 3 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q332 : go 4 7 (stepAll 4 2 (stepAll 4 3 (stepAll 4 3 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

end CoveringKernel
