import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_8_3

/-!
GENERATED by gen.py (frente 1a, 2026-10-02) -- kernel tier, `decide +kernel` only.
cell: K7_8_3  q=7 n=8 R=3 M=1893; data = `CoveringCerts.Data.K7_8_3` (C1_Data_K7_8_3.lean, sha256 in its header).
leaves: all 7^3 prefixes of length 3; each leaf is `go 7 5 (stepAll ... (wordItems 3 W)) = true`.
-/

namespace CoveringKernel

theorem K7_8_3_q110 : go 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q111 : go 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q112 : go 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q113 : go 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q114 : go 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q115 : go 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q116 : go 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q120 : go 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q121 : go 7 5 (stepAll 7 1 (stepAll 7 2 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q122 : go 7 5 (stepAll 7 2 (stepAll 7 2 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q123 : go 7 5 (stepAll 7 3 (stepAll 7 2 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q124 : go 7 5 (stepAll 7 4 (stepAll 7 2 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q125 : go 7 5 (stepAll 7 5 (stepAll 7 2 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q126 : go 7 5 (stepAll 7 6 (stepAll 7 2 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

end CoveringKernel
