import CoveringLean.K2_Core
import CoveringLean.C1_Data_K5_9_3

/-!
GENERATED by gen.py (frente 1b, 2026-10-02; copy of ~/h/b/gen/gen.py + Final via cert_of_go) -- kernel tier, `decide +kernel` only.
cell: K5_9_3  q=5 n=9 R=3 M=1250; data = `CoveringCerts.Data.K5_9_3` (C1_Data_K5_9_3.lean, sha256 in its header).
leaves: all 5^4 prefixes of length 4; each leaf is `go 5 5 (stepAll ... (wordItems 3 W)) = true`.
-/

namespace CoveringKernel

theorem K5_9_3_q1304 : go 5 5 (stepAll 5 4 (stepAll 5 0 (stepAll 5 3 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1310 : go 5 5 (stepAll 5 0 (stepAll 5 1 (stepAll 5 3 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1311 : go 5 5 (stepAll 5 1 (stepAll 5 1 (stepAll 5 3 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1312 : go 5 5 (stepAll 5 2 (stepAll 5 1 (stepAll 5 3 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1313 : go 5 5 (stepAll 5 3 (stepAll 5 1 (stepAll 5 3 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1314 : go 5 5 (stepAll 5 4 (stepAll 5 1 (stepAll 5 3 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1320 : go 5 5 (stepAll 5 0 (stepAll 5 2 (stepAll 5 3 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1321 : go 5 5 (stepAll 5 1 (stepAll 5 2 (stepAll 5 3 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1322 : go 5 5 (stepAll 5 2 (stepAll 5 2 (stepAll 5 3 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1323 : go 5 5 (stepAll 5 3 (stepAll 5 2 (stepAll 5 3 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1324 : go 5 5 (stepAll 5 4 (stepAll 5 2 (stepAll 5 3 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1330 : go 5 5 (stepAll 5 0 (stepAll 5 3 (stepAll 5 3 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1331 : go 5 5 (stepAll 5 1 (stepAll 5 3 (stepAll 5 3 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1332 : go 5 5 (stepAll 5 2 (stepAll 5 3 (stepAll 5 3 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1333 : go 5 5 (stepAll 5 3 (stepAll 5 3 (stepAll 5 3 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1334 : go 5 5 (stepAll 5 4 (stepAll 5 3 (stepAll 5 3 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1340 : go 5 5 (stepAll 5 0 (stepAll 5 4 (stepAll 5 3 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1341 : go 5 5 (stepAll 5 1 (stepAll 5 4 (stepAll 5 3 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1342 : go 5 5 (stepAll 5 2 (stepAll 5 4 (stepAll 5 3 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1343 : go 5 5 (stepAll 5 3 (stepAll 5 4 (stepAll 5 3 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1344 : go 5 5 (stepAll 5 4 (stepAll 5 4 (stepAll 5 3 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1400 : go 5 5 (stepAll 5 0 (stepAll 5 0 (stepAll 5 4 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1401 : go 5 5 (stepAll 5 1 (stepAll 5 0 (stepAll 5 4 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1402 : go 5 5 (stepAll 5 2 (stepAll 5 0 (stepAll 5 4 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1403 : go 5 5 (stepAll 5 3 (stepAll 5 0 (stepAll 5 4 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1404 : go 5 5 (stepAll 5 4 (stepAll 5 0 (stepAll 5 4 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1410 : go 5 5 (stepAll 5 0 (stepAll 5 1 (stepAll 5 4 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1411 : go 5 5 (stepAll 5 1 (stepAll 5 1 (stepAll 5 4 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1412 : go 5 5 (stepAll 5 2 (stepAll 5 1 (stepAll 5 4 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1413 : go 5 5 (stepAll 5 3 (stepAll 5 1 (stepAll 5 4 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1414 : go 5 5 (stepAll 5 4 (stepAll 5 1 (stepAll 5 4 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1420 : go 5 5 (stepAll 5 0 (stepAll 5 2 (stepAll 5 4 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1421 : go 5 5 (stepAll 5 1 (stepAll 5 2 (stepAll 5 4 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1422 : go 5 5 (stepAll 5 2 (stepAll 5 2 (stepAll 5 4 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1423 : go 5 5 (stepAll 5 3 (stepAll 5 2 (stepAll 5 4 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1424 : go 5 5 (stepAll 5 4 (stepAll 5 2 (stepAll 5 4 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1430 : go 5 5 (stepAll 5 0 (stepAll 5 3 (stepAll 5 4 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1431 : go 5 5 (stepAll 5 1 (stepAll 5 3 (stepAll 5 4 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1432 : go 5 5 (stepAll 5 2 (stepAll 5 3 (stepAll 5 4 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1433 : go 5 5 (stepAll 5 3 (stepAll 5 3 (stepAll 5 4 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1434 : go 5 5 (stepAll 5 4 (stepAll 5 3 (stepAll 5 4 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1440 : go 5 5 (stepAll 5 0 (stepAll 5 4 (stepAll 5 4 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1441 : go 5 5 (stepAll 5 1 (stepAll 5 4 (stepAll 5 4 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1442 : go 5 5 (stepAll 5 2 (stepAll 5 4 (stepAll 5 4 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1443 : go 5 5 (stepAll 5 3 (stepAll 5 4 (stepAll 5 4 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q1444 : go 5 5 (stepAll 5 4 (stepAll 5 4 (stepAll 5 4 (stepAll 5 1 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2000 : go 5 5 (stepAll 5 0 (stepAll 5 0 (stepAll 5 0 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2001 : go 5 5 (stepAll 5 1 (stepAll 5 0 (stepAll 5 0 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2002 : go 5 5 (stepAll 5 2 (stepAll 5 0 (stepAll 5 0 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2003 : go 5 5 (stepAll 5 3 (stepAll 5 0 (stepAll 5 0 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2004 : go 5 5 (stepAll 5 4 (stepAll 5 0 (stepAll 5 0 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

end CoveringKernel
