import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q4401 : go 7 5 (stepAll 7 1 (stepAll 7 0 (stepAll 7 4 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4402 : go 7 5 (stepAll 7 2 (stepAll 7 0 (stepAll 7 4 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4403 : go 7 5 (stepAll 7 3 (stepAll 7 0 (stepAll 7 4 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4404 : go 7 5 (stepAll 7 4 (stepAll 7 0 (stepAll 7 4 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4405 : go 7 5 (stepAll 7 5 (stepAll 7 0 (stepAll 7 4 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4406 : go 7 5 (stepAll 7 6 (stepAll 7 0 (stepAll 7 4 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4410 : go 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 4 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4411 : go 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 4 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4412 : go 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 4 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4413 : go 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 4 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4414 : go 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 4 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4415 : go 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 4 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4416 : go 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 4 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4420 : go 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 4 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4421 : go 7 5 (stepAll 7 1 (stepAll 7 2 (stepAll 7 4 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4422 : go 7 5 (stepAll 7 2 (stepAll 7 2 (stepAll 7 4 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4423 : go 7 5 (stepAll 7 3 (stepAll 7 2 (stepAll 7 4 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4424 : go 7 5 (stepAll 7 4 (stepAll 7 2 (stepAll 7 4 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4425 : go 7 5 (stepAll 7 5 (stepAll 7 2 (stepAll 7 4 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4426 : go 7 5 (stepAll 7 6 (stepAll 7 2 (stepAll 7 4 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4430 : go 7 5 (stepAll 7 0 (stepAll 7 3 (stepAll 7 4 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4431 : go 7 5 (stepAll 7 1 (stepAll 7 3 (stepAll 7 4 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4432 : go 7 5 (stepAll 7 2 (stepAll 7 3 (stepAll 7 4 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4433 : go 7 5 (stepAll 7 3 (stepAll 7 3 (stepAll 7 4 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4434 : go 7 5 (stepAll 7 4 (stepAll 7 3 (stepAll 7 4 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
