import CoveringLean.K2_Core
import CoveringLean.C1_Data_K5_9_5

/-!
GENERATED by gen.py (frente 1b, 2026-10-02; copy of ~/h/b/gen/gen.py + Final via cert_of_go) -- kernel tier, `decide +kernel` only.
cell: K5_9_5  q=5 n=9 R=5 M=50; data = `CoveringCerts.Data.K5_9_5` (C1_Data_K5_9_5.lean, sha256 in its header).
leaves: all 5^2 prefixes of length 2; each leaf is `go 5 7 (stepAll ... (wordItems 5 W)) = true`.
-/

namespace CoveringKernel

theorem K5_9_5_q00 : go 5 7 (stepAll 5 0 (stepAll 5 0 (wordItems 5 CoveringCerts.Data.K5_9_5))) = true := by decide +kernel

theorem K5_9_5_q01 : go 5 7 (stepAll 5 1 (stepAll 5 0 (wordItems 5 CoveringCerts.Data.K5_9_5))) = true := by decide +kernel

theorem K5_9_5_q02 : go 5 7 (stepAll 5 2 (stepAll 5 0 (wordItems 5 CoveringCerts.Data.K5_9_5))) = true := by decide +kernel

theorem K5_9_5_q03 : go 5 7 (stepAll 5 3 (stepAll 5 0 (wordItems 5 CoveringCerts.Data.K5_9_5))) = true := by decide +kernel

theorem K5_9_5_q04 : go 5 7 (stepAll 5 4 (stepAll 5 0 (wordItems 5 CoveringCerts.Data.K5_9_5))) = true := by decide +kernel

theorem K5_9_5_q10 : go 5 7 (stepAll 5 0 (stepAll 5 1 (wordItems 5 CoveringCerts.Data.K5_9_5))) = true := by decide +kernel

theorem K5_9_5_q11 : go 5 7 (stepAll 5 1 (stepAll 5 1 (wordItems 5 CoveringCerts.Data.K5_9_5))) = true := by decide +kernel

theorem K5_9_5_q12 : go 5 7 (stepAll 5 2 (stepAll 5 1 (wordItems 5 CoveringCerts.Data.K5_9_5))) = true := by decide +kernel

theorem K5_9_5_q13 : go 5 7 (stepAll 5 3 (stepAll 5 1 (wordItems 5 CoveringCerts.Data.K5_9_5))) = true := by decide +kernel

theorem K5_9_5_q14 : go 5 7 (stepAll 5 4 (stepAll 5 1 (wordItems 5 CoveringCerts.Data.K5_9_5))) = true := by decide +kernel

theorem K5_9_5_q20 : go 5 7 (stepAll 5 0 (stepAll 5 2 (wordItems 5 CoveringCerts.Data.K5_9_5))) = true := by decide +kernel

theorem K5_9_5_q21 : go 5 7 (stepAll 5 1 (stepAll 5 2 (wordItems 5 CoveringCerts.Data.K5_9_5))) = true := by decide +kernel

theorem K5_9_5_q22 : go 5 7 (stepAll 5 2 (stepAll 5 2 (wordItems 5 CoveringCerts.Data.K5_9_5))) = true := by decide +kernel

theorem K5_9_5_q23 : go 5 7 (stepAll 5 3 (stepAll 5 2 (wordItems 5 CoveringCerts.Data.K5_9_5))) = true := by decide +kernel

theorem K5_9_5_q24 : go 5 7 (stepAll 5 4 (stepAll 5 2 (wordItems 5 CoveringCerts.Data.K5_9_5))) = true := by decide +kernel

theorem K5_9_5_q30 : go 5 7 (stepAll 5 0 (stepAll 5 3 (wordItems 5 CoveringCerts.Data.K5_9_5))) = true := by decide +kernel

theorem K5_9_5_q31 : go 5 7 (stepAll 5 1 (stepAll 5 3 (wordItems 5 CoveringCerts.Data.K5_9_5))) = true := by decide +kernel

theorem K5_9_5_q32 : go 5 7 (stepAll 5 2 (stepAll 5 3 (wordItems 5 CoveringCerts.Data.K5_9_5))) = true := by decide +kernel

theorem K5_9_5_q33 : go 5 7 (stepAll 5 3 (stepAll 5 3 (wordItems 5 CoveringCerts.Data.K5_9_5))) = true := by decide +kernel

end CoveringKernel
