import CoveringLean.K2_Core
import CoveringLean.C1_Data_K5_10_4

/-!
GENERATED by gen.py (frente 1b, 2026-10-02; copy of ~/h/b/gen/gen.py + Final via cert_of_go) -- kernel tier, `decide +kernel` only.
cell: K5_10_4  q=5 n=10 R=4 M=625; data = `CoveringCerts.Data.K5_10_4` (C1_Data_K5_10_4.lean, sha256 in its header).
leaves: all 5^4 prefixes of length 4; each leaf is `go 5 6 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K5_10_4_q0032 : go 5 6 (stepAll 5 2 (stepAll 5 3 (stepAll 5 0 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0033 : go 5 6 (stepAll 5 3 (stepAll 5 3 (stepAll 5 0 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0034 : go 5 6 (stepAll 5 4 (stepAll 5 3 (stepAll 5 0 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0040 : go 5 6 (stepAll 5 0 (stepAll 5 4 (stepAll 5 0 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0041 : go 5 6 (stepAll 5 1 (stepAll 5 4 (stepAll 5 0 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0042 : go 5 6 (stepAll 5 2 (stepAll 5 4 (stepAll 5 0 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0043 : go 5 6 (stepAll 5 3 (stepAll 5 4 (stepAll 5 0 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0044 : go 5 6 (stepAll 5 4 (stepAll 5 4 (stepAll 5 0 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0100 : go 5 6 (stepAll 5 0 (stepAll 5 0 (stepAll 5 1 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0101 : go 5 6 (stepAll 5 1 (stepAll 5 0 (stepAll 5 1 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0102 : go 5 6 (stepAll 5 2 (stepAll 5 0 (stepAll 5 1 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0103 : go 5 6 (stepAll 5 3 (stepAll 5 0 (stepAll 5 1 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0104 : go 5 6 (stepAll 5 4 (stepAll 5 0 (stepAll 5 1 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0110 : go 5 6 (stepAll 5 0 (stepAll 5 1 (stepAll 5 1 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0111 : go 5 6 (stepAll 5 1 (stepAll 5 1 (stepAll 5 1 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0112 : go 5 6 (stepAll 5 2 (stepAll 5 1 (stepAll 5 1 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0113 : go 5 6 (stepAll 5 3 (stepAll 5 1 (stepAll 5 1 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

end CoveringKernel
