import CoveringLean.K2_Core
import CoveringLean.C1_CoverCheck
import CoveringLean.K3_K7_8_3_P1
import CoveringLean.K3_K7_8_3_P2
import CoveringLean.K3_K7_8_3_P3
import CoveringLean.K3_K7_8_3_P4
import CoveringLean.K3_K7_8_3_P5
import CoveringLean.K3_K7_8_3_P6
import CoveringLean.K3_K7_8_3_P7
import CoveringLean.K3_K7_8_3_P8
import CoveringLean.K3_K7_8_3_P9
import CoveringLean.K3_K7_8_3_P10
import CoveringLean.K3_K7_8_3_P11
import CoveringLean.K3_K7_8_3_P12
import CoveringLean.K3_K7_8_3_P13
import CoveringLean.K3_K7_8_3_P14
import CoveringLean.K3_K7_8_3_P15
import CoveringLean.K3_K7_8_3_P16
import CoveringLean.K3_K7_8_3_P17
import CoveringLean.K3_K7_8_3_P18
import CoveringLean.K3_K7_8_3_P19
import CoveringLean.K3_K7_8_3_P20
import CoveringLean.K3_K7_8_3_P21
import CoveringLean.K3_K7_8_3_P22
import CoveringLean.K3_K7_8_3_P23
import CoveringLean.K3_K7_8_3_P24
import CoveringLean.K3_K7_8_3_P25

/-!
GENERATED by gen.py (frente 1a, 2026-10-02) -- kernel tier, `decide +kernel` only.
cell: K7_8_3  q=7 n=8 R=3 M=1893; data = `CoveringCerts.Data.K7_8_3` (C1_Data_K7_8_3.lean, sha256 in its header).
leaves: all 7^3 prefixes of length 3; each leaf is `go 7 5 (stepAll ... (wordItems 3 W)) = true`.
-/

namespace CoveringKernel

theorem K7_8_3_q00 : go 7 6 (stepAll 7 0 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 0 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q000
  · exact K7_8_3_q001
  · exact K7_8_3_q002
  · exact K7_8_3_q003
  · exact K7_8_3_q004
  · exact K7_8_3_q005
  · exact K7_8_3_q006
  )

theorem K7_8_3_q01 : go 7 6 (stepAll 7 1 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 1 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q010
  · exact K7_8_3_q011
  · exact K7_8_3_q012
  · exact K7_8_3_q013
  · exact K7_8_3_q014
  · exact K7_8_3_q015
  · exact K7_8_3_q016
  )

theorem K7_8_3_q02 : go 7 6 (stepAll 7 2 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 2 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q020
  · exact K7_8_3_q021
  · exact K7_8_3_q022
  · exact K7_8_3_q023
  · exact K7_8_3_q024
  · exact K7_8_3_q025
  · exact K7_8_3_q026
  )

theorem K7_8_3_q03 : go 7 6 (stepAll 7 3 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 3 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q030
  · exact K7_8_3_q031
  · exact K7_8_3_q032
  · exact K7_8_3_q033
  · exact K7_8_3_q034
  · exact K7_8_3_q035
  · exact K7_8_3_q036
  )

theorem K7_8_3_q04 : go 7 6 (stepAll 7 4 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 4 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q040
  · exact K7_8_3_q041
  · exact K7_8_3_q042
  · exact K7_8_3_q043
  · exact K7_8_3_q044
  · exact K7_8_3_q045
  · exact K7_8_3_q046
  )

theorem K7_8_3_q05 : go 7 6 (stepAll 7 5 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 5 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q050
  · exact K7_8_3_q051
  · exact K7_8_3_q052
  · exact K7_8_3_q053
  · exact K7_8_3_q054
  · exact K7_8_3_q055
  · exact K7_8_3_q056
  )

theorem K7_8_3_q06 : go 7 6 (stepAll 7 6 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 6 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q060
  · exact K7_8_3_q061
  · exact K7_8_3_q062
  · exact K7_8_3_q063
  · exact K7_8_3_q064
  · exact K7_8_3_q065
  · exact K7_8_3_q066
  )

theorem K7_8_3_q10 : go 7 6 (stepAll 7 0 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 0 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q100
  · exact K7_8_3_q101
  · exact K7_8_3_q102
  · exact K7_8_3_q103
  · exact K7_8_3_q104
  · exact K7_8_3_q105
  · exact K7_8_3_q106
  )

theorem K7_8_3_q11 : go 7 6 (stepAll 7 1 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 1 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q110
  · exact K7_8_3_q111
  · exact K7_8_3_q112
  · exact K7_8_3_q113
  · exact K7_8_3_q114
  · exact K7_8_3_q115
  · exact K7_8_3_q116
  )

theorem K7_8_3_q12 : go 7 6 (stepAll 7 2 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 2 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q120
  · exact K7_8_3_q121
  · exact K7_8_3_q122
  · exact K7_8_3_q123
  · exact K7_8_3_q124
  · exact K7_8_3_q125
  · exact K7_8_3_q126
  )

theorem K7_8_3_q13 : go 7 6 (stepAll 7 3 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 3 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q130
  · exact K7_8_3_q131
  · exact K7_8_3_q132
  · exact K7_8_3_q133
  · exact K7_8_3_q134
  · exact K7_8_3_q135
  · exact K7_8_3_q136
  )

theorem K7_8_3_q14 : go 7 6 (stepAll 7 4 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 4 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q140
  · exact K7_8_3_q141
  · exact K7_8_3_q142
  · exact K7_8_3_q143
  · exact K7_8_3_q144
  · exact K7_8_3_q145
  · exact K7_8_3_q146
  )

theorem K7_8_3_q15 : go 7 6 (stepAll 7 5 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 5 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q150
  · exact K7_8_3_q151
  · exact K7_8_3_q152
  · exact K7_8_3_q153
  · exact K7_8_3_q154
  · exact K7_8_3_q155
  · exact K7_8_3_q156
  )

theorem K7_8_3_q16 : go 7 6 (stepAll 7 6 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 6 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q160
  · exact K7_8_3_q161
  · exact K7_8_3_q162
  · exact K7_8_3_q163
  · exact K7_8_3_q164
  · exact K7_8_3_q165
  · exact K7_8_3_q166
  )

theorem K7_8_3_q20 : go 7 6 (stepAll 7 0 (stepAll 7 2 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 0 (stepAll 7 2 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q200
  · exact K7_8_3_q201
  · exact K7_8_3_q202
  · exact K7_8_3_q203
  · exact K7_8_3_q204
  · exact K7_8_3_q205
  · exact K7_8_3_q206
  )

theorem K7_8_3_q21 : go 7 6 (stepAll 7 1 (stepAll 7 2 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 1 (stepAll 7 2 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q210
  · exact K7_8_3_q211
  · exact K7_8_3_q212
  · exact K7_8_3_q213
  · exact K7_8_3_q214
  · exact K7_8_3_q215
  · exact K7_8_3_q216
  )

theorem K7_8_3_q22 : go 7 6 (stepAll 7 2 (stepAll 7 2 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 2 (stepAll 7 2 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q220
  · exact K7_8_3_q221
  · exact K7_8_3_q222
  · exact K7_8_3_q223
  · exact K7_8_3_q224
  · exact K7_8_3_q225
  · exact K7_8_3_q226
  )

theorem K7_8_3_q23 : go 7 6 (stepAll 7 3 (stepAll 7 2 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 3 (stepAll 7 2 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q230
  · exact K7_8_3_q231
  · exact K7_8_3_q232
  · exact K7_8_3_q233
  · exact K7_8_3_q234
  · exact K7_8_3_q235
  · exact K7_8_3_q236
  )

theorem K7_8_3_q24 : go 7 6 (stepAll 7 4 (stepAll 7 2 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 4 (stepAll 7 2 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q240
  · exact K7_8_3_q241
  · exact K7_8_3_q242
  · exact K7_8_3_q243
  · exact K7_8_3_q244
  · exact K7_8_3_q245
  · exact K7_8_3_q246
  )

theorem K7_8_3_q25 : go 7 6 (stepAll 7 5 (stepAll 7 2 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 5 (stepAll 7 2 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q250
  · exact K7_8_3_q251
  · exact K7_8_3_q252
  · exact K7_8_3_q253
  · exact K7_8_3_q254
  · exact K7_8_3_q255
  · exact K7_8_3_q256
  )

theorem K7_8_3_q26 : go 7 6 (stepAll 7 6 (stepAll 7 2 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 6 (stepAll 7 2 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q260
  · exact K7_8_3_q261
  · exact K7_8_3_q262
  · exact K7_8_3_q263
  · exact K7_8_3_q264
  · exact K7_8_3_q265
  · exact K7_8_3_q266
  )

theorem K7_8_3_q30 : go 7 6 (stepAll 7 0 (stepAll 7 3 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 0 (stepAll 7 3 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q300
  · exact K7_8_3_q301
  · exact K7_8_3_q302
  · exact K7_8_3_q303
  · exact K7_8_3_q304
  · exact K7_8_3_q305
  · exact K7_8_3_q306
  )

theorem K7_8_3_q31 : go 7 6 (stepAll 7 1 (stepAll 7 3 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 1 (stepAll 7 3 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q310
  · exact K7_8_3_q311
  · exact K7_8_3_q312
  · exact K7_8_3_q313
  · exact K7_8_3_q314
  · exact K7_8_3_q315
  · exact K7_8_3_q316
  )

theorem K7_8_3_q32 : go 7 6 (stepAll 7 2 (stepAll 7 3 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 2 (stepAll 7 3 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q320
  · exact K7_8_3_q321
  · exact K7_8_3_q322
  · exact K7_8_3_q323
  · exact K7_8_3_q324
  · exact K7_8_3_q325
  · exact K7_8_3_q326
  )

theorem K7_8_3_q33 : go 7 6 (stepAll 7 3 (stepAll 7 3 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 3 (stepAll 7 3 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q330
  · exact K7_8_3_q331
  · exact K7_8_3_q332
  · exact K7_8_3_q333
  · exact K7_8_3_q334
  · exact K7_8_3_q335
  · exact K7_8_3_q336
  )

theorem K7_8_3_q34 : go 7 6 (stepAll 7 4 (stepAll 7 3 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 4 (stepAll 7 3 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q340
  · exact K7_8_3_q341
  · exact K7_8_3_q342
  · exact K7_8_3_q343
  · exact K7_8_3_q344
  · exact K7_8_3_q345
  · exact K7_8_3_q346
  )

theorem K7_8_3_q35 : go 7 6 (stepAll 7 5 (stepAll 7 3 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 5 (stepAll 7 3 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q350
  · exact K7_8_3_q351
  · exact K7_8_3_q352
  · exact K7_8_3_q353
  · exact K7_8_3_q354
  · exact K7_8_3_q355
  · exact K7_8_3_q356
  )

theorem K7_8_3_q36 : go 7 6 (stepAll 7 6 (stepAll 7 3 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 6 (stepAll 7 3 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q360
  · exact K7_8_3_q361
  · exact K7_8_3_q362
  · exact K7_8_3_q363
  · exact K7_8_3_q364
  · exact K7_8_3_q365
  · exact K7_8_3_q366
  )

theorem K7_8_3_q40 : go 7 6 (stepAll 7 0 (stepAll 7 4 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 0 (stepAll 7 4 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q400
  · exact K7_8_3_q401
  · exact K7_8_3_q402
  · exact K7_8_3_q403
  · exact K7_8_3_q404
  · exact K7_8_3_q405
  · exact K7_8_3_q406
  )

theorem K7_8_3_q41 : go 7 6 (stepAll 7 1 (stepAll 7 4 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 1 (stepAll 7 4 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q410
  · exact K7_8_3_q411
  · exact K7_8_3_q412
  · exact K7_8_3_q413
  · exact K7_8_3_q414
  · exact K7_8_3_q415
  · exact K7_8_3_q416
  )

theorem K7_8_3_q42 : go 7 6 (stepAll 7 2 (stepAll 7 4 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 2 (stepAll 7 4 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q420
  · exact K7_8_3_q421
  · exact K7_8_3_q422
  · exact K7_8_3_q423
  · exact K7_8_3_q424
  · exact K7_8_3_q425
  · exact K7_8_3_q426
  )

theorem K7_8_3_q43 : go 7 6 (stepAll 7 3 (stepAll 7 4 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 3 (stepAll 7 4 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q430
  · exact K7_8_3_q431
  · exact K7_8_3_q432
  · exact K7_8_3_q433
  · exact K7_8_3_q434
  · exact K7_8_3_q435
  · exact K7_8_3_q436
  )

theorem K7_8_3_q44 : go 7 6 (stepAll 7 4 (stepAll 7 4 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 4 (stepAll 7 4 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q440
  · exact K7_8_3_q441
  · exact K7_8_3_q442
  · exact K7_8_3_q443
  · exact K7_8_3_q444
  · exact K7_8_3_q445
  · exact K7_8_3_q446
  )

theorem K7_8_3_q45 : go 7 6 (stepAll 7 5 (stepAll 7 4 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 5 (stepAll 7 4 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q450
  · exact K7_8_3_q451
  · exact K7_8_3_q452
  · exact K7_8_3_q453
  · exact K7_8_3_q454
  · exact K7_8_3_q455
  · exact K7_8_3_q456
  )

theorem K7_8_3_q46 : go 7 6 (stepAll 7 6 (stepAll 7 4 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 6 (stepAll 7 4 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q460
  · exact K7_8_3_q461
  · exact K7_8_3_q462
  · exact K7_8_3_q463
  · exact K7_8_3_q464
  · exact K7_8_3_q465
  · exact K7_8_3_q466
  )

theorem K7_8_3_q50 : go 7 6 (stepAll 7 0 (stepAll 7 5 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 0 (stepAll 7 5 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q500
  · exact K7_8_3_q501
  · exact K7_8_3_q502
  · exact K7_8_3_q503
  · exact K7_8_3_q504
  · exact K7_8_3_q505
  · exact K7_8_3_q506
  )

theorem K7_8_3_q51 : go 7 6 (stepAll 7 1 (stepAll 7 5 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 1 (stepAll 7 5 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q510
  · exact K7_8_3_q511
  · exact K7_8_3_q512
  · exact K7_8_3_q513
  · exact K7_8_3_q514
  · exact K7_8_3_q515
  · exact K7_8_3_q516
  )

theorem K7_8_3_q52 : go 7 6 (stepAll 7 2 (stepAll 7 5 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 2 (stepAll 7 5 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q520
  · exact K7_8_3_q521
  · exact K7_8_3_q522
  · exact K7_8_3_q523
  · exact K7_8_3_q524
  · exact K7_8_3_q525
  · exact K7_8_3_q526
  )

theorem K7_8_3_q53 : go 7 6 (stepAll 7 3 (stepAll 7 5 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 3 (stepAll 7 5 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q530
  · exact K7_8_3_q531
  · exact K7_8_3_q532
  · exact K7_8_3_q533
  · exact K7_8_3_q534
  · exact K7_8_3_q535
  · exact K7_8_3_q536
  )

theorem K7_8_3_q54 : go 7 6 (stepAll 7 4 (stepAll 7 5 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 4 (stepAll 7 5 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q540
  · exact K7_8_3_q541
  · exact K7_8_3_q542
  · exact K7_8_3_q543
  · exact K7_8_3_q544
  · exact K7_8_3_q545
  · exact K7_8_3_q546
  )

theorem K7_8_3_q55 : go 7 6 (stepAll 7 5 (stepAll 7 5 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 5 (stepAll 7 5 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q550
  · exact K7_8_3_q551
  · exact K7_8_3_q552
  · exact K7_8_3_q553
  · exact K7_8_3_q554
  · exact K7_8_3_q555
  · exact K7_8_3_q556
  )

theorem K7_8_3_q56 : go 7 6 (stepAll 7 6 (stepAll 7 5 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 6 (stepAll 7 5 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q560
  · exact K7_8_3_q561
  · exact K7_8_3_q562
  · exact K7_8_3_q563
  · exact K7_8_3_q564
  · exact K7_8_3_q565
  · exact K7_8_3_q566
  )

theorem K7_8_3_q60 : go 7 6 (stepAll 7 0 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 0 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q600
  · exact K7_8_3_q601
  · exact K7_8_3_q602
  · exact K7_8_3_q603
  · exact K7_8_3_q604
  · exact K7_8_3_q605
  · exact K7_8_3_q606
  )

theorem K7_8_3_q61 : go 7 6 (stepAll 7 1 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 1 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q610
  · exact K7_8_3_q611
  · exact K7_8_3_q612
  · exact K7_8_3_q613
  · exact K7_8_3_q614
  · exact K7_8_3_q615
  · exact K7_8_3_q616
  )

theorem K7_8_3_q62 : go 7 6 (stepAll 7 2 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 2 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q620
  · exact K7_8_3_q621
  · exact K7_8_3_q622
  · exact K7_8_3_q623
  · exact K7_8_3_q624
  · exact K7_8_3_q625
  · exact K7_8_3_q626
  )

theorem K7_8_3_q63 : go 7 6 (stepAll 7 3 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 3 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q630
  · exact K7_8_3_q631
  · exact K7_8_3_q632
  · exact K7_8_3_q633
  · exact K7_8_3_q634
  · exact K7_8_3_q635
  · exact K7_8_3_q636
  )

theorem K7_8_3_q64 : go 7 6 (stepAll 7 4 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 4 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q640
  · exact K7_8_3_q641
  · exact K7_8_3_q642
  · exact K7_8_3_q643
  · exact K7_8_3_q644
  · exact K7_8_3_q645
  · exact K7_8_3_q646
  )

theorem K7_8_3_q65 : go 7 6 (stepAll 7 5 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 5 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q650
  · exact K7_8_3_q651
  · exact K7_8_3_q652
  · exact K7_8_3_q653
  · exact K7_8_3_q654
  · exact K7_8_3_q655
  · exact K7_8_3_q656
  )

theorem K7_8_3_q66 : go 7 6 (stepAll 7 6 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3))) = true :=
  go_split 7 5 (stepAll 7 6 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3))) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q660
  · exact K7_8_3_q661
  · exact K7_8_3_q662
  · exact K7_8_3_q663
  · exact K7_8_3_q664
  · exact K7_8_3_q665
  · exact K7_8_3_q666
  )

theorem K7_8_3_q0 : go 7 7 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3)) = true :=
  go_split 7 6 (stepAll 7 0 (wordItems 3 CoveringCerts.Data.K7_8_3)) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q00
  · exact K7_8_3_q01
  · exact K7_8_3_q02
  · exact K7_8_3_q03
  · exact K7_8_3_q04
  · exact K7_8_3_q05
  · exact K7_8_3_q06
  )

theorem K7_8_3_q1 : go 7 7 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3)) = true :=
  go_split 7 6 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3)) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q10
  · exact K7_8_3_q11
  · exact K7_8_3_q12
  · exact K7_8_3_q13
  · exact K7_8_3_q14
  · exact K7_8_3_q15
  · exact K7_8_3_q16
  )

theorem K7_8_3_q2 : go 7 7 (stepAll 7 2 (wordItems 3 CoveringCerts.Data.K7_8_3)) = true :=
  go_split 7 6 (stepAll 7 2 (wordItems 3 CoveringCerts.Data.K7_8_3)) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q20
  · exact K7_8_3_q21
  · exact K7_8_3_q22
  · exact K7_8_3_q23
  · exact K7_8_3_q24
  · exact K7_8_3_q25
  · exact K7_8_3_q26
  )

theorem K7_8_3_q3 : go 7 7 (stepAll 7 3 (wordItems 3 CoveringCerts.Data.K7_8_3)) = true :=
  go_split 7 6 (stepAll 7 3 (wordItems 3 CoveringCerts.Data.K7_8_3)) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q30
  · exact K7_8_3_q31
  · exact K7_8_3_q32
  · exact K7_8_3_q33
  · exact K7_8_3_q34
  · exact K7_8_3_q35
  · exact K7_8_3_q36
  )

theorem K7_8_3_q4 : go 7 7 (stepAll 7 4 (wordItems 3 CoveringCerts.Data.K7_8_3)) = true :=
  go_split 7 6 (stepAll 7 4 (wordItems 3 CoveringCerts.Data.K7_8_3)) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q40
  · exact K7_8_3_q41
  · exact K7_8_3_q42
  · exact K7_8_3_q43
  · exact K7_8_3_q44
  · exact K7_8_3_q45
  · exact K7_8_3_q46
  )

theorem K7_8_3_q5 : go 7 7 (stepAll 7 5 (wordItems 3 CoveringCerts.Data.K7_8_3)) = true :=
  go_split 7 6 (stepAll 7 5 (wordItems 3 CoveringCerts.Data.K7_8_3)) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q50
  · exact K7_8_3_q51
  · exact K7_8_3_q52
  · exact K7_8_3_q53
  · exact K7_8_3_q54
  · exact K7_8_3_q55
  · exact K7_8_3_q56
  )

theorem K7_8_3_q6 : go 7 7 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3)) = true :=
  go_split 7 6 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3)) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q60
  · exact K7_8_3_q61
  · exact K7_8_3_q62
  · exact K7_8_3_q63
  · exact K7_8_3_q64
  · exact K7_8_3_q65
  · exact K7_8_3_q66
  )

theorem K7_8_3_q : go 7 8 (wordItems 3 CoveringCerts.Data.K7_8_3) = true :=
  go_split 7 7 (wordItems 3 CoveringCerts.Data.K7_8_3) (by
  intro v hv
  interval_cases v
  · exact K7_8_3_q0
  · exact K7_8_3_q1
  · exact K7_8_3_q2
  · exact K7_8_3_q3
  · exact K7_8_3_q4
  · exact K7_8_3_q5
  · exact K7_8_3_q6
  )

theorem K7_8_3_le_1893_kernel_le :
    ∃ C : Finset (Fin 8 → ZMod 7), C.card ≤ 1893 ∧ CoveringA2.Covers 3 C := by
  have h := cover_simple 7 8 3 CoveringCerts.Data.K7_8_3 K7_8_3_q
  have hl : CoveringCerts.Data.K7_8_3.length = 1893 := by decide +kernel
  rw [hl] at h
  exact h

end CoveringKernel

#print axioms CoveringKernel.K7_8_3_le_1893_kernel_le
