import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q1425 : go 7 5 (stepAll 7 5 (stepAll 7 2 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1426 : go 7 5 (stepAll 7 6 (stepAll 7 2 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1430 : go 7 5 (stepAll 7 0 (stepAll 7 3 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1431 : go 7 5 (stepAll 7 1 (stepAll 7 3 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1432 : go 7 5 (stepAll 7 2 (stepAll 7 3 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1433 : go 7 5 (stepAll 7 3 (stepAll 7 3 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1434 : go 7 5 (stepAll 7 4 (stepAll 7 3 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1435 : go 7 5 (stepAll 7 5 (stepAll 7 3 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1436 : go 7 5 (stepAll 7 6 (stepAll 7 3 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1440 : go 7 5 (stepAll 7 0 (stepAll 7 4 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1441 : go 7 5 (stepAll 7 1 (stepAll 7 4 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1442 : go 7 5 (stepAll 7 2 (stepAll 7 4 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1443 : go 7 5 (stepAll 7 3 (stepAll 7 4 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1444 : go 7 5 (stepAll 7 4 (stepAll 7 4 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1445 : go 7 5 (stepAll 7 5 (stepAll 7 4 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1446 : go 7 5 (stepAll 7 6 (stepAll 7 4 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1450 : go 7 5 (stepAll 7 0 (stepAll 7 5 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1451 : go 7 5 (stepAll 7 1 (stepAll 7 5 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1452 : go 7 5 (stepAll 7 2 (stepAll 7 5 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1453 : go 7 5 (stepAll 7 3 (stepAll 7 5 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1454 : go 7 5 (stepAll 7 4 (stepAll 7 5 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1455 : go 7 5 (stepAll 7 5 (stepAll 7 5 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1456 : go 7 5 (stepAll 7 6 (stepAll 7 5 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1460 : go 7 5 (stepAll 7 0 (stepAll 7 6 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1461 : go 7 5 (stepAll 7 1 (stepAll 7 6 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
