import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q1156 : go 7 5 (stepAll 7 6 (stepAll 7 5 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1160 : go 7 5 (stepAll 7 0 (stepAll 7 6 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1161 : go 7 5 (stepAll 7 1 (stepAll 7 6 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1162 : go 7 5 (stepAll 7 2 (stepAll 7 6 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1163 : go 7 5 (stepAll 7 3 (stepAll 7 6 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1164 : go 7 5 (stepAll 7 4 (stepAll 7 6 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1165 : go 7 5 (stepAll 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1166 : go 7 5 (stepAll 7 6 (stepAll 7 6 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1200 : go 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1201 : go 7 5 (stepAll 7 1 (stepAll 7 0 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1202 : go 7 5 (stepAll 7 2 (stepAll 7 0 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1203 : go 7 5 (stepAll 7 3 (stepAll 7 0 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1204 : go 7 5 (stepAll 7 4 (stepAll 7 0 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1205 : go 7 5 (stepAll 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1206 : go 7 5 (stepAll 7 6 (stepAll 7 0 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1210 : go 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1211 : go 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1212 : go 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1213 : go 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1214 : go 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1215 : go 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1216 : go 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1220 : go 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1221 : go 7 5 (stepAll 7 1 (stepAll 7 2 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1222 : go 7 5 (stepAll 7 2 (stepAll 7 2 (stepAll 7 2 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
