import CoveringLean.K2_Core
import CoveringLean.C1_Data_K4_10_4

/-!
GENERATED by gen.py (frente 1b, 2026-10-02; copy of ~/h/b/gen/gen.py + Final via cert_of_go) -- kernel tier, `decide +kernel` only.
cell: K4_10_4  q=4 n=10 R=4 M=192; data = `CoveringCerts.Data.K4_10_4` (C1_Data_K4_10_4.lean, sha256 in its header).
leaves: all 4^3 prefixes of length 3; each leaf is `go 4 7 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K4_10_4_q000 : go 4 7 (stepAll 4 0 (stepAll 4 0 (stepAll 4 0 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q001 : go 4 7 (stepAll 4 1 (stepAll 4 0 (stepAll 4 0 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q002 : go 4 7 (stepAll 4 2 (stepAll 4 0 (stepAll 4 0 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q003 : go 4 7 (stepAll 4 3 (stepAll 4 0 (stepAll 4 0 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q010 : go 4 7 (stepAll 4 0 (stepAll 4 1 (stepAll 4 0 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q011 : go 4 7 (stepAll 4 1 (stepAll 4 1 (stepAll 4 0 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q012 : go 4 7 (stepAll 4 2 (stepAll 4 1 (stepAll 4 0 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q013 : go 4 7 (stepAll 4 3 (stepAll 4 1 (stepAll 4 0 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q020 : go 4 7 (stepAll 4 0 (stepAll 4 2 (stepAll 4 0 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q021 : go 4 7 (stepAll 4 1 (stepAll 4 2 (stepAll 4 0 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q022 : go 4 7 (stepAll 4 2 (stepAll 4 2 (stepAll 4 0 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q023 : go 4 7 (stepAll 4 3 (stepAll 4 2 (stepAll 4 0 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q030 : go 4 7 (stepAll 4 0 (stepAll 4 3 (stepAll 4 0 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q031 : go 4 7 (stepAll 4 1 (stepAll 4 3 (stepAll 4 0 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q032 : go 4 7 (stepAll 4 2 (stepAll 4 3 (stepAll 4 0 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q033 : go 4 7 (stepAll 4 3 (stepAll 4 3 (stepAll 4 0 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q100 : go 4 7 (stepAll 4 0 (stepAll 4 0 (stepAll 4 1 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q101 : go 4 7 (stepAll 4 1 (stepAll 4 0 (stepAll 4 1 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q102 : go 4 7 (stepAll 4 2 (stepAll 4 0 (stepAll 4 1 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q103 : go 4 7 (stepAll 4 3 (stepAll 4 0 (stepAll 4 1 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

theorem K4_10_4_q110 : go 4 7 (stepAll 4 0 (stepAll 4 1 (stepAll 4 1 (wordItems 4 CoveringCerts.Data.K4_10_4)))) = true := by decide +kernel

end CoveringKernel
