import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q1665 : go 7 5 (stepAll 7 5 (stepAll 7 6 (stepAll 7 6 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1666 : go 7 5 (stepAll 7 6 (stepAll 7 6 (stepAll 7 6 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2000 : go 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 0 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2001 : go 7 5 (stepAll 7 1 (stepAll 7 0 (stepAll 7 0 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2002 : go 7 5 (stepAll 7 2 (stepAll 7 0 (stepAll 7 0 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2003 : go 7 5 (stepAll 7 3 (stepAll 7 0 (stepAll 7 0 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2004 : go 7 5 (stepAll 7 4 (stepAll 7 0 (stepAll 7 0 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2005 : go 7 5 (stepAll 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2006 : go 7 5 (stepAll 7 6 (stepAll 7 0 (stepAll 7 0 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2010 : go 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 0 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2011 : go 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 0 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2012 : go 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 0 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2013 : go 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 0 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2014 : go 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 0 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2015 : go 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 0 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2016 : go 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 0 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2020 : go 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 0 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2021 : go 7 5 (stepAll 7 1 (stepAll 7 2 (stepAll 7 0 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2022 : go 7 5 (stepAll 7 2 (stepAll 7 2 (stepAll 7 0 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2023 : go 7 5 (stepAll 7 3 (stepAll 7 2 (stepAll 7 0 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2024 : go 7 5 (stepAll 7 4 (stepAll 7 2 (stepAll 7 0 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2025 : go 7 5 (stepAll 7 5 (stepAll 7 2 (stepAll 7 0 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2026 : go 7 5 (stepAll 7 6 (stepAll 7 2 (stepAll 7 0 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2030 : go 7 5 (stepAll 7 0 (stepAll 7 3 (stepAll 7 0 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2031 : go 7 5 (stepAll 7 1 (stepAll 7 3 (stepAll 7 0 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
