import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q6464 : go 7 5 (stepAll 7 4 (stepAll 7 6 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6465 : go 7 5 (stepAll 7 5 (stepAll 7 6 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6466 : go 7 5 (stepAll 7 6 (stepAll 7 6 (stepAll 7 4 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6500 : go 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 5 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6501 : go 7 5 (stepAll 7 1 (stepAll 7 0 (stepAll 7 5 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6502 : go 7 5 (stepAll 7 2 (stepAll 7 0 (stepAll 7 5 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6503 : go 7 5 (stepAll 7 3 (stepAll 7 0 (stepAll 7 5 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6504 : go 7 5 (stepAll 7 4 (stepAll 7 0 (stepAll 7 5 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6505 : go 7 5 (stepAll 7 5 (stepAll 7 0 (stepAll 7 5 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6506 : go 7 5 (stepAll 7 6 (stepAll 7 0 (stepAll 7 5 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6510 : go 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 5 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6511 : go 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 5 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6512 : go 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 5 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6513 : go 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 5 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6514 : go 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 5 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6515 : go 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 5 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6516 : go 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 5 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6520 : go 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 5 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6521 : go 7 5 (stepAll 7 1 (stepAll 7 2 (stepAll 7 5 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6522 : go 7 5 (stepAll 7 2 (stepAll 7 2 (stepAll 7 5 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6523 : go 7 5 (stepAll 7 3 (stepAll 7 2 (stepAll 7 5 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6524 : go 7 5 (stepAll 7 4 (stepAll 7 2 (stepAll 7 5 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6525 : go 7 5 (stepAll 7 5 (stepAll 7 2 (stepAll 7 5 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6526 : go 7 5 (stepAll 7 6 (stepAll 7 2 (stepAll 7 5 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6530 : go 7 5 (stepAll 7 0 (stepAll 7 3 (stepAll 7 5 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6531 : go 7 5 (stepAll 7 1 (stepAll 7 3 (stepAll 7 5 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
