import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q2135 : go 7 5 (stepAll 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2136 : go 7 5 (stepAll 7 6 (stepAll 7 3 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2140 : go 7 5 (stepAll 7 0 (stepAll 7 4 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2141 : go 7 5 (stepAll 7 1 (stepAll 7 4 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2142 : go 7 5 (stepAll 7 2 (stepAll 7 4 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2143 : go 7 5 (stepAll 7 3 (stepAll 7 4 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2144 : go 7 5 (stepAll 7 4 (stepAll 7 4 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2145 : go 7 5 (stepAll 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2146 : go 7 5 (stepAll 7 6 (stepAll 7 4 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2150 : go 7 5 (stepAll 7 0 (stepAll 7 5 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2151 : go 7 5 (stepAll 7 1 (stepAll 7 5 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2152 : go 7 5 (stepAll 7 2 (stepAll 7 5 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2153 : go 7 5 (stepAll 7 3 (stepAll 7 5 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2154 : go 7 5 (stepAll 7 4 (stepAll 7 5 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2155 : go 7 5 (stepAll 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2156 : go 7 5 (stepAll 7 6 (stepAll 7 5 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2160 : go 7 5 (stepAll 7 0 (stepAll 7 6 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2161 : go 7 5 (stepAll 7 1 (stepAll 7 6 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2162 : go 7 5 (stepAll 7 2 (stepAll 7 6 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2163 : go 7 5 (stepAll 7 3 (stepAll 7 6 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2164 : go 7 5 (stepAll 7 4 (stepAll 7 6 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2165 : go 7 5 (stepAll 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2166 : go 7 5 (stepAll 7 6 (stepAll 7 6 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2200 : go 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 2 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
