import CoveringLean.K2_Core
import CoveringLean.C1_Data_K5_9_3

/-!
GENERATED by gen.py (frente 1b, 2026-10-02; copy of ~/h/b/gen/gen.py + Final via cert_of_go) -- kernel tier, `decide +kernel` only.
cell: K5_9_3  q=5 n=9 R=3 M=1250; data = `CoveringCerts.Data.K5_9_3` (C1_Data_K5_9_3.lean, sha256 in its header).
leaves: all 5^4 prefixes of length 4; each leaf is `go 5 5 (stepAll ... (wordItems 3 W)) = true`.
-/

namespace CoveringKernel

theorem K5_9_3_q4422 : go 5 5 (stepAll 5 2 (stepAll 5 2 (stepAll 5 4 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4423 : go 5 5 (stepAll 5 3 (stepAll 5 2 (stepAll 5 4 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4424 : go 5 5 (stepAll 5 4 (stepAll 5 2 (stepAll 5 4 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4430 : go 5 5 (stepAll 5 0 (stepAll 5 3 (stepAll 5 4 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4431 : go 5 5 (stepAll 5 1 (stepAll 5 3 (stepAll 5 4 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4432 : go 5 5 (stepAll 5 2 (stepAll 5 3 (stepAll 5 4 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4433 : go 5 5 (stepAll 5 3 (stepAll 5 3 (stepAll 5 4 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4434 : go 5 5 (stepAll 5 4 (stepAll 5 3 (stepAll 5 4 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4440 : go 5 5 (stepAll 5 0 (stepAll 5 4 (stepAll 5 4 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4441 : go 5 5 (stepAll 5 1 (stepAll 5 4 (stepAll 5 4 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4442 : go 5 5 (stepAll 5 2 (stepAll 5 4 (stepAll 5 4 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4443 : go 5 5 (stepAll 5 3 (stepAll 5 4 (stepAll 5 4 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4444 : go 5 5 (stepAll 5 4 (stepAll 5 4 (stepAll 5 4 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

end CoveringKernel
