import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q4503 : go 7 5 (stepAll 7 3 (stepAll 7 0 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4504 : go 7 5 (stepAll 7 4 (stepAll 7 0 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4505 : go 7 5 (stepAll 7 5 (stepAll 7 0 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4506 : go 7 5 (stepAll 7 6 (stepAll 7 0 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4510 : go 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4511 : go 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4512 : go 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4513 : go 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4514 : go 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4515 : go 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4516 : go 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4520 : go 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4521 : go 7 5 (stepAll 7 1 (stepAll 7 2 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4522 : go 7 5 (stepAll 7 2 (stepAll 7 2 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4523 : go 7 5 (stepAll 7 3 (stepAll 7 2 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4524 : go 7 5 (stepAll 7 4 (stepAll 7 2 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4525 : go 7 5 (stepAll 7 5 (stepAll 7 2 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4526 : go 7 5 (stepAll 7 6 (stepAll 7 2 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4530 : go 7 5 (stepAll 7 0 (stepAll 7 3 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4531 : go 7 5 (stepAll 7 1 (stepAll 7 3 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4532 : go 7 5 (stepAll 7 2 (stepAll 7 3 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4533 : go 7 5 (stepAll 7 3 (stepAll 7 3 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4534 : go 7 5 (stepAll 7 4 (stepAll 7 3 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4535 : go 7 5 (stepAll 7 5 (stepAll 7 3 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
