import CoveringLean.K2_Core
import CoveringLean.C1_Data_K5_10_4

/-!
GENERATED by gen.py (frente 1b, 2026-10-02; copy of ~/h/b/gen/gen.py + Final via cert_of_go) -- kernel tier, `decide +kernel` only.
cell: K5_10_4  q=5 n=10 R=4 M=625; data = `CoveringCerts.Data.K5_10_4` (C1_Data_K5_10_4.lean, sha256 in its header).
leaves: all 5^4 prefixes of length 4; each leaf is `go 5 6 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K5_10_4_q3401 : go 5 6 (stepAll 5 1 (stepAll 5 0 (stepAll 5 4 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3402 : go 5 6 (stepAll 5 2 (stepAll 5 0 (stepAll 5 4 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3403 : go 5 6 (stepAll 5 3 (stepAll 5 0 (stepAll 5 4 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3404 : go 5 6 (stepAll 5 4 (stepAll 5 0 (stepAll 5 4 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3410 : go 5 6 (stepAll 5 0 (stepAll 5 1 (stepAll 5 4 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3411 : go 5 6 (stepAll 5 1 (stepAll 5 1 (stepAll 5 4 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3412 : go 5 6 (stepAll 5 2 (stepAll 5 1 (stepAll 5 4 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3413 : go 5 6 (stepAll 5 3 (stepAll 5 1 (stepAll 5 4 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3414 : go 5 6 (stepAll 5 4 (stepAll 5 1 (stepAll 5 4 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3420 : go 5 6 (stepAll 5 0 (stepAll 5 2 (stepAll 5 4 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3421 : go 5 6 (stepAll 5 1 (stepAll 5 2 (stepAll 5 4 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3422 : go 5 6 (stepAll 5 2 (stepAll 5 2 (stepAll 5 4 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3423 : go 5 6 (stepAll 5 3 (stepAll 5 2 (stepAll 5 4 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3424 : go 5 6 (stepAll 5 4 (stepAll 5 2 (stepAll 5 4 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3430 : go 5 6 (stepAll 5 0 (stepAll 5 3 (stepAll 5 4 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3431 : go 5 6 (stepAll 5 1 (stepAll 5 3 (stepAll 5 4 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3432 : go 5 6 (stepAll 5 2 (stepAll 5 3 (stepAll 5 4 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

end CoveringKernel
