import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q2610 : go 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 6 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2611 : go 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 6 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2612 : go 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 6 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2613 : go 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 6 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2614 : go 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 6 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2615 : go 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 6 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2616 : go 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 6 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2620 : go 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 6 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2621 : go 7 5 (stepAll 7 1 (stepAll 7 2 (stepAll 7 6 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2622 : go 7 5 (stepAll 7 2 (stepAll 7 2 (stepAll 7 6 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2623 : go 7 5 (stepAll 7 3 (stepAll 7 2 (stepAll 7 6 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2624 : go 7 5 (stepAll 7 4 (stepAll 7 2 (stepAll 7 6 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2625 : go 7 5 (stepAll 7 5 (stepAll 7 2 (stepAll 7 6 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2626 : go 7 5 (stepAll 7 6 (stepAll 7 2 (stepAll 7 6 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2630 : go 7 5 (stepAll 7 0 (stepAll 7 3 (stepAll 7 6 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2631 : go 7 5 (stepAll 7 1 (stepAll 7 3 (stepAll 7 6 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2632 : go 7 5 (stepAll 7 2 (stepAll 7 3 (stepAll 7 6 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2633 : go 7 5 (stepAll 7 3 (stepAll 7 3 (stepAll 7 6 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2634 : go 7 5 (stepAll 7 4 (stepAll 7 3 (stepAll 7 6 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2635 : go 7 5 (stepAll 7 5 (stepAll 7 3 (stepAll 7 6 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2636 : go 7 5 (stepAll 7 6 (stepAll 7 3 (stepAll 7 6 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2640 : go 7 5 (stepAll 7 0 (stepAll 7 4 (stepAll 7 6 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2641 : go 7 5 (stepAll 7 1 (stepAll 7 4 (stepAll 7 6 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2642 : go 7 5 (stepAll 7 2 (stepAll 7 4 (stepAll 7 6 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2643 : go 7 5 (stepAll 7 3 (stepAll 7 4 (stepAll 7 6 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
