import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q5414 : go 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 4 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5415 : go 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 4 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5416 : go 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 4 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5420 : go 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 4 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5421 : go 7 5 (stepAll 7 1 (stepAll 7 2 (stepAll 7 4 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5422 : go 7 5 (stepAll 7 2 (stepAll 7 2 (stepAll 7 4 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5423 : go 7 5 (stepAll 7 3 (stepAll 7 2 (stepAll 7 4 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5424 : go 7 5 (stepAll 7 4 (stepAll 7 2 (stepAll 7 4 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5425 : go 7 5 (stepAll 7 5 (stepAll 7 2 (stepAll 7 4 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5426 : go 7 5 (stepAll 7 6 (stepAll 7 2 (stepAll 7 4 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5430 : go 7 5 (stepAll 7 0 (stepAll 7 3 (stepAll 7 4 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5431 : go 7 5 (stepAll 7 1 (stepAll 7 3 (stepAll 7 4 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5432 : go 7 5 (stepAll 7 2 (stepAll 7 3 (stepAll 7 4 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5433 : go 7 5 (stepAll 7 3 (stepAll 7 3 (stepAll 7 4 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5434 : go 7 5 (stepAll 7 4 (stepAll 7 3 (stepAll 7 4 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5435 : go 7 5 (stepAll 7 5 (stepAll 7 3 (stepAll 7 4 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5436 : go 7 5 (stepAll 7 6 (stepAll 7 3 (stepAll 7 4 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5440 : go 7 5 (stepAll 7 0 (stepAll 7 4 (stepAll 7 4 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5441 : go 7 5 (stepAll 7 1 (stepAll 7 4 (stepAll 7 4 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5442 : go 7 5 (stepAll 7 2 (stepAll 7 4 (stepAll 7 4 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5443 : go 7 5 (stepAll 7 3 (stepAll 7 4 (stepAll 7 4 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5444 : go 7 5 (stepAll 7 4 (stepAll 7 4 (stepAll 7 4 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5445 : go 7 5 (stepAll 7 5 (stepAll 7 4 (stepAll 7 4 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5446 : go 7 5 (stepAll 7 6 (stepAll 7 4 (stepAll 7 4 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5450 : go 7 5 (stepAll 7 0 (stepAll 7 5 (stepAll 7 4 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
