import CoveringLean.K2_Core
import CoveringLean.C1_Data_K5_10_4

/-!
GENERATED by gen.py (frente 1b, 2026-10-02; copy of ~/h/b/gen/gen.py + Final via cert_of_go) -- kernel tier, `decide +kernel` only.
cell: K5_10_4  q=5 n=10 R=4 M=625; data = `CoveringCerts.Data.K5_10_4` (C1_Data_K5_10_4.lean, sha256 in its header).
leaves: all 5^4 prefixes of length 4; each leaf is `go 5 6 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K5_10_4_q2330 : go 5 6 (stepAll 5 0 (stepAll 5 3 (stepAll 5 3 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2331 : go 5 6 (stepAll 5 1 (stepAll 5 3 (stepAll 5 3 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2332 : go 5 6 (stepAll 5 2 (stepAll 5 3 (stepAll 5 3 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2333 : go 5 6 (stepAll 5 3 (stepAll 5 3 (stepAll 5 3 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2334 : go 5 6 (stepAll 5 4 (stepAll 5 3 (stepAll 5 3 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2340 : go 5 6 (stepAll 5 0 (stepAll 5 4 (stepAll 5 3 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2341 : go 5 6 (stepAll 5 1 (stepAll 5 4 (stepAll 5 3 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2342 : go 5 6 (stepAll 5 2 (stepAll 5 4 (stepAll 5 3 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2343 : go 5 6 (stepAll 5 3 (stepAll 5 4 (stepAll 5 3 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2344 : go 5 6 (stepAll 5 4 (stepAll 5 4 (stepAll 5 3 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2400 : go 5 6 (stepAll 5 0 (stepAll 5 0 (stepAll 5 4 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2401 : go 5 6 (stepAll 5 1 (stepAll 5 0 (stepAll 5 4 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2402 : go 5 6 (stepAll 5 2 (stepAll 5 0 (stepAll 5 4 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2403 : go 5 6 (stepAll 5 3 (stepAll 5 0 (stepAll 5 4 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2404 : go 5 6 (stepAll 5 4 (stepAll 5 0 (stepAll 5 4 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2410 : go 5 6 (stepAll 5 0 (stepAll 5 1 (stepAll 5 4 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2411 : go 5 6 (stepAll 5 1 (stepAll 5 1 (stepAll 5 4 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

end CoveringKernel
