import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q5210 : go 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 2 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5211 : go 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 2 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5212 : go 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 2 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5213 : go 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 2 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5214 : go 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 2 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5215 : go 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 2 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5216 : go 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 2 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5220 : go 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 2 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5221 : go 7 5 (stepAll 7 1 (stepAll 7 2 (stepAll 7 2 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5222 : go 7 5 (stepAll 7 2 (stepAll 7 2 (stepAll 7 2 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5223 : go 7 5 (stepAll 7 3 (stepAll 7 2 (stepAll 7 2 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5224 : go 7 5 (stepAll 7 4 (stepAll 7 2 (stepAll 7 2 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5225 : go 7 5 (stepAll 7 5 (stepAll 7 2 (stepAll 7 2 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5226 : go 7 5 (stepAll 7 6 (stepAll 7 2 (stepAll 7 2 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5230 : go 7 5 (stepAll 7 0 (stepAll 7 3 (stepAll 7 2 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5231 : go 7 5 (stepAll 7 1 (stepAll 7 3 (stepAll 7 2 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5232 : go 7 5 (stepAll 7 2 (stepAll 7 3 (stepAll 7 2 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5233 : go 7 5 (stepAll 7 3 (stepAll 7 3 (stepAll 7 2 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5234 : go 7 5 (stepAll 7 4 (stepAll 7 3 (stepAll 7 2 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5235 : go 7 5 (stepAll 7 5 (stepAll 7 3 (stepAll 7 2 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5236 : go 7 5 (stepAll 7 6 (stepAll 7 3 (stepAll 7 2 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5240 : go 7 5 (stepAll 7 0 (stepAll 7 4 (stepAll 7 2 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5241 : go 7 5 (stepAll 7 1 (stepAll 7 4 (stepAll 7 2 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5242 : go 7 5 (stepAll 7 2 (stepAll 7 4 (stepAll 7 2 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5243 : go 7 5 (stepAll 7 3 (stepAll 7 4 (stepAll 7 2 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
