import CoveringLean.K2_Core
import CoveringLean.C1_Data_K5_9_3

/-!
GENERATED by gen.py (frente 1b, 2026-10-02; copy of ~/h/b/gen/gen.py + Final via cert_of_go) -- kernel tier, `decide +kernel` only.
cell: K5_9_3  q=5 n=9 R=3 M=1250; data = `CoveringCerts.Data.K5_9_3` (C1_Data_K5_9_3.lean, sha256 in its header).
leaves: all 5^4 prefixes of length 4; each leaf is `go 5 5 (stepAll ... (wordItems 3 W)) = true`.
-/

namespace CoveringKernel

theorem K5_9_3_q3113 : go 5 5 (stepAll 5 3 (stepAll 5 1 (stepAll 5 1 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3114 : go 5 5 (stepAll 5 4 (stepAll 5 1 (stepAll 5 1 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3120 : go 5 5 (stepAll 5 0 (stepAll 5 2 (stepAll 5 1 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3121 : go 5 5 (stepAll 5 1 (stepAll 5 2 (stepAll 5 1 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3122 : go 5 5 (stepAll 5 2 (stepAll 5 2 (stepAll 5 1 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3123 : go 5 5 (stepAll 5 3 (stepAll 5 2 (stepAll 5 1 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3124 : go 5 5 (stepAll 5 4 (stepAll 5 2 (stepAll 5 1 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3130 : go 5 5 (stepAll 5 0 (stepAll 5 3 (stepAll 5 1 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3131 : go 5 5 (stepAll 5 1 (stepAll 5 3 (stepAll 5 1 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3132 : go 5 5 (stepAll 5 2 (stepAll 5 3 (stepAll 5 1 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3133 : go 5 5 (stepAll 5 3 (stepAll 5 3 (stepAll 5 1 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3134 : go 5 5 (stepAll 5 4 (stepAll 5 3 (stepAll 5 1 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3140 : go 5 5 (stepAll 5 0 (stepAll 5 4 (stepAll 5 1 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3141 : go 5 5 (stepAll 5 1 (stepAll 5 4 (stepAll 5 1 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3142 : go 5 5 (stepAll 5 2 (stepAll 5 4 (stepAll 5 1 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3143 : go 5 5 (stepAll 5 3 (stepAll 5 4 (stepAll 5 1 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3144 : go 5 5 (stepAll 5 4 (stepAll 5 4 (stepAll 5 1 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3200 : go 5 5 (stepAll 5 0 (stepAll 5 0 (stepAll 5 2 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3201 : go 5 5 (stepAll 5 1 (stepAll 5 0 (stepAll 5 2 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3202 : go 5 5 (stepAll 5 2 (stepAll 5 0 (stepAll 5 2 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3203 : go 5 5 (stepAll 5 3 (stepAll 5 0 (stepAll 5 2 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3204 : go 5 5 (stepAll 5 4 (stepAll 5 0 (stepAll 5 2 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3210 : go 5 5 (stepAll 5 0 (stepAll 5 1 (stepAll 5 2 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3211 : go 5 5 (stepAll 5 1 (stepAll 5 1 (stepAll 5 2 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3212 : go 5 5 (stepAll 5 2 (stepAll 5 1 (stepAll 5 2 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3213 : go 5 5 (stepAll 5 3 (stepAll 5 1 (stepAll 5 2 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3214 : go 5 5 (stepAll 5 4 (stepAll 5 1 (stepAll 5 2 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3220 : go 5 5 (stepAll 5 0 (stepAll 5 2 (stepAll 5 2 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3221 : go 5 5 (stepAll 5 1 (stepAll 5 2 (stepAll 5 2 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3222 : go 5 5 (stepAll 5 2 (stepAll 5 2 (stepAll 5 2 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3223 : go 5 5 (stepAll 5 3 (stepAll 5 2 (stepAll 5 2 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3224 : go 5 5 (stepAll 5 4 (stepAll 5 2 (stepAll 5 2 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3230 : go 5 5 (stepAll 5 0 (stepAll 5 3 (stepAll 5 2 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3231 : go 5 5 (stepAll 5 1 (stepAll 5 3 (stepAll 5 2 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3232 : go 5 5 (stepAll 5 2 (stepAll 5 3 (stepAll 5 2 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3233 : go 5 5 (stepAll 5 3 (stepAll 5 3 (stepAll 5 2 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3234 : go 5 5 (stepAll 5 4 (stepAll 5 3 (stepAll 5 2 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3240 : go 5 5 (stepAll 5 0 (stepAll 5 4 (stepAll 5 2 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3241 : go 5 5 (stepAll 5 1 (stepAll 5 4 (stepAll 5 2 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3242 : go 5 5 (stepAll 5 2 (stepAll 5 4 (stepAll 5 2 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3243 : go 5 5 (stepAll 5 3 (stepAll 5 4 (stepAll 5 2 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3244 : go 5 5 (stepAll 5 4 (stepAll 5 4 (stepAll 5 2 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3300 : go 5 5 (stepAll 5 0 (stepAll 5 0 (stepAll 5 3 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3301 : go 5 5 (stepAll 5 1 (stepAll 5 0 (stepAll 5 3 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3302 : go 5 5 (stepAll 5 2 (stepAll 5 0 (stepAll 5 3 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3303 : go 5 5 (stepAll 5 3 (stepAll 5 0 (stepAll 5 3 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3304 : go 5 5 (stepAll 5 4 (stepAll 5 0 (stepAll 5 3 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3310 : go 5 5 (stepAll 5 0 (stepAll 5 1 (stepAll 5 3 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3311 : go 5 5 (stepAll 5 1 (stepAll 5 1 (stepAll 5 3 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3312 : go 5 5 (stepAll 5 2 (stepAll 5 1 (stepAll 5 3 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3313 : go 5 5 (stepAll 5 3 (stepAll 5 1 (stepAll 5 3 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

end CoveringKernel
