import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q6566 : go 7 5 (stepAll 7 6 (stepAll 7 6 (stepAll 7 5 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6600 : go 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 6 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6601 : go 7 5 (stepAll 7 1 (stepAll 7 0 (stepAll 7 6 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6602 : go 7 5 (stepAll 7 2 (stepAll 7 0 (stepAll 7 6 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6603 : go 7 5 (stepAll 7 3 (stepAll 7 0 (stepAll 7 6 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6604 : go 7 5 (stepAll 7 4 (stepAll 7 0 (stepAll 7 6 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6605 : go 7 5 (stepAll 7 5 (stepAll 7 0 (stepAll 7 6 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6606 : go 7 5 (stepAll 7 6 (stepAll 7 0 (stepAll 7 6 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6610 : go 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 6 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6611 : go 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 6 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6612 : go 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 6 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6613 : go 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 6 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6614 : go 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 6 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6615 : go 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 6 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6616 : go 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 6 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6620 : go 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 6 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6621 : go 7 5 (stepAll 7 1 (stepAll 7 2 (stepAll 7 6 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6622 : go 7 5 (stepAll 7 2 (stepAll 7 2 (stepAll 7 6 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6623 : go 7 5 (stepAll 7 3 (stepAll 7 2 (stepAll 7 6 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6624 : go 7 5 (stepAll 7 4 (stepAll 7 2 (stepAll 7 6 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6625 : go 7 5 (stepAll 7 5 (stepAll 7 2 (stepAll 7 6 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6626 : go 7 5 (stepAll 7 6 (stepAll 7 2 (stepAll 7 6 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6630 : go 7 5 (stepAll 7 0 (stepAll 7 3 (stepAll 7 6 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6631 : go 7 5 (stepAll 7 1 (stepAll 7 3 (stepAll 7 6 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6632 : go 7 5 (stepAll 7 2 (stepAll 7 3 (stepAll 7 6 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6633 : go 7 5 (stepAll 7 3 (stepAll 7 3 (stepAll 7 6 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
