import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q6325 : go 7 5 (stepAll 7 5 (stepAll 7 2 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6326 : go 7 5 (stepAll 7 6 (stepAll 7 2 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6330 : go 7 5 (stepAll 7 0 (stepAll 7 3 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6331 : go 7 5 (stepAll 7 1 (stepAll 7 3 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6332 : go 7 5 (stepAll 7 2 (stepAll 7 3 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6333 : go 7 5 (stepAll 7 3 (stepAll 7 3 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6334 : go 7 5 (stepAll 7 4 (stepAll 7 3 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6335 : go 7 5 (stepAll 7 5 (stepAll 7 3 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6336 : go 7 5 (stepAll 7 6 (stepAll 7 3 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6340 : go 7 5 (stepAll 7 0 (stepAll 7 4 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6341 : go 7 5 (stepAll 7 1 (stepAll 7 4 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6342 : go 7 5 (stepAll 7 2 (stepAll 7 4 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6343 : go 7 5 (stepAll 7 3 (stepAll 7 4 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6344 : go 7 5 (stepAll 7 4 (stepAll 7 4 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6345 : go 7 5 (stepAll 7 5 (stepAll 7 4 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6346 : go 7 5 (stepAll 7 6 (stepAll 7 4 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6350 : go 7 5 (stepAll 7 0 (stepAll 7 5 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6351 : go 7 5 (stepAll 7 1 (stepAll 7 5 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6352 : go 7 5 (stepAll 7 2 (stepAll 7 5 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6353 : go 7 5 (stepAll 7 3 (stepAll 7 5 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6354 : go 7 5 (stepAll 7 4 (stepAll 7 5 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6355 : go 7 5 (stepAll 7 5 (stepAll 7 5 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6356 : go 7 5 (stepAll 7 6 (stepAll 7 5 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6360 : go 7 5 (stepAll 7 0 (stepAll 7 6 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6361 : go 7 5 (stepAll 7 1 (stepAll 7 6 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
