import CoveringLean.K2_Core
import CoveringLean.C1_Data_K5_10_4

/-!
GENERATED by gen.py (frente 1b, 2026-10-02; copy of ~/h/b/gen/gen.py + Final via cert_of_go) -- kernel tier, `decide +kernel` only.
cell: K5_10_4  q=5 n=10 R=4 M=625; data = `CoveringCerts.Data.K5_10_4` (C1_Data_K5_10_4.lean, sha256 in its header).
leaves: all 5^4 prefixes of length 4; each leaf is `go 5 6 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K5_10_4_q4303 : go 5 6 (stepAll 5 3 (stepAll 5 0 (stepAll 5 3 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4304 : go 5 6 (stepAll 5 4 (stepAll 5 0 (stepAll 5 3 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4310 : go 5 6 (stepAll 5 0 (stepAll 5 1 (stepAll 5 3 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4311 : go 5 6 (stepAll 5 1 (stepAll 5 1 (stepAll 5 3 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4312 : go 5 6 (stepAll 5 2 (stepAll 5 1 (stepAll 5 3 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4313 : go 5 6 (stepAll 5 3 (stepAll 5 1 (stepAll 5 3 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4314 : go 5 6 (stepAll 5 4 (stepAll 5 1 (stepAll 5 3 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4320 : go 5 6 (stepAll 5 0 (stepAll 5 2 (stepAll 5 3 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4321 : go 5 6 (stepAll 5 1 (stepAll 5 2 (stepAll 5 3 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4322 : go 5 6 (stepAll 5 2 (stepAll 5 2 (stepAll 5 3 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4323 : go 5 6 (stepAll 5 3 (stepAll 5 2 (stepAll 5 3 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4324 : go 5 6 (stepAll 5 4 (stepAll 5 2 (stepAll 5 3 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4330 : go 5 6 (stepAll 5 0 (stepAll 5 3 (stepAll 5 3 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4331 : go 5 6 (stepAll 5 1 (stepAll 5 3 (stepAll 5 3 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4332 : go 5 6 (stepAll 5 2 (stepAll 5 3 (stepAll 5 3 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4333 : go 5 6 (stepAll 5 3 (stepAll 5 3 (stepAll 5 3 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4334 : go 5 6 (stepAll 5 4 (stepAll 5 3 (stepAll 5 3 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

end CoveringKernel
