import CoveringLean.K2_Core
import CoveringLean.C1_Data_K5_9_3

/-!
GENERATED by gen.py (frente 1b, 2026-10-02; copy of ~/h/b/gen/gen.py + Final via cert_of_go) -- kernel tier, `decide +kernel` only.
cell: K5_9_3  q=5 n=9 R=3 M=1250; data = `CoveringCerts.Data.K5_9_3` (C1_Data_K5_9_3.lean, sha256 in its header).
leaves: all 5^4 prefixes of length 4; each leaf is `go 5 5 (stepAll ... (wordItems 3 W)) = true`.
-/

namespace CoveringKernel

theorem K5_9_3_q2412 : go 5 5 (stepAll 5 2 (stepAll 5 1 (stepAll 5 4 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2413 : go 5 5 (stepAll 5 3 (stepAll 5 1 (stepAll 5 4 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2414 : go 5 5 (stepAll 5 4 (stepAll 5 1 (stepAll 5 4 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2420 : go 5 5 (stepAll 5 0 (stepAll 5 2 (stepAll 5 4 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2421 : go 5 5 (stepAll 5 1 (stepAll 5 2 (stepAll 5 4 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2422 : go 5 5 (stepAll 5 2 (stepAll 5 2 (stepAll 5 4 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2423 : go 5 5 (stepAll 5 3 (stepAll 5 2 (stepAll 5 4 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2424 : go 5 5 (stepAll 5 4 (stepAll 5 2 (stepAll 5 4 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2430 : go 5 5 (stepAll 5 0 (stepAll 5 3 (stepAll 5 4 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2431 : go 5 5 (stepAll 5 1 (stepAll 5 3 (stepAll 5 4 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2432 : go 5 5 (stepAll 5 2 (stepAll 5 3 (stepAll 5 4 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2433 : go 5 5 (stepAll 5 3 (stepAll 5 3 (stepAll 5 4 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2434 : go 5 5 (stepAll 5 4 (stepAll 5 3 (stepAll 5 4 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2440 : go 5 5 (stepAll 5 0 (stepAll 5 4 (stepAll 5 4 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2441 : go 5 5 (stepAll 5 1 (stepAll 5 4 (stepAll 5 4 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2442 : go 5 5 (stepAll 5 2 (stepAll 5 4 (stepAll 5 4 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2443 : go 5 5 (stepAll 5 3 (stepAll 5 4 (stepAll 5 4 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q2444 : go 5 5 (stepAll 5 4 (stepAll 5 4 (stepAll 5 4 (stepAll 5 2 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3000 : go 5 5 (stepAll 5 0 (stepAll 5 0 (stepAll 5 0 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3001 : go 5 5 (stepAll 5 1 (stepAll 5 0 (stepAll 5 0 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3002 : go 5 5 (stepAll 5 2 (stepAll 5 0 (stepAll 5 0 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3003 : go 5 5 (stepAll 5 3 (stepAll 5 0 (stepAll 5 0 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3004 : go 5 5 (stepAll 5 4 (stepAll 5 0 (stepAll 5 0 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3010 : go 5 5 (stepAll 5 0 (stepAll 5 1 (stepAll 5 0 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3011 : go 5 5 (stepAll 5 1 (stepAll 5 1 (stepAll 5 0 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3012 : go 5 5 (stepAll 5 2 (stepAll 5 1 (stepAll 5 0 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3013 : go 5 5 (stepAll 5 3 (stepAll 5 1 (stepAll 5 0 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3014 : go 5 5 (stepAll 5 4 (stepAll 5 1 (stepAll 5 0 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3020 : go 5 5 (stepAll 5 0 (stepAll 5 2 (stepAll 5 0 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3021 : go 5 5 (stepAll 5 1 (stepAll 5 2 (stepAll 5 0 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3022 : go 5 5 (stepAll 5 2 (stepAll 5 2 (stepAll 5 0 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3023 : go 5 5 (stepAll 5 3 (stepAll 5 2 (stepAll 5 0 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3024 : go 5 5 (stepAll 5 4 (stepAll 5 2 (stepAll 5 0 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3030 : go 5 5 (stepAll 5 0 (stepAll 5 3 (stepAll 5 0 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3031 : go 5 5 (stepAll 5 1 (stepAll 5 3 (stepAll 5 0 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3032 : go 5 5 (stepAll 5 2 (stepAll 5 3 (stepAll 5 0 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3033 : go 5 5 (stepAll 5 3 (stepAll 5 3 (stepAll 5 0 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3034 : go 5 5 (stepAll 5 4 (stepAll 5 3 (stepAll 5 0 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3040 : go 5 5 (stepAll 5 0 (stepAll 5 4 (stepAll 5 0 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3041 : go 5 5 (stepAll 5 1 (stepAll 5 4 (stepAll 5 0 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3042 : go 5 5 (stepAll 5 2 (stepAll 5 4 (stepAll 5 0 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3043 : go 5 5 (stepAll 5 3 (stepAll 5 4 (stepAll 5 0 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3044 : go 5 5 (stepAll 5 4 (stepAll 5 4 (stepAll 5 0 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3100 : go 5 5 (stepAll 5 0 (stepAll 5 0 (stepAll 5 1 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3101 : go 5 5 (stepAll 5 1 (stepAll 5 0 (stepAll 5 1 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3102 : go 5 5 (stepAll 5 2 (stepAll 5 0 (stepAll 5 1 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3103 : go 5 5 (stepAll 5 3 (stepAll 5 0 (stepAll 5 1 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3104 : go 5 5 (stepAll 5 4 (stepAll 5 0 (stepAll 5 1 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3110 : go 5 5 (stepAll 5 0 (stepAll 5 1 (stepAll 5 1 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3111 : go 5 5 (stepAll 5 1 (stepAll 5 1 (stepAll 5 1 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q3112 : go 5 5 (stepAll 5 2 (stepAll 5 1 (stepAll 5 1 (stepAll 5 3 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

end CoveringKernel
