import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q1526 : go 7 5 (stepAll 7 6 (stepAll 7 2 (stepAll 7 5 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1530 : go 7 5 (stepAll 7 0 (stepAll 7 3 (stepAll 7 5 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1531 : go 7 5 (stepAll 7 1 (stepAll 7 3 (stepAll 7 5 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1532 : go 7 5 (stepAll 7 2 (stepAll 7 3 (stepAll 7 5 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1533 : go 7 5 (stepAll 7 3 (stepAll 7 3 (stepAll 7 5 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1534 : go 7 5 (stepAll 7 4 (stepAll 7 3 (stepAll 7 5 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1535 : go 7 5 (stepAll 7 5 (stepAll 7 3 (stepAll 7 5 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1536 : go 7 5 (stepAll 7 6 (stepAll 7 3 (stepAll 7 5 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1540 : go 7 5 (stepAll 7 0 (stepAll 7 4 (stepAll 7 5 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1541 : go 7 5 (stepAll 7 1 (stepAll 7 4 (stepAll 7 5 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1542 : go 7 5 (stepAll 7 2 (stepAll 7 4 (stepAll 7 5 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1543 : go 7 5 (stepAll 7 3 (stepAll 7 4 (stepAll 7 5 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1544 : go 7 5 (stepAll 7 4 (stepAll 7 4 (stepAll 7 5 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1545 : go 7 5 (stepAll 7 5 (stepAll 7 4 (stepAll 7 5 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1546 : go 7 5 (stepAll 7 6 (stepAll 7 4 (stepAll 7 5 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1550 : go 7 5 (stepAll 7 0 (stepAll 7 5 (stepAll 7 5 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1551 : go 7 5 (stepAll 7 1 (stepAll 7 5 (stepAll 7 5 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1552 : go 7 5 (stepAll 7 2 (stepAll 7 5 (stepAll 7 5 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1553 : go 7 5 (stepAll 7 3 (stepAll 7 5 (stepAll 7 5 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1554 : go 7 5 (stepAll 7 4 (stepAll 7 5 (stepAll 7 5 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1555 : go 7 5 (stepAll 7 5 (stepAll 7 5 (stepAll 7 5 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1556 : go 7 5 (stepAll 7 6 (stepAll 7 5 (stepAll 7 5 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1560 : go 7 5 (stepAll 7 0 (stepAll 7 6 (stepAll 7 5 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1561 : go 7 5 (stepAll 7 1 (stepAll 7 6 (stepAll 7 5 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1562 : go 7 5 (stepAll 7 2 (stepAll 7 6 (stepAll 7 5 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
