import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_8_3

/-!
GENERATED by gen.py (frente 1a, 2026-10-02) -- kernel tier, `decide +kernel` only.
cell: K7_8_3  q=7 n=8 R=3 M=1893; data = `CoveringCerts.Data.K7_8_3` (C1_Data_K7_8_3.lean, sha256 in its header).
leaves: all 7^3 prefixes of length 3; each leaf is `go 7 5 (stepAll ... (wordItems 3 W)) = true`.
-/

namespace CoveringKernel

theorem K7_8_3_q620 : go 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q621 : go 7 5 (stepAll 7 1 (stepAll 7 2 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q622 : go 7 5 (stepAll 7 2 (stepAll 7 2 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q623 : go 7 5 (stepAll 7 3 (stepAll 7 2 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q624 : go 7 5 (stepAll 7 4 (stepAll 7 2 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q625 : go 7 5 (stepAll 7 5 (stepAll 7 2 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q626 : go 7 5 (stepAll 7 6 (stepAll 7 2 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q630 : go 7 5 (stepAll 7 0 (stepAll 7 3 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q631 : go 7 5 (stepAll 7 1 (stepAll 7 3 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q632 : go 7 5 (stepAll 7 2 (stepAll 7 3 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q633 : go 7 5 (stepAll 7 3 (stepAll 7 3 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q634 : go 7 5 (stepAll 7 4 (stepAll 7 3 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q635 : go 7 5 (stepAll 7 5 (stepAll 7 3 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q636 : go 7 5 (stepAll 7 6 (stepAll 7 3 (stepAll 7 6 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

end CoveringKernel
