import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_8_3

/-!
GENERATED by gen.py (frente 1a, 2026-10-02) -- kernel tier, `decide +kernel` only.
cell: K7_8_3  q=7 n=8 R=3 M=1893; data = `CoveringCerts.Data.K7_8_3` (C1_Data_K7_8_3.lean, sha256 in its header).
leaves: all 7^3 prefixes of length 3; each leaf is `go 7 5 (stepAll ... (wordItems 3 W)) = true`.
-/

namespace CoveringKernel

theorem K7_8_3_q150 : go 7 5 (stepAll 7 0 (stepAll 7 5 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q151 : go 7 5 (stepAll 7 1 (stepAll 7 5 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q152 : go 7 5 (stepAll 7 2 (stepAll 7 5 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q153 : go 7 5 (stepAll 7 3 (stepAll 7 5 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q154 : go 7 5 (stepAll 7 4 (stepAll 7 5 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q155 : go 7 5 (stepAll 7 5 (stepAll 7 5 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q156 : go 7 5 (stepAll 7 6 (stepAll 7 5 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q160 : go 7 5 (stepAll 7 0 (stepAll 7 6 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q161 : go 7 5 (stepAll 7 1 (stepAll 7 6 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q162 : go 7 5 (stepAll 7 2 (stepAll 7 6 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q163 : go 7 5 (stepAll 7 3 (stepAll 7 6 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q164 : go 7 5 (stepAll 7 4 (stepAll 7 6 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q165 : go 7 5 (stepAll 7 5 (stepAll 7 6 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

theorem K7_8_3_q166 : go 7 5 (stepAll 7 6 (stepAll 7 6 (stepAll 7 1 (wordItems 3 CoveringCerts.Data.K7_8_3)))) = true := by decide +kernel

end CoveringKernel
