import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q3112 : go 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3113 : go 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3114 : go 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3115 : go 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3116 : go 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3120 : go 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3121 : go 7 5 (stepAll 7 1 (stepAll 7 2 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3122 : go 7 5 (stepAll 7 2 (stepAll 7 2 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3123 : go 7 5 (stepAll 7 3 (stepAll 7 2 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3124 : go 7 5 (stepAll 7 4 (stepAll 7 2 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3125 : go 7 5 (stepAll 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3126 : go 7 5 (stepAll 7 6 (stepAll 7 2 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3130 : go 7 5 (stepAll 7 0 (stepAll 7 3 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3131 : go 7 5 (stepAll 7 1 (stepAll 7 3 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3132 : go 7 5 (stepAll 7 2 (stepAll 7 3 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3133 : go 7 5 (stepAll 7 3 (stepAll 7 3 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3134 : go 7 5 (stepAll 7 4 (stepAll 7 3 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3135 : go 7 5 (stepAll 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3136 : go 7 5 (stepAll 7 6 (stepAll 7 3 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3140 : go 7 5 (stepAll 7 0 (stepAll 7 4 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3141 : go 7 5 (stepAll 7 1 (stepAll 7 4 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3142 : go 7 5 (stepAll 7 2 (stepAll 7 4 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3143 : go 7 5 (stepAll 7 3 (stepAll 7 4 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3144 : go 7 5 (stepAll 7 4 (stepAll 7 4 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3145 : go 7 5 (stepAll 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3146 : go 7 5 (stepAll 7 6 (stepAll 7 4 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
