import CoveringLean.K2_Core
import CoveringLean.C1_Data_K5_10_4

/-!
GENERATED by gen.py (frente 1b, 2026-10-02; copy of ~/h/b/gen/gen.py + Final via cert_of_go) -- kernel tier, `decide +kernel` only.
cell: K5_10_4  q=5 n=10 R=4 M=625; data = `CoveringCerts.Data.K5_10_4` (C1_Data_K5_10_4.lean, sha256 in its header).
leaves: all 5^4 prefixes of length 4; each leaf is `go 5 6 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K5_10_4_q1021 : go 5 6 (stepAll 5 1 (stepAll 5 2 (stepAll 5 0 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1022 : go 5 6 (stepAll 5 2 (stepAll 5 2 (stepAll 5 0 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1023 : go 5 6 (stepAll 5 3 (stepAll 5 2 (stepAll 5 0 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1024 : go 5 6 (stepAll 5 4 (stepAll 5 2 (stepAll 5 0 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1030 : go 5 6 (stepAll 5 0 (stepAll 5 3 (stepAll 5 0 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1031 : go 5 6 (stepAll 5 1 (stepAll 5 3 (stepAll 5 0 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1032 : go 5 6 (stepAll 5 2 (stepAll 5 3 (stepAll 5 0 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1033 : go 5 6 (stepAll 5 3 (stepAll 5 3 (stepAll 5 0 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1034 : go 5 6 (stepAll 5 4 (stepAll 5 3 (stepAll 5 0 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1040 : go 5 6 (stepAll 5 0 (stepAll 5 4 (stepAll 5 0 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1041 : go 5 6 (stepAll 5 1 (stepAll 5 4 (stepAll 5 0 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1042 : go 5 6 (stepAll 5 2 (stepAll 5 4 (stepAll 5 0 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1043 : go 5 6 (stepAll 5 3 (stepAll 5 4 (stepAll 5 0 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1044 : go 5 6 (stepAll 5 4 (stepAll 5 4 (stepAll 5 0 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1100 : go 5 6 (stepAll 5 0 (stepAll 5 0 (stepAll 5 1 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1101 : go 5 6 (stepAll 5 1 (stepAll 5 0 (stepAll 5 1 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1102 : go 5 6 (stepAll 5 2 (stepAll 5 0 (stepAll 5 1 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

end CoveringKernel
