import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q2100 : go 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2101 : go 7 5 (stepAll 7 1 (stepAll 7 0 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2102 : go 7 5 (stepAll 7 2 (stepAll 7 0 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2103 : go 7 5 (stepAll 7 3 (stepAll 7 0 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2104 : go 7 5 (stepAll 7 4 (stepAll 7 0 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2105 : go 7 5 (stepAll 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2106 : go 7 5 (stepAll 7 6 (stepAll 7 0 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2110 : go 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2111 : go 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2112 : go 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2113 : go 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2114 : go 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2115 : go 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2116 : go 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2120 : go 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2121 : go 7 5 (stepAll 7 1 (stepAll 7 2 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2122 : go 7 5 (stepAll 7 2 (stepAll 7 2 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2123 : go 7 5 (stepAll 7 3 (stepAll 7 2 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2124 : go 7 5 (stepAll 7 4 (stepAll 7 2 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2125 : go 7 5 (stepAll 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2126 : go 7 5 (stepAll 7 6 (stepAll 7 2 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2130 : go 7 5 (stepAll 7 0 (stepAll 7 3 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2131 : go 7 5 (stepAll 7 1 (stepAll 7 3 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2132 : go 7 5 (stepAll 7 2 (stepAll 7 3 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2133 : go 7 5 (stepAll 7 3 (stepAll 7 3 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2134 : go 7 5 (stepAll 7 4 (stepAll 7 3 (stepAll 7 1 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
