import CoveringLean.K2_Core
import CoveringLean.C1_Data_K5_9_4

/-!
GENERATED by gen.py (frente 1b, 2026-10-02; copy of ~/h/b/gen/gen.py + Final via cert_of_go) -- kernel tier, `decide +kernel` only.
cell: K5_9_4  q=5 n=9 R=4 M=250; data = `CoveringCerts.Data.K5_9_4` (C1_Data_K5_9_4.lean, sha256 in its header).
leaves: all 5^3 prefixes of length 3; each leaf is `go 5 6 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K5_9_4_q102 : go 5 6 (stepAll 5 2 (stepAll 5 0 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q103 : go 5 6 (stepAll 5 3 (stepAll 5 0 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q104 : go 5 6 (stepAll 5 4 (stepAll 5 0 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q110 : go 5 6 (stepAll 5 0 (stepAll 5 1 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q111 : go 5 6 (stepAll 5 1 (stepAll 5 1 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q112 : go 5 6 (stepAll 5 2 (stepAll 5 1 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q113 : go 5 6 (stepAll 5 3 (stepAll 5 1 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q114 : go 5 6 (stepAll 5 4 (stepAll 5 1 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q120 : go 5 6 (stepAll 5 0 (stepAll 5 2 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q121 : go 5 6 (stepAll 5 1 (stepAll 5 2 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q122 : go 5 6 (stepAll 5 2 (stepAll 5 2 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q123 : go 5 6 (stepAll 5 3 (stepAll 5 2 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q124 : go 5 6 (stepAll 5 4 (stepAll 5 2 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q130 : go 5 6 (stepAll 5 0 (stepAll 5 3 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q131 : go 5 6 (stepAll 5 1 (stepAll 5 3 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q132 : go 5 6 (stepAll 5 2 (stepAll 5 3 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q133 : go 5 6 (stepAll 5 3 (stepAll 5 3 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q134 : go 5 6 (stepAll 5 4 (stepAll 5 3 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q140 : go 5 6 (stepAll 5 0 (stepAll 5 4 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q141 : go 5 6 (stepAll 5 1 (stepAll 5 4 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q142 : go 5 6 (stepAll 5 2 (stepAll 5 4 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q143 : go 5 6 (stepAll 5 3 (stepAll 5 4 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q144 : go 5 6 (stepAll 5 4 (stepAll 5 4 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q200 : go 5 6 (stepAll 5 0 (stepAll 5 0 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q201 : go 5 6 (stepAll 5 1 (stepAll 5 0 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q202 : go 5 6 (stepAll 5 2 (stepAll 5 0 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q203 : go 5 6 (stepAll 5 3 (stepAll 5 0 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

end CoveringKernel
