import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q4536 : go 7 5 (stepAll 7 6 (stepAll 7 3 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4540 : go 7 5 (stepAll 7 0 (stepAll 7 4 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4541 : go 7 5 (stepAll 7 1 (stepAll 7 4 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4542 : go 7 5 (stepAll 7 2 (stepAll 7 4 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4543 : go 7 5 (stepAll 7 3 (stepAll 7 4 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4544 : go 7 5 (stepAll 7 4 (stepAll 7 4 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4545 : go 7 5 (stepAll 7 5 (stepAll 7 4 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4546 : go 7 5 (stepAll 7 6 (stepAll 7 4 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4550 : go 7 5 (stepAll 7 0 (stepAll 7 5 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4551 : go 7 5 (stepAll 7 1 (stepAll 7 5 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4552 : go 7 5 (stepAll 7 2 (stepAll 7 5 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4553 : go 7 5 (stepAll 7 3 (stepAll 7 5 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4554 : go 7 5 (stepAll 7 4 (stepAll 7 5 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4555 : go 7 5 (stepAll 7 5 (stepAll 7 5 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4556 : go 7 5 (stepAll 7 6 (stepAll 7 5 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4560 : go 7 5 (stepAll 7 0 (stepAll 7 6 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4561 : go 7 5 (stepAll 7 1 (stepAll 7 6 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4562 : go 7 5 (stepAll 7 2 (stepAll 7 6 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4563 : go 7 5 (stepAll 7 3 (stepAll 7 6 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4564 : go 7 5 (stepAll 7 4 (stepAll 7 6 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4565 : go 7 5 (stepAll 7 5 (stepAll 7 6 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4566 : go 7 5 (stepAll 7 6 (stepAll 7 6 (stepAll 7 5 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4600 : go 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 6 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4601 : go 7 5 (stepAll 7 1 (stepAll 7 0 (stepAll 7 6 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4602 : go 7 5 (stepAll 7 2 (stepAll 7 0 (stepAll 7 6 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4603 : go 7 5 (stepAll 7 3 (stepAll 7 0 (stepAll 7 6 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
