import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q0511 : go 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0512 : go 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0513 : go 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0514 : go 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0515 : go 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0516 : go 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0520 : go 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0521 : go 7 5 (stepAll 7 1 (stepAll 7 2 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0522 : go 7 5 (stepAll 7 2 (stepAll 7 2 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0523 : go 7 5 (stepAll 7 3 (stepAll 7 2 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0524 : go 7 5 (stepAll 7 4 (stepAll 7 2 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0525 : go 7 5 (stepAll 7 5 (stepAll 7 2 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0526 : go 7 5 (stepAll 7 6 (stepAll 7 2 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0530 : go 7 5 (stepAll 7 0 (stepAll 7 3 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0531 : go 7 5 (stepAll 7 1 (stepAll 7 3 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0532 : go 7 5 (stepAll 7 2 (stepAll 7 3 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0533 : go 7 5 (stepAll 7 3 (stepAll 7 3 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0534 : go 7 5 (stepAll 7 4 (stepAll 7 3 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0535 : go 7 5 (stepAll 7 5 (stepAll 7 3 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0536 : go 7 5 (stepAll 7 6 (stepAll 7 3 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0540 : go 7 5 (stepAll 7 0 (stepAll 7 4 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0541 : go 7 5 (stepAll 7 1 (stepAll 7 4 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0542 : go 7 5 (stepAll 7 2 (stepAll 7 4 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0543 : go 7 5 (stepAll 7 3 (stepAll 7 4 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0544 : go 7 5 (stepAll 7 4 (stepAll 7 4 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0545 : go 7 5 (stepAll 7 5 (stepAll 7 4 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
