import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q0444 : go 7 5 (stepAll 7 4 (stepAll 7 4 (stepAll 7 4 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0445 : go 7 5 (stepAll 7 5 (stepAll 7 4 (stepAll 7 4 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0446 : go 7 5 (stepAll 7 6 (stepAll 7 4 (stepAll 7 4 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0450 : go 7 5 (stepAll 7 0 (stepAll 7 5 (stepAll 7 4 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0451 : go 7 5 (stepAll 7 1 (stepAll 7 5 (stepAll 7 4 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0452 : go 7 5 (stepAll 7 2 (stepAll 7 5 (stepAll 7 4 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0453 : go 7 5 (stepAll 7 3 (stepAll 7 5 (stepAll 7 4 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0454 : go 7 5 (stepAll 7 4 (stepAll 7 5 (stepAll 7 4 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0455 : go 7 5 (stepAll 7 5 (stepAll 7 5 (stepAll 7 4 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0456 : go 7 5 (stepAll 7 6 (stepAll 7 5 (stepAll 7 4 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0460 : go 7 5 (stepAll 7 0 (stepAll 7 6 (stepAll 7 4 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0461 : go 7 5 (stepAll 7 1 (stepAll 7 6 (stepAll 7 4 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0462 : go 7 5 (stepAll 7 2 (stepAll 7 6 (stepAll 7 4 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0463 : go 7 5 (stepAll 7 3 (stepAll 7 6 (stepAll 7 4 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0464 : go 7 5 (stepAll 7 4 (stepAll 7 6 (stepAll 7 4 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0465 : go 7 5 (stepAll 7 5 (stepAll 7 6 (stepAll 7 4 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0466 : go 7 5 (stepAll 7 6 (stepAll 7 6 (stepAll 7 4 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0500 : go 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0501 : go 7 5 (stepAll 7 1 (stepAll 7 0 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0502 : go 7 5 (stepAll 7 2 (stepAll 7 0 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0503 : go 7 5 (stepAll 7 3 (stepAll 7 0 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0504 : go 7 5 (stepAll 7 4 (stepAll 7 0 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0505 : go 7 5 (stepAll 7 5 (stepAll 7 0 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0506 : go 7 5 (stepAll 7 6 (stepAll 7 0 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0510 : go 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 5 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
