import CoveringLean.K2_Core
import CoveringLean.C1_Data_K5_9_4

/-!
GENERATED by gen.py (frente 1b, 2026-10-02; copy of ~/h/b/gen/gen.py + Final via cert_of_go) -- kernel tier, `decide +kernel` only.
cell: K5_9_4  q=5 n=9 R=4 M=250; data = `CoveringCerts.Data.K5_9_4` (C1_Data_K5_9_4.lean, sha256 in its header).
leaves: all 5^3 prefixes of length 3; each leaf is `go 5 6 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K5_9_4_q412 : go 5 6 (stepAll 5 2 (stepAll 5 1 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q413 : go 5 6 (stepAll 5 3 (stepAll 5 1 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q414 : go 5 6 (stepAll 5 4 (stepAll 5 1 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q420 : go 5 6 (stepAll 5 0 (stepAll 5 2 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q421 : go 5 6 (stepAll 5 1 (stepAll 5 2 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q422 : go 5 6 (stepAll 5 2 (stepAll 5 2 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q423 : go 5 6 (stepAll 5 3 (stepAll 5 2 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q424 : go 5 6 (stepAll 5 4 (stepAll 5 2 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q430 : go 5 6 (stepAll 5 0 (stepAll 5 3 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q431 : go 5 6 (stepAll 5 1 (stepAll 5 3 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q432 : go 5 6 (stepAll 5 2 (stepAll 5 3 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q433 : go 5 6 (stepAll 5 3 (stepAll 5 3 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q434 : go 5 6 (stepAll 5 4 (stepAll 5 3 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q440 : go 5 6 (stepAll 5 0 (stepAll 5 4 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q441 : go 5 6 (stepAll 5 1 (stepAll 5 4 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q442 : go 5 6 (stepAll 5 2 (stepAll 5 4 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q443 : go 5 6 (stepAll 5 3 (stepAll 5 4 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

theorem K5_9_4_q444 : go 5 6 (stepAll 5 4 (stepAll 5 4 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_9_4)))) = true := by decide +kernel

end CoveringKernel
