import CoveringLean.K2_Core
import CoveringLean.C1_Data_K5_10_4

/-!
GENERATED by gen.py (frente 1b, 2026-10-02; copy of ~/h/b/gen/gen.py + Final via cert_of_go) -- kernel tier, `decide +kernel` only.
cell: K5_10_4  q=5 n=10 R=4 M=625; data = `CoveringCerts.Data.K5_10_4` (C1_Data_K5_10_4.lean, sha256 in its header).
leaves: all 5^4 prefixes of length 4; each leaf is `go 5 6 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K5_10_4_q3031 : go 5 6 (stepAll 5 1 (stepAll 5 3 (stepAll 5 0 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3032 : go 5 6 (stepAll 5 2 (stepAll 5 3 (stepAll 5 0 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3033 : go 5 6 (stepAll 5 3 (stepAll 5 3 (stepAll 5 0 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3034 : go 5 6 (stepAll 5 4 (stepAll 5 3 (stepAll 5 0 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3040 : go 5 6 (stepAll 5 0 (stepAll 5 4 (stepAll 5 0 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3041 : go 5 6 (stepAll 5 1 (stepAll 5 4 (stepAll 5 0 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3042 : go 5 6 (stepAll 5 2 (stepAll 5 4 (stepAll 5 0 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3043 : go 5 6 (stepAll 5 3 (stepAll 5 4 (stepAll 5 0 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3044 : go 5 6 (stepAll 5 4 (stepAll 5 4 (stepAll 5 0 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3100 : go 5 6 (stepAll 5 0 (stepAll 5 0 (stepAll 5 1 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3101 : go 5 6 (stepAll 5 1 (stepAll 5 0 (stepAll 5 1 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3102 : go 5 6 (stepAll 5 2 (stepAll 5 0 (stepAll 5 1 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3103 : go 5 6 (stepAll 5 3 (stepAll 5 0 (stepAll 5 1 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3104 : go 5 6 (stepAll 5 4 (stepAll 5 0 (stepAll 5 1 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3110 : go 5 6 (stepAll 5 0 (stepAll 5 1 (stepAll 5 1 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3111 : go 5 6 (stepAll 5 1 (stepAll 5 1 (stepAll 5 1 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q3112 : go 5 6 (stepAll 5 2 (stepAll 5 1 (stepAll 5 1 (stepAll 5 3 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

end CoveringKernel
