import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q4604 : go 7 5 (stepAll 7 4 (stepAll 7 0 (stepAll 7 6 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4605 : go 7 5 (stepAll 7 5 (stepAll 7 0 (stepAll 7 6 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4606 : go 7 5 (stepAll 7 6 (stepAll 7 0 (stepAll 7 6 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4610 : go 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 6 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4611 : go 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 6 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4612 : go 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 6 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4613 : go 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 6 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4614 : go 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 6 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4615 : go 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 6 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4616 : go 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 6 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4620 : go 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 6 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4621 : go 7 5 (stepAll 7 1 (stepAll 7 2 (stepAll 7 6 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4622 : go 7 5 (stepAll 7 2 (stepAll 7 2 (stepAll 7 6 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4623 : go 7 5 (stepAll 7 3 (stepAll 7 2 (stepAll 7 6 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4624 : go 7 5 (stepAll 7 4 (stepAll 7 2 (stepAll 7 6 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4625 : go 7 5 (stepAll 7 5 (stepAll 7 2 (stepAll 7 6 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4626 : go 7 5 (stepAll 7 6 (stepAll 7 2 (stepAll 7 6 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4630 : go 7 5 (stepAll 7 0 (stepAll 7 3 (stepAll 7 6 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4631 : go 7 5 (stepAll 7 1 (stepAll 7 3 (stepAll 7 6 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4632 : go 7 5 (stepAll 7 2 (stepAll 7 3 (stepAll 7 6 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4633 : go 7 5 (stepAll 7 3 (stepAll 7 3 (stepAll 7 6 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4634 : go 7 5 (stepAll 7 4 (stepAll 7 3 (stepAll 7 6 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4635 : go 7 5 (stepAll 7 5 (stepAll 7 3 (stepAll 7 6 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4636 : go 7 5 (stepAll 7 6 (stepAll 7 3 (stepAll 7 6 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
