import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q3622 : go 7 5 (stepAll 7 2 (stepAll 7 2 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3623 : go 7 5 (stepAll 7 3 (stepAll 7 2 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3624 : go 7 5 (stepAll 7 4 (stepAll 7 2 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3625 : go 7 5 (stepAll 7 5 (stepAll 7 2 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3626 : go 7 5 (stepAll 7 6 (stepAll 7 2 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3630 : go 7 5 (stepAll 7 0 (stepAll 7 3 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3631 : go 7 5 (stepAll 7 1 (stepAll 7 3 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3632 : go 7 5 (stepAll 7 2 (stepAll 7 3 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3633 : go 7 5 (stepAll 7 3 (stepAll 7 3 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3634 : go 7 5 (stepAll 7 4 (stepAll 7 3 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3635 : go 7 5 (stepAll 7 5 (stepAll 7 3 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3636 : go 7 5 (stepAll 7 6 (stepAll 7 3 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3640 : go 7 5 (stepAll 7 0 (stepAll 7 4 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3641 : go 7 5 (stepAll 7 1 (stepAll 7 4 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3642 : go 7 5 (stepAll 7 2 (stepAll 7 4 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3643 : go 7 5 (stepAll 7 3 (stepAll 7 4 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3644 : go 7 5 (stepAll 7 4 (stepAll 7 4 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3645 : go 7 5 (stepAll 7 5 (stepAll 7 4 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3646 : go 7 5 (stepAll 7 6 (stepAll 7 4 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3650 : go 7 5 (stepAll 7 0 (stepAll 7 5 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3651 : go 7 5 (stepAll 7 1 (stepAll 7 5 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3652 : go 7 5 (stepAll 7 2 (stepAll 7 5 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3653 : go 7 5 (stepAll 7 3 (stepAll 7 5 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3654 : go 7 5 (stepAll 7 4 (stepAll 7 5 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3655 : go 7 5 (stepAll 7 5 (stepAll 7 5 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3656 : go 7 5 (stepAll 7 6 (stepAll 7 5 (stepAll 7 6 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
