import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q6260 : go 7 5 (stepAll 7 0 (stepAll 7 6 (stepAll 7 2 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6261 : go 7 5 (stepAll 7 1 (stepAll 7 6 (stepAll 7 2 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6262 : go 7 5 (stepAll 7 2 (stepAll 7 6 (stepAll 7 2 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6263 : go 7 5 (stepAll 7 3 (stepAll 7 6 (stepAll 7 2 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6264 : go 7 5 (stepAll 7 4 (stepAll 7 6 (stepAll 7 2 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6265 : go 7 5 (stepAll 7 5 (stepAll 7 6 (stepAll 7 2 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6266 : go 7 5 (stepAll 7 6 (stepAll 7 6 (stepAll 7 2 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6300 : go 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6301 : go 7 5 (stepAll 7 1 (stepAll 7 0 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6302 : go 7 5 (stepAll 7 2 (stepAll 7 0 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6303 : go 7 5 (stepAll 7 3 (stepAll 7 0 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6304 : go 7 5 (stepAll 7 4 (stepAll 7 0 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6305 : go 7 5 (stepAll 7 5 (stepAll 7 0 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6306 : go 7 5 (stepAll 7 6 (stepAll 7 0 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6310 : go 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6311 : go 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6312 : go 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6313 : go 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6314 : go 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6315 : go 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6316 : go 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6320 : go 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6321 : go 7 5 (stepAll 7 1 (stepAll 7 2 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6322 : go 7 5 (stepAll 7 2 (stepAll 7 2 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6323 : go 7 5 (stepAll 7 3 (stepAll 7 2 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6324 : go 7 5 (stepAll 7 4 (stepAll 7 2 (stepAll 7 3 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
