import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q0000 : go 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 0 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0001 : go 7 5 (stepAll 7 1 (stepAll 7 0 (stepAll 7 0 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0002 : go 7 5 (stepAll 7 2 (stepAll 7 0 (stepAll 7 0 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0003 : go 7 5 (stepAll 7 3 (stepAll 7 0 (stepAll 7 0 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0004 : go 7 5 (stepAll 7 4 (stepAll 7 0 (stepAll 7 0 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0005 : go 7 5 (stepAll 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0006 : go 7 5 (stepAll 7 6 (stepAll 7 0 (stepAll 7 0 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0010 : go 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 0 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0011 : go 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 0 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0012 : go 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 0 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0013 : go 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 0 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0014 : go 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 0 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0015 : go 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 0 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0016 : go 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 0 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0020 : go 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 0 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0021 : go 7 5 (stepAll 7 1 (stepAll 7 2 (stepAll 7 0 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0022 : go 7 5 (stepAll 7 2 (stepAll 7 2 (stepAll 7 0 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0023 : go 7 5 (stepAll 7 3 (stepAll 7 2 (stepAll 7 0 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0024 : go 7 5 (stepAll 7 4 (stepAll 7 2 (stepAll 7 0 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0025 : go 7 5 (stepAll 7 5 (stepAll 7 2 (stepAll 7 0 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0026 : go 7 5 (stepAll 7 6 (stepAll 7 2 (stepAll 7 0 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0030 : go 7 5 (stepAll 7 0 (stepAll 7 3 (stepAll 7 0 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0031 : go 7 5 (stepAll 7 1 (stepAll 7 3 (stepAll 7 0 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0032 : go 7 5 (stepAll 7 2 (stepAll 7 3 (stepAll 7 0 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0033 : go 7 5 (stepAll 7 3 (stepAll 7 3 (stepAll 7 0 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0034 : go 7 5 (stepAll 7 4 (stepAll 7 3 (stepAll 7 0 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0035 : go 7 5 (stepAll 7 5 (stepAll 7 3 (stepAll 7 0 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
