import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q0140 : go 7 5 (stepAll 7 0 (stepAll 7 4 (stepAll 7 1 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0141 : go 7 5 (stepAll 7 1 (stepAll 7 4 (stepAll 7 1 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0142 : go 7 5 (stepAll 7 2 (stepAll 7 4 (stepAll 7 1 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0143 : go 7 5 (stepAll 7 3 (stepAll 7 4 (stepAll 7 1 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0144 : go 7 5 (stepAll 7 4 (stepAll 7 4 (stepAll 7 1 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0145 : go 7 5 (stepAll 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0146 : go 7 5 (stepAll 7 6 (stepAll 7 4 (stepAll 7 1 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0150 : go 7 5 (stepAll 7 0 (stepAll 7 5 (stepAll 7 1 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0151 : go 7 5 (stepAll 7 1 (stepAll 7 5 (stepAll 7 1 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0152 : go 7 5 (stepAll 7 2 (stepAll 7 5 (stepAll 7 1 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0153 : go 7 5 (stepAll 7 3 (stepAll 7 5 (stepAll 7 1 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0154 : go 7 5 (stepAll 7 4 (stepAll 7 5 (stepAll 7 1 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0155 : go 7 5 (stepAll 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0156 : go 7 5 (stepAll 7 6 (stepAll 7 5 (stepAll 7 1 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0160 : go 7 5 (stepAll 7 0 (stepAll 7 6 (stepAll 7 1 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0161 : go 7 5 (stepAll 7 1 (stepAll 7 6 (stepAll 7 1 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0162 : go 7 5 (stepAll 7 2 (stepAll 7 6 (stepAll 7 1 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0163 : go 7 5 (stepAll 7 3 (stepAll 7 6 (stepAll 7 1 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0164 : go 7 5 (stepAll 7 4 (stepAll 7 6 (stepAll 7 1 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0165 : go 7 5 (stepAll 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0166 : go 7 5 (stepAll 7 6 (stepAll 7 6 (stepAll 7 1 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0200 : go 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 2 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0201 : go 7 5 (stepAll 7 1 (stepAll 7 0 (stepAll 7 2 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0202 : go 7 5 (stepAll 7 2 (stepAll 7 0 (stepAll 7 2 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
