import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q6122 : go 7 5 (stepAll 7 2 (stepAll 7 2 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6123 : go 7 5 (stepAll 7 3 (stepAll 7 2 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6124 : go 7 5 (stepAll 7 4 (stepAll 7 2 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6125 : go 7 5 (stepAll 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6126 : go 7 5 (stepAll 7 6 (stepAll 7 2 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6130 : go 7 5 (stepAll 7 0 (stepAll 7 3 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6131 : go 7 5 (stepAll 7 1 (stepAll 7 3 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6132 : go 7 5 (stepAll 7 2 (stepAll 7 3 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6133 : go 7 5 (stepAll 7 3 (stepAll 7 3 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6134 : go 7 5 (stepAll 7 4 (stepAll 7 3 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6135 : go 7 5 (stepAll 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6136 : go 7 5 (stepAll 7 6 (stepAll 7 3 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6140 : go 7 5 (stepAll 7 0 (stepAll 7 4 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6141 : go 7 5 (stepAll 7 1 (stepAll 7 4 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6142 : go 7 5 (stepAll 7 2 (stepAll 7 4 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6143 : go 7 5 (stepAll 7 3 (stepAll 7 4 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6144 : go 7 5 (stepAll 7 4 (stepAll 7 4 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6145 : go 7 5 (stepAll 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6146 : go 7 5 (stepAll 7 6 (stepAll 7 4 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6150 : go 7 5 (stepAll 7 0 (stepAll 7 5 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6151 : go 7 5 (stepAll 7 1 (stepAll 7 5 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6152 : go 7 5 (stepAll 7 2 (stepAll 7 5 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6153 : go 7 5 (stepAll 7 3 (stepAll 7 5 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6154 : go 7 5 (stepAll 7 4 (stepAll 7 5 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
