import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q0342 : go 7 5 (stepAll 7 2 (stepAll 7 4 (stepAll 7 3 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0343 : go 7 5 (stepAll 7 3 (stepAll 7 4 (stepAll 7 3 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0344 : go 7 5 (stepAll 7 4 (stepAll 7 4 (stepAll 7 3 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0345 : go 7 5 (stepAll 7 5 (stepAll 7 4 (stepAll 7 3 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0346 : go 7 5 (stepAll 7 6 (stepAll 7 4 (stepAll 7 3 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0350 : go 7 5 (stepAll 7 0 (stepAll 7 5 (stepAll 7 3 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0351 : go 7 5 (stepAll 7 1 (stepAll 7 5 (stepAll 7 3 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0352 : go 7 5 (stepAll 7 2 (stepAll 7 5 (stepAll 7 3 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0353 : go 7 5 (stepAll 7 3 (stepAll 7 5 (stepAll 7 3 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0354 : go 7 5 (stepAll 7 4 (stepAll 7 5 (stepAll 7 3 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0355 : go 7 5 (stepAll 7 5 (stepAll 7 5 (stepAll 7 3 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0356 : go 7 5 (stepAll 7 6 (stepAll 7 5 (stepAll 7 3 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0360 : go 7 5 (stepAll 7 0 (stepAll 7 6 (stepAll 7 3 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0361 : go 7 5 (stepAll 7 1 (stepAll 7 6 (stepAll 7 3 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0362 : go 7 5 (stepAll 7 2 (stepAll 7 6 (stepAll 7 3 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0363 : go 7 5 (stepAll 7 3 (stepAll 7 6 (stepAll 7 3 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0364 : go 7 5 (stepAll 7 4 (stepAll 7 6 (stepAll 7 3 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0365 : go 7 5 (stepAll 7 5 (stepAll 7 6 (stepAll 7 3 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0366 : go 7 5 (stepAll 7 6 (stepAll 7 6 (stepAll 7 3 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0400 : go 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 4 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0401 : go 7 5 (stepAll 7 1 (stepAll 7 0 (stepAll 7 4 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0402 : go 7 5 (stepAll 7 2 (stepAll 7 0 (stepAll 7 4 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0403 : go 7 5 (stepAll 7 3 (stepAll 7 0 (stepAll 7 4 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0404 : go 7 5 (stepAll 7 4 (stepAll 7 0 (stepAll 7 4 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q0405 : go 7 5 (stepAll 7 5 (stepAll 7 0 (stepAll 7 4 (stepAll 7 0 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
