import CoveringLean.K2_Core
import CoveringLean.C1_Data_K5_10_4

/-!
GENERATED by gen.py (frente 1b, 2026-10-02; copy of ~/h/b/gen/gen.py + Final via cert_of_go) -- kernel tier, `decide +kernel` only.
cell: K5_10_4  q=5 n=10 R=4 M=625; data = `CoveringCerts.Data.K5_10_4` (C1_Data_K5_10_4.lean, sha256 in its header).
leaves: all 5^4 prefixes of length 4; each leaf is `go 5 6 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K5_10_4_q0402 : go 5 6 (stepAll 5 2 (stepAll 5 0 (stepAll 5 4 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0403 : go 5 6 (stepAll 5 3 (stepAll 5 0 (stepAll 5 4 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0404 : go 5 6 (stepAll 5 4 (stepAll 5 0 (stepAll 5 4 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0410 : go 5 6 (stepAll 5 0 (stepAll 5 1 (stepAll 5 4 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0411 : go 5 6 (stepAll 5 1 (stepAll 5 1 (stepAll 5 4 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0412 : go 5 6 (stepAll 5 2 (stepAll 5 1 (stepAll 5 4 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0413 : go 5 6 (stepAll 5 3 (stepAll 5 1 (stepAll 5 4 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0414 : go 5 6 (stepAll 5 4 (stepAll 5 1 (stepAll 5 4 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0420 : go 5 6 (stepAll 5 0 (stepAll 5 2 (stepAll 5 4 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0421 : go 5 6 (stepAll 5 1 (stepAll 5 2 (stepAll 5 4 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0422 : go 5 6 (stepAll 5 2 (stepAll 5 2 (stepAll 5 4 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0423 : go 5 6 (stepAll 5 3 (stepAll 5 2 (stepAll 5 4 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0424 : go 5 6 (stepAll 5 4 (stepAll 5 2 (stepAll 5 4 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0430 : go 5 6 (stepAll 5 0 (stepAll 5 3 (stepAll 5 4 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0431 : go 5 6 (stepAll 5 1 (stepAll 5 3 (stepAll 5 4 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0432 : go 5 6 (stepAll 5 2 (stepAll 5 3 (stepAll 5 4 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0433 : go 5 6 (stepAll 5 3 (stepAll 5 3 (stepAll 5 4 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

end CoveringKernel
