import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q1360 : go 7 5 (stepAll 7 0 (stepAll 7 6 (stepAll 7 3 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1361 : go 7 5 (stepAll 7 1 (stepAll 7 6 (stepAll 7 3 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1362 : go 7 5 (stepAll 7 2 (stepAll 7 6 (stepAll 7 3 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1363 : go 7 5 (stepAll 7 3 (stepAll 7 6 (stepAll 7 3 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1364 : go 7 5 (stepAll 7 4 (stepAll 7 6 (stepAll 7 3 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1365 : go 7 5 (stepAll 7 5 (stepAll 7 6 (stepAll 7 3 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1366 : go 7 5 (stepAll 7 6 (stepAll 7 6 (stepAll 7 3 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1400 : go 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1401 : go 7 5 (stepAll 7 1 (stepAll 7 0 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1402 : go 7 5 (stepAll 7 2 (stepAll 7 0 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1403 : go 7 5 (stepAll 7 3 (stepAll 7 0 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1404 : go 7 5 (stepAll 7 4 (stepAll 7 0 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1405 : go 7 5 (stepAll 7 5 (stepAll 7 0 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1406 : go 7 5 (stepAll 7 6 (stepAll 7 0 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1410 : go 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1411 : go 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1412 : go 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1413 : go 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1414 : go 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1415 : go 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1416 : go 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1420 : go 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1421 : go 7 5 (stepAll 7 1 (stepAll 7 2 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1422 : go 7 5 (stepAll 7 2 (stepAll 7 2 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1423 : go 7 5 (stepAll 7 3 (stepAll 7 2 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1424 : go 7 5 (stepAll 7 4 (stepAll 7 2 (stepAll 7 4 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
