import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q6155 : go 7 5 (stepAll 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6156 : go 7 5 (stepAll 7 6 (stepAll 7 5 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6160 : go 7 5 (stepAll 7 0 (stepAll 7 6 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6161 : go 7 5 (stepAll 7 1 (stepAll 7 6 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6162 : go 7 5 (stepAll 7 2 (stepAll 7 6 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6163 : go 7 5 (stepAll 7 3 (stepAll 7 6 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6164 : go 7 5 (stepAll 7 4 (stepAll 7 6 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6165 : go 7 5 (stepAll 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6166 : go 7 5 (stepAll 7 6 (stepAll 7 6 (stepAll 7 1 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6200 : go 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 2 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6201 : go 7 5 (stepAll 7 1 (stepAll 7 0 (stepAll 7 2 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6202 : go 7 5 (stepAll 7 2 (stepAll 7 0 (stepAll 7 2 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6203 : go 7 5 (stepAll 7 3 (stepAll 7 0 (stepAll 7 2 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6204 : go 7 5 (stepAll 7 4 (stepAll 7 0 (stepAll 7 2 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6205 : go 7 5 (stepAll 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6206 : go 7 5 (stepAll 7 6 (stepAll 7 0 (stepAll 7 2 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6210 : go 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 2 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6211 : go 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 2 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6212 : go 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 2 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6213 : go 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 2 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6214 : go 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 2 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6215 : go 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 2 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6216 : go 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 2 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6220 : go 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 2 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6221 : go 7 5 (stepAll 7 1 (stepAll 7 2 (stepAll 7 2 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6222 : go 7 5 (stepAll 7 2 (stepAll 7 2 (stepAll 7 2 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
