import CoveringLean.K2_Core
import CoveringLean.C1_Data_K5_9_3

/-!
GENERATED by gen.py (frente 1b, 2026-10-02; copy of ~/h/b/gen/gen.py + Final via cert_of_go) -- kernel tier, `decide +kernel` only.
cell: K5_9_3  q=5 n=9 R=3 M=1250; data = `CoveringCerts.Data.K5_9_3` (C1_Data_K5_9_3.lean, sha256 in its header).
leaves: all 5^4 prefixes of length 4; each leaf is `go 5 5 (stepAll ... (wordItems 3 W)) = true`.
-/

namespace CoveringKernel

theorem K5_9_3_q4020 : go 5 5 (stepAll 5 0 (stepAll 5 2 (stepAll 5 0 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4021 : go 5 5 (stepAll 5 1 (stepAll 5 2 (stepAll 5 0 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4022 : go 5 5 (stepAll 5 2 (stepAll 5 2 (stepAll 5 0 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4023 : go 5 5 (stepAll 5 3 (stepAll 5 2 (stepAll 5 0 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4024 : go 5 5 (stepAll 5 4 (stepAll 5 2 (stepAll 5 0 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4030 : go 5 5 (stepAll 5 0 (stepAll 5 3 (stepAll 5 0 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4031 : go 5 5 (stepAll 5 1 (stepAll 5 3 (stepAll 5 0 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4032 : go 5 5 (stepAll 5 2 (stepAll 5 3 (stepAll 5 0 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4033 : go 5 5 (stepAll 5 3 (stepAll 5 3 (stepAll 5 0 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4034 : go 5 5 (stepAll 5 4 (stepAll 5 3 (stepAll 5 0 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4040 : go 5 5 (stepAll 5 0 (stepAll 5 4 (stepAll 5 0 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4041 : go 5 5 (stepAll 5 1 (stepAll 5 4 (stepAll 5 0 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4042 : go 5 5 (stepAll 5 2 (stepAll 5 4 (stepAll 5 0 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4043 : go 5 5 (stepAll 5 3 (stepAll 5 4 (stepAll 5 0 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4044 : go 5 5 (stepAll 5 4 (stepAll 5 4 (stepAll 5 0 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4100 : go 5 5 (stepAll 5 0 (stepAll 5 0 (stepAll 5 1 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4101 : go 5 5 (stepAll 5 1 (stepAll 5 0 (stepAll 5 1 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4102 : go 5 5 (stepAll 5 2 (stepAll 5 0 (stepAll 5 1 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4103 : go 5 5 (stepAll 5 3 (stepAll 5 0 (stepAll 5 1 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4104 : go 5 5 (stepAll 5 4 (stepAll 5 0 (stepAll 5 1 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4110 : go 5 5 (stepAll 5 0 (stepAll 5 1 (stepAll 5 1 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4111 : go 5 5 (stepAll 5 1 (stepAll 5 1 (stepAll 5 1 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4112 : go 5 5 (stepAll 5 2 (stepAll 5 1 (stepAll 5 1 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4113 : go 5 5 (stepAll 5 3 (stepAll 5 1 (stepAll 5 1 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4114 : go 5 5 (stepAll 5 4 (stepAll 5 1 (stepAll 5 1 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4120 : go 5 5 (stepAll 5 0 (stepAll 5 2 (stepAll 5 1 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4121 : go 5 5 (stepAll 5 1 (stepAll 5 2 (stepAll 5 1 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4122 : go 5 5 (stepAll 5 2 (stepAll 5 2 (stepAll 5 1 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4123 : go 5 5 (stepAll 5 3 (stepAll 5 2 (stepAll 5 1 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4124 : go 5 5 (stepAll 5 4 (stepAll 5 2 (stepAll 5 1 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4130 : go 5 5 (stepAll 5 0 (stepAll 5 3 (stepAll 5 1 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4131 : go 5 5 (stepAll 5 1 (stepAll 5 3 (stepAll 5 1 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4132 : go 5 5 (stepAll 5 2 (stepAll 5 3 (stepAll 5 1 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4133 : go 5 5 (stepAll 5 3 (stepAll 5 3 (stepAll 5 1 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4134 : go 5 5 (stepAll 5 4 (stepAll 5 3 (stepAll 5 1 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4140 : go 5 5 (stepAll 5 0 (stepAll 5 4 (stepAll 5 1 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4141 : go 5 5 (stepAll 5 1 (stepAll 5 4 (stepAll 5 1 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4142 : go 5 5 (stepAll 5 2 (stepAll 5 4 (stepAll 5 1 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4143 : go 5 5 (stepAll 5 3 (stepAll 5 4 (stepAll 5 1 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4144 : go 5 5 (stepAll 5 4 (stepAll 5 4 (stepAll 5 1 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4200 : go 5 5 (stepAll 5 0 (stepAll 5 0 (stepAll 5 2 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4201 : go 5 5 (stepAll 5 1 (stepAll 5 0 (stepAll 5 2 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4202 : go 5 5 (stepAll 5 2 (stepAll 5 0 (stepAll 5 2 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4203 : go 5 5 (stepAll 5 3 (stepAll 5 0 (stepAll 5 2 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4204 : go 5 5 (stepAll 5 4 (stepAll 5 0 (stepAll 5 2 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4210 : go 5 5 (stepAll 5 0 (stepAll 5 1 (stepAll 5 2 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4211 : go 5 5 (stepAll 5 1 (stepAll 5 1 (stepAll 5 2 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4212 : go 5 5 (stepAll 5 2 (stepAll 5 1 (stepAll 5 2 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4213 : go 5 5 (stepAll 5 3 (stepAll 5 1 (stepAll 5 2 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4214 : go 5 5 (stepAll 5 4 (stepAll 5 1 (stepAll 5 2 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

theorem K5_9_3_q4220 : go 5 5 (stepAll 5 0 (stepAll 5 2 (stepAll 5 2 (stepAll 5 4 (wordItems 3 CoveringCerts.Data.K5_9_3))))) = true := by decide +kernel

end CoveringKernel
