import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q2441 : go 7 5 (stepAll 7 1 (stepAll 7 4 (stepAll 7 4 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2442 : go 7 5 (stepAll 7 2 (stepAll 7 4 (stepAll 7 4 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2443 : go 7 5 (stepAll 7 3 (stepAll 7 4 (stepAll 7 4 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2444 : go 7 5 (stepAll 7 4 (stepAll 7 4 (stepAll 7 4 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2445 : go 7 5 (stepAll 7 5 (stepAll 7 4 (stepAll 7 4 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2446 : go 7 5 (stepAll 7 6 (stepAll 7 4 (stepAll 7 4 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2450 : go 7 5 (stepAll 7 0 (stepAll 7 5 (stepAll 7 4 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2451 : go 7 5 (stepAll 7 1 (stepAll 7 5 (stepAll 7 4 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2452 : go 7 5 (stepAll 7 2 (stepAll 7 5 (stepAll 7 4 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2453 : go 7 5 (stepAll 7 3 (stepAll 7 5 (stepAll 7 4 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2454 : go 7 5 (stepAll 7 4 (stepAll 7 5 (stepAll 7 4 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2455 : go 7 5 (stepAll 7 5 (stepAll 7 5 (stepAll 7 4 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2456 : go 7 5 (stepAll 7 6 (stepAll 7 5 (stepAll 7 4 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2460 : go 7 5 (stepAll 7 0 (stepAll 7 6 (stepAll 7 4 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2461 : go 7 5 (stepAll 7 1 (stepAll 7 6 (stepAll 7 4 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2462 : go 7 5 (stepAll 7 2 (stepAll 7 6 (stepAll 7 4 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2463 : go 7 5 (stepAll 7 3 (stepAll 7 6 (stepAll 7 4 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2464 : go 7 5 (stepAll 7 4 (stepAll 7 6 (stepAll 7 4 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2465 : go 7 5 (stepAll 7 5 (stepAll 7 6 (stepAll 7 4 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2466 : go 7 5 (stepAll 7 6 (stepAll 7 6 (stepAll 7 4 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2500 : go 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 5 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2501 : go 7 5 (stepAll 7 1 (stepAll 7 0 (stepAll 7 5 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2502 : go 7 5 (stepAll 7 2 (stepAll 7 0 (stepAll 7 5 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2503 : go 7 5 (stepAll 7 3 (stepAll 7 0 (stepAll 7 5 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q2504 : go 7 5 (stepAll 7 4 (stepAll 7 0 (stepAll 7 5 (stepAll 7 2 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
