import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q3355 : go 7 5 (stepAll 7 5 (stepAll 7 5 (stepAll 7 3 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3356 : go 7 5 (stepAll 7 6 (stepAll 7 5 (stepAll 7 3 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3360 : go 7 5 (stepAll 7 0 (stepAll 7 6 (stepAll 7 3 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3361 : go 7 5 (stepAll 7 1 (stepAll 7 6 (stepAll 7 3 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3362 : go 7 5 (stepAll 7 2 (stepAll 7 6 (stepAll 7 3 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3363 : go 7 5 (stepAll 7 3 (stepAll 7 6 (stepAll 7 3 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3364 : go 7 5 (stepAll 7 4 (stepAll 7 6 (stepAll 7 3 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3365 : go 7 5 (stepAll 7 5 (stepAll 7 6 (stepAll 7 3 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3366 : go 7 5 (stepAll 7 6 (stepAll 7 6 (stepAll 7 3 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3400 : go 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 4 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3401 : go 7 5 (stepAll 7 1 (stepAll 7 0 (stepAll 7 4 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3402 : go 7 5 (stepAll 7 2 (stepAll 7 0 (stepAll 7 4 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3403 : go 7 5 (stepAll 7 3 (stepAll 7 0 (stepAll 7 4 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3404 : go 7 5 (stepAll 7 4 (stepAll 7 0 (stepAll 7 4 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3405 : go 7 5 (stepAll 7 5 (stepAll 7 0 (stepAll 7 4 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3406 : go 7 5 (stepAll 7 6 (stepAll 7 0 (stepAll 7 4 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3410 : go 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 4 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3411 : go 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 4 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3412 : go 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 4 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3413 : go 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 4 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3414 : go 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 4 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3415 : go 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 4 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3416 : go 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 4 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3420 : go 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 4 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3421 : go 7 5 (stepAll 7 1 (stepAll 7 2 (stepAll 7 4 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
