import CoveringLean.K2_Core
import CoveringLean.C1_CoverCheck
import CoveringLean.K3_K4_10_4_P1
import CoveringLean.K3_K4_10_4_P2
import CoveringLean.K3_K4_10_4_P3
import CoveringLean.K3_K4_10_4_P4

/-!
GENERATED by gen.py (frente 1b, 2026-10-02; copy of ~/h/b/gen/gen.py + Final via cert_of_go) -- kernel tier, `decide +kernel` only.
cell: K4_10_4  q=4 n=10 R=4 M=192; data = `CoveringCerts.Data.K4_10_4` (C1_Data_K4_10_4.lean, sha256 in its header).
leaves: all 4^3 prefixes of length 3; each leaf is `go 4 7 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K4_10_4_q00 : go 4 8 (stepAll 4 0 (stepAll 4 0 (wordItems 4 CoveringCerts.Data.K4_10_4))) = true :=
  go_split 4 7 (stepAll 4 0 (stepAll 4 0 (wordItems 4 CoveringCerts.Data.K4_10_4))) (by
  intro v hv
  interval_cases v
  · exact K4_10_4_q000
  · exact K4_10_4_q001
  · exact K4_10_4_q002
  · exact K4_10_4_q003
  )

theorem K4_10_4_q01 : go 4 8 (stepAll 4 1 (stepAll 4 0 (wordItems 4 CoveringCerts.Data.K4_10_4))) = true :=
  go_split 4 7 (stepAll 4 1 (stepAll 4 0 (wordItems 4 CoveringCerts.Data.K4_10_4))) (by
  intro v hv
  interval_cases v
  · exact K4_10_4_q010
  · exact K4_10_4_q011
  · exact K4_10_4_q012
  · exact K4_10_4_q013
  )

theorem K4_10_4_q02 : go 4 8 (stepAll 4 2 (stepAll 4 0 (wordItems 4 CoveringCerts.Data.K4_10_4))) = true :=
  go_split 4 7 (stepAll 4 2 (stepAll 4 0 (wordItems 4 CoveringCerts.Data.K4_10_4))) (by
  intro v hv
  interval_cases v
  · exact K4_10_4_q020
  · exact K4_10_4_q021
  · exact K4_10_4_q022
  · exact K4_10_4_q023
  )

theorem K4_10_4_q03 : go 4 8 (stepAll 4 3 (stepAll 4 0 (wordItems 4 CoveringCerts.Data.K4_10_4))) = true :=
  go_split 4 7 (stepAll 4 3 (stepAll 4 0 (wordItems 4 CoveringCerts.Data.K4_10_4))) (by
  intro v hv
  interval_cases v
  · exact K4_10_4_q030
  · exact K4_10_4_q031
  · exact K4_10_4_q032
  · exact K4_10_4_q033
  )

theorem K4_10_4_q10 : go 4 8 (stepAll 4 0 (stepAll 4 1 (wordItems 4 CoveringCerts.Data.K4_10_4))) = true :=
  go_split 4 7 (stepAll 4 0 (stepAll 4 1 (wordItems 4 CoveringCerts.Data.K4_10_4))) (by
  intro v hv
  interval_cases v
  · exact K4_10_4_q100
  · exact K4_10_4_q101
  · exact K4_10_4_q102
  · exact K4_10_4_q103
  )

theorem K4_10_4_q11 : go 4 8 (stepAll 4 1 (stepAll 4 1 (wordItems 4 CoveringCerts.Data.K4_10_4))) = true :=
  go_split 4 7 (stepAll 4 1 (stepAll 4 1 (wordItems 4 CoveringCerts.Data.K4_10_4))) (by
  intro v hv
  interval_cases v
  · exact K4_10_4_q110
  · exact K4_10_4_q111
  · exact K4_10_4_q112
  · exact K4_10_4_q113
  )

theorem K4_10_4_q12 : go 4 8 (stepAll 4 2 (stepAll 4 1 (wordItems 4 CoveringCerts.Data.K4_10_4))) = true :=
  go_split 4 7 (stepAll 4 2 (stepAll 4 1 (wordItems 4 CoveringCerts.Data.K4_10_4))) (by
  intro v hv
  interval_cases v
  · exact K4_10_4_q120
  · exact K4_10_4_q121
  · exact K4_10_4_q122
  · exact K4_10_4_q123
  )

theorem K4_10_4_q13 : go 4 8 (stepAll 4 3 (stepAll 4 1 (wordItems 4 CoveringCerts.Data.K4_10_4))) = true :=
  go_split 4 7 (stepAll 4 3 (stepAll 4 1 (wordItems 4 CoveringCerts.Data.K4_10_4))) (by
  intro v hv
  interval_cases v
  · exact K4_10_4_q130
  · exact K4_10_4_q131
  · exact K4_10_4_q132
  · exact K4_10_4_q133
  )

theorem K4_10_4_q20 : go 4 8 (stepAll 4 0 (stepAll 4 2 (wordItems 4 CoveringCerts.Data.K4_10_4))) = true :=
  go_split 4 7 (stepAll 4 0 (stepAll 4 2 (wordItems 4 CoveringCerts.Data.K4_10_4))) (by
  intro v hv
  interval_cases v
  · exact K4_10_4_q200
  · exact K4_10_4_q201
  · exact K4_10_4_q202
  · exact K4_10_4_q203
  )

theorem K4_10_4_q21 : go 4 8 (stepAll 4 1 (stepAll 4 2 (wordItems 4 CoveringCerts.Data.K4_10_4))) = true :=
  go_split 4 7 (stepAll 4 1 (stepAll 4 2 (wordItems 4 CoveringCerts.Data.K4_10_4))) (by
  intro v hv
  interval_cases v
  · exact K4_10_4_q210
  · exact K4_10_4_q211
  · exact K4_10_4_q212
  · exact K4_10_4_q213
  )

theorem K4_10_4_q22 : go 4 8 (stepAll 4 2 (stepAll 4 2 (wordItems 4 CoveringCerts.Data.K4_10_4))) = true :=
  go_split 4 7 (stepAll 4 2 (stepAll 4 2 (wordItems 4 CoveringCerts.Data.K4_10_4))) (by
  intro v hv
  interval_cases v
  · exact K4_10_4_q220
  · exact K4_10_4_q221
  · exact K4_10_4_q222
  · exact K4_10_4_q223
  )

theorem K4_10_4_q23 : go 4 8 (stepAll 4 3 (stepAll 4 2 (wordItems 4 CoveringCerts.Data.K4_10_4))) = true :=
  go_split 4 7 (stepAll 4 3 (stepAll 4 2 (wordItems 4 CoveringCerts.Data.K4_10_4))) (by
  intro v hv
  interval_cases v
  · exact K4_10_4_q230
  · exact K4_10_4_q231
  · exact K4_10_4_q232
  · exact K4_10_4_q233
  )

theorem K4_10_4_q30 : go 4 8 (stepAll 4 0 (stepAll 4 3 (wordItems 4 CoveringCerts.Data.K4_10_4))) = true :=
  go_split 4 7 (stepAll 4 0 (stepAll 4 3 (wordItems 4 CoveringCerts.Data.K4_10_4))) (by
  intro v hv
  interval_cases v
  · exact K4_10_4_q300
  · exact K4_10_4_q301
  · exact K4_10_4_q302
  · exact K4_10_4_q303
  )

theorem K4_10_4_q31 : go 4 8 (stepAll 4 1 (stepAll 4 3 (wordItems 4 CoveringCerts.Data.K4_10_4))) = true :=
  go_split 4 7 (stepAll 4 1 (stepAll 4 3 (wordItems 4 CoveringCerts.Data.K4_10_4))) (by
  intro v hv
  interval_cases v
  · exact K4_10_4_q310
  · exact K4_10_4_q311
  · exact K4_10_4_q312
  · exact K4_10_4_q313
  )

theorem K4_10_4_q32 : go 4 8 (stepAll 4 2 (stepAll 4 3 (wordItems 4 CoveringCerts.Data.K4_10_4))) = true :=
  go_split 4 7 (stepAll 4 2 (stepAll 4 3 (wordItems 4 CoveringCerts.Data.K4_10_4))) (by
  intro v hv
  interval_cases v
  · exact K4_10_4_q320
  · exact K4_10_4_q321
  · exact K4_10_4_q322
  · exact K4_10_4_q323
  )

theorem K4_10_4_q33 : go 4 8 (stepAll 4 3 (stepAll 4 3 (wordItems 4 CoveringCerts.Data.K4_10_4))) = true :=
  go_split 4 7 (stepAll 4 3 (stepAll 4 3 (wordItems 4 CoveringCerts.Data.K4_10_4))) (by
  intro v hv
  interval_cases v
  · exact K4_10_4_q330
  · exact K4_10_4_q331
  · exact K4_10_4_q332
  · exact K4_10_4_q333
  )

theorem K4_10_4_q0 : go 4 9 (stepAll 4 0 (wordItems 4 CoveringCerts.Data.K4_10_4)) = true :=
  go_split 4 8 (stepAll 4 0 (wordItems 4 CoveringCerts.Data.K4_10_4)) (by
  intro v hv
  interval_cases v
  · exact K4_10_4_q00
  · exact K4_10_4_q01
  · exact K4_10_4_q02
  · exact K4_10_4_q03
  )

theorem K4_10_4_q1 : go 4 9 (stepAll 4 1 (wordItems 4 CoveringCerts.Data.K4_10_4)) = true :=
  go_split 4 8 (stepAll 4 1 (wordItems 4 CoveringCerts.Data.K4_10_4)) (by
  intro v hv
  interval_cases v
  · exact K4_10_4_q10
  · exact K4_10_4_q11
  · exact K4_10_4_q12
  · exact K4_10_4_q13
  )

theorem K4_10_4_q2 : go 4 9 (stepAll 4 2 (wordItems 4 CoveringCerts.Data.K4_10_4)) = true :=
  go_split 4 8 (stepAll 4 2 (wordItems 4 CoveringCerts.Data.K4_10_4)) (by
  intro v hv
  interval_cases v
  · exact K4_10_4_q20
  · exact K4_10_4_q21
  · exact K4_10_4_q22
  · exact K4_10_4_q23
  )

theorem K4_10_4_q3 : go 4 9 (stepAll 4 3 (wordItems 4 CoveringCerts.Data.K4_10_4)) = true :=
  go_split 4 8 (stepAll 4 3 (wordItems 4 CoveringCerts.Data.K4_10_4)) (by
  intro v hv
  interval_cases v
  · exact K4_10_4_q30
  · exact K4_10_4_q31
  · exact K4_10_4_q32
  · exact K4_10_4_q33
  )

theorem K4_10_4_q : go 4 10 (wordItems 4 CoveringCerts.Data.K4_10_4) = true :=
  go_split 4 9 (wordItems 4 CoveringCerts.Data.K4_10_4) (by
  intro v hv
  interval_cases v
  · exact K4_10_4_q0
  · exact K4_10_4_q1
  · exact K4_10_4_q2
  · exact K4_10_4_q3
  )

theorem K4_10_4_le_192_kernel_le :
    ∃ C : Finset (Fin 10 → ZMod 4), C.card ≤ 192 ∧ CoveringA2.Covers 4 C := by
  have h := cover_simple 4 10 4 CoveringCerts.Data.K4_10_4 K4_10_4_q
  have hl : CoveringCerts.Data.K4_10_4.length = 192 := by decide +kernel
  rw [hl] at h
  exact h

end CoveringKernel

#print axioms CoveringKernel.K4_10_4_le_192_kernel_le
