import CoveringLean.K2_Core
import CoveringLean.C1_Data_K5_10_4

/-!
GENERATED by gen.py (frente 1b, 2026-10-02; copy of ~/h/b/gen/gen.py + Final via cert_of_go) -- kernel tier, `decide +kernel` only.
cell: K5_10_4  q=5 n=10 R=4 M=625; data = `CoveringCerts.Data.K5_10_4` (C1_Data_K5_10_4.lean, sha256 in its header).
leaves: all 5^4 prefixes of length 4; each leaf is `go 5 6 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K5_10_4_q1423 : go 5 6 (stepAll 5 3 (stepAll 5 2 (stepAll 5 4 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1424 : go 5 6 (stepAll 5 4 (stepAll 5 2 (stepAll 5 4 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1430 : go 5 6 (stepAll 5 0 (stepAll 5 3 (stepAll 5 4 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1431 : go 5 6 (stepAll 5 1 (stepAll 5 3 (stepAll 5 4 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1432 : go 5 6 (stepAll 5 2 (stepAll 5 3 (stepAll 5 4 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1433 : go 5 6 (stepAll 5 3 (stepAll 5 3 (stepAll 5 4 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1434 : go 5 6 (stepAll 5 4 (stepAll 5 3 (stepAll 5 4 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1440 : go 5 6 (stepAll 5 0 (stepAll 5 4 (stepAll 5 4 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1441 : go 5 6 (stepAll 5 1 (stepAll 5 4 (stepAll 5 4 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1442 : go 5 6 (stepAll 5 2 (stepAll 5 4 (stepAll 5 4 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1443 : go 5 6 (stepAll 5 3 (stepAll 5 4 (stepAll 5 4 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1444 : go 5 6 (stepAll 5 4 (stepAll 5 4 (stepAll 5 4 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2000 : go 5 6 (stepAll 5 0 (stepAll 5 0 (stepAll 5 0 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2001 : go 5 6 (stepAll 5 1 (stepAll 5 0 (stepAll 5 0 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2002 : go 5 6 (stepAll 5 2 (stepAll 5 0 (stepAll 5 0 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2003 : go 5 6 (stepAll 5 3 (stepAll 5 0 (stepAll 5 0 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q2004 : go 5 6 (stepAll 5 4 (stepAll 5 0 (stepAll 5 0 (stepAll 5 2 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

end CoveringKernel
