import CoveringLean.K2_Core
import CoveringLean.C1_Data_K5_9_5

/-!
GENERATED by gen.py (frente 1b, 2026-10-02; copy of ~/h/b/gen/gen.py + Final via cert_of_go) -- kernel tier, `decide +kernel` only.
cell: K5_9_5  q=5 n=9 R=5 M=50; data = `CoveringCerts.Data.K5_9_5` (C1_Data_K5_9_5.lean, sha256 in its header).
leaves: all 5^2 prefixes of length 2; each leaf is `go 5 7 (stepAll ... (wordItems 5 W)) = true`.
-/

namespace CoveringKernel

theorem K5_9_5_q34 : go 5 7 (stepAll 5 4 (stepAll 5 3 (wordItems 5 CoveringCerts.Data.K5_9_5))) = true := by decide +kernel

theorem K5_9_5_q40 : go 5 7 (stepAll 5 0 (stepAll 5 4 (wordItems 5 CoveringCerts.Data.K5_9_5))) = true := by decide +kernel

theorem K5_9_5_q41 : go 5 7 (stepAll 5 1 (stepAll 5 4 (wordItems 5 CoveringCerts.Data.K5_9_5))) = true := by decide +kernel

theorem K5_9_5_q42 : go 5 7 (stepAll 5 2 (stepAll 5 4 (wordItems 5 CoveringCerts.Data.K5_9_5))) = true := by decide +kernel

theorem K5_9_5_q43 : go 5 7 (stepAll 5 3 (stepAll 5 4 (wordItems 5 CoveringCerts.Data.K5_9_5))) = true := by decide +kernel

theorem K5_9_5_q44 : go 5 7 (stepAll 5 4 (stepAll 5 4 (wordItems 5 CoveringCerts.Data.K5_9_5))) = true := by decide +kernel

end CoveringKernel
