import CoveringLean.K2_Core
import CoveringLean.C1_Data_K5_10_4

/-!
GENERATED by gen.py (frente 1b, 2026-10-02; copy of ~/h/b/gen/gen.py + Final via cert_of_go) -- kernel tier, `decide +kernel` only.
cell: K5_10_4  q=5 n=10 R=4 M=625; data = `CoveringCerts.Data.K5_10_4` (C1_Data_K5_10_4.lean, sha256 in its header).
leaves: all 5^4 prefixes of length 4; each leaf is `go 5 6 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K5_10_4_q0320 : go 5 6 (stepAll 5 0 (stepAll 5 2 (stepAll 5 3 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0321 : go 5 6 (stepAll 5 1 (stepAll 5 2 (stepAll 5 3 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0322 : go 5 6 (stepAll 5 2 (stepAll 5 2 (stepAll 5 3 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0323 : go 5 6 (stepAll 5 3 (stepAll 5 2 (stepAll 5 3 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0324 : go 5 6 (stepAll 5 4 (stepAll 5 2 (stepAll 5 3 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0330 : go 5 6 (stepAll 5 0 (stepAll 5 3 (stepAll 5 3 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0331 : go 5 6 (stepAll 5 1 (stepAll 5 3 (stepAll 5 3 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0332 : go 5 6 (stepAll 5 2 (stepAll 5 3 (stepAll 5 3 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0333 : go 5 6 (stepAll 5 3 (stepAll 5 3 (stepAll 5 3 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0334 : go 5 6 (stepAll 5 4 (stepAll 5 3 (stepAll 5 3 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0340 : go 5 6 (stepAll 5 0 (stepAll 5 4 (stepAll 5 3 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0341 : go 5 6 (stepAll 5 1 (stepAll 5 4 (stepAll 5 3 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0342 : go 5 6 (stepAll 5 2 (stepAll 5 4 (stepAll 5 3 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0343 : go 5 6 (stepAll 5 3 (stepAll 5 4 (stepAll 5 3 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0344 : go 5 6 (stepAll 5 4 (stepAll 5 4 (stepAll 5 3 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0400 : go 5 6 (stepAll 5 0 (stepAll 5 0 (stepAll 5 4 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q0401 : go 5 6 (stepAll 5 1 (stepAll 5 0 (stepAll 5 4 (stepAll 5 0 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

end CoveringKernel
