import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q5004 : go 7 5 (stepAll 7 4 (stepAll 7 0 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5005 : go 7 5 (stepAll 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5006 : go 7 5 (stepAll 7 6 (stepAll 7 0 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5010 : go 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5011 : go 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5012 : go 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5013 : go 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5014 : go 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5015 : go 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5016 : go 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5020 : go 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5021 : go 7 5 (stepAll 7 1 (stepAll 7 2 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5022 : go 7 5 (stepAll 7 2 (stepAll 7 2 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5023 : go 7 5 (stepAll 7 3 (stepAll 7 2 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5024 : go 7 5 (stepAll 7 4 (stepAll 7 2 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5025 : go 7 5 (stepAll 7 5 (stepAll 7 2 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5026 : go 7 5 (stepAll 7 6 (stepAll 7 2 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5030 : go 7 5 (stepAll 7 0 (stepAll 7 3 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5031 : go 7 5 (stepAll 7 1 (stepAll 7 3 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5032 : go 7 5 (stepAll 7 2 (stepAll 7 3 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5033 : go 7 5 (stepAll 7 3 (stepAll 7 3 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5034 : go 7 5 (stepAll 7 4 (stepAll 7 3 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5035 : go 7 5 (stepAll 7 5 (stepAll 7 3 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5036 : go 7 5 (stepAll 7 6 (stepAll 7 3 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5040 : go 7 5 (stepAll 7 0 (stepAll 7 4 (stepAll 7 0 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
