import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q5654 : go 7 5 (stepAll 7 4 (stepAll 7 5 (stepAll 7 6 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5655 : go 7 5 (stepAll 7 5 (stepAll 7 5 (stepAll 7 6 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5656 : go 7 5 (stepAll 7 6 (stepAll 7 5 (stepAll 7 6 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5660 : go 7 5 (stepAll 7 0 (stepAll 7 6 (stepAll 7 6 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5661 : go 7 5 (stepAll 7 1 (stepAll 7 6 (stepAll 7 6 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5662 : go 7 5 (stepAll 7 2 (stepAll 7 6 (stepAll 7 6 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5663 : go 7 5 (stepAll 7 3 (stepAll 7 6 (stepAll 7 6 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5664 : go 7 5 (stepAll 7 4 (stepAll 7 6 (stepAll 7 6 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5665 : go 7 5 (stepAll 7 5 (stepAll 7 6 (stepAll 7 6 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q5666 : go 7 5 (stepAll 7 6 (stepAll 7 6 (stepAll 7 6 (stepAll 7 5 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6000 : go 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 0 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6001 : go 7 5 (stepAll 7 1 (stepAll 7 0 (stepAll 7 0 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6002 : go 7 5 (stepAll 7 2 (stepAll 7 0 (stepAll 7 0 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6003 : go 7 5 (stepAll 7 3 (stepAll 7 0 (stepAll 7 0 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6004 : go 7 5 (stepAll 7 4 (stepAll 7 0 (stepAll 7 0 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6005 : go 7 5 (stepAll 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6006 : go 7 5 (stepAll 7 6 (stepAll 7 0 (stepAll 7 0 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6010 : go 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 0 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6011 : go 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 0 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6012 : go 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 0 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6013 : go 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 0 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6014 : go 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 0 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6015 : go 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 0 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6016 : go 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 0 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6020 : go 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 0 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q6021 : go 7 5 (stepAll 7 1 (stepAll 7 2 (stepAll 7 0 (stepAll 7 6 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
