import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q3456 : go 7 5 (stepAll 7 6 (stepAll 7 5 (stepAll 7 4 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3460 : go 7 5 (stepAll 7 0 (stepAll 7 6 (stepAll 7 4 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3461 : go 7 5 (stepAll 7 1 (stepAll 7 6 (stepAll 7 4 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3462 : go 7 5 (stepAll 7 2 (stepAll 7 6 (stepAll 7 4 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3463 : go 7 5 (stepAll 7 3 (stepAll 7 6 (stepAll 7 4 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3464 : go 7 5 (stepAll 7 4 (stepAll 7 6 (stepAll 7 4 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3465 : go 7 5 (stepAll 7 5 (stepAll 7 6 (stepAll 7 4 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3466 : go 7 5 (stepAll 7 6 (stepAll 7 6 (stepAll 7 4 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3500 : go 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 5 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3501 : go 7 5 (stepAll 7 1 (stepAll 7 0 (stepAll 7 5 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3502 : go 7 5 (stepAll 7 2 (stepAll 7 0 (stepAll 7 5 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3503 : go 7 5 (stepAll 7 3 (stepAll 7 0 (stepAll 7 5 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3504 : go 7 5 (stepAll 7 4 (stepAll 7 0 (stepAll 7 5 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3505 : go 7 5 (stepAll 7 5 (stepAll 7 0 (stepAll 7 5 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3506 : go 7 5 (stepAll 7 6 (stepAll 7 0 (stepAll 7 5 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3510 : go 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 5 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3511 : go 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 5 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3512 : go 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 5 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3513 : go 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 5 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3514 : go 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 5 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3515 : go 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 5 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3516 : go 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 5 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3520 : go 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 5 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
