import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q4024 : go 7 5 (stepAll 7 4 (stepAll 7 2 (stepAll 7 0 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4025 : go 7 5 (stepAll 7 5 (stepAll 7 2 (stepAll 7 0 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4026 : go 7 5 (stepAll 7 6 (stepAll 7 2 (stepAll 7 0 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4030 : go 7 5 (stepAll 7 0 (stepAll 7 3 (stepAll 7 0 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4031 : go 7 5 (stepAll 7 1 (stepAll 7 3 (stepAll 7 0 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4032 : go 7 5 (stepAll 7 2 (stepAll 7 3 (stepAll 7 0 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4033 : go 7 5 (stepAll 7 3 (stepAll 7 3 (stepAll 7 0 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4034 : go 7 5 (stepAll 7 4 (stepAll 7 3 (stepAll 7 0 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4035 : go 7 5 (stepAll 7 5 (stepAll 7 3 (stepAll 7 0 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4036 : go 7 5 (stepAll 7 6 (stepAll 7 3 (stepAll 7 0 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4040 : go 7 5 (stepAll 7 0 (stepAll 7 4 (stepAll 7 0 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4041 : go 7 5 (stepAll 7 1 (stepAll 7 4 (stepAll 7 0 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4042 : go 7 5 (stepAll 7 2 (stepAll 7 4 (stepAll 7 0 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4043 : go 7 5 (stepAll 7 3 (stepAll 7 4 (stepAll 7 0 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4044 : go 7 5 (stepAll 7 4 (stepAll 7 4 (stepAll 7 0 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4045 : go 7 5 (stepAll 7 5 (stepAll 7 4 (stepAll 7 0 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4046 : go 7 5 (stepAll 7 6 (stepAll 7 4 (stepAll 7 0 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4050 : go 7 5 (stepAll 7 0 (stepAll 7 5 (stepAll 7 0 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4051 : go 7 5 (stepAll 7 1 (stepAll 7 5 (stepAll 7 0 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4052 : go 7 5 (stepAll 7 2 (stepAll 7 5 (stepAll 7 0 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4053 : go 7 5 (stepAll 7 3 (stepAll 7 5 (stepAll 7 0 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4054 : go 7 5 (stepAll 7 4 (stepAll 7 5 (stepAll 7 0 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4055 : go 7 5 (stepAll 7 5 (stepAll 7 5 (stepAll 7 0 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4056 : go 7 5 (stepAll 7 6 (stepAll 7 5 (stepAll 7 0 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4060 : go 7 5 (stepAll 7 0 (stepAll 7 6 (stepAll 7 0 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4061 : go 7 5 (stepAll 7 1 (stepAll 7 6 (stepAll 7 0 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q4062 : go 7 5 (stepAll 7 2 (stepAll 7 6 (stepAll 7 0 (stepAll 7 4 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
