import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q1121 : go 7 5 (stepAll 7 1 (stepAll 7 2 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1122 : go 7 5 (stepAll 7 2 (stepAll 7 2 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1123 : go 7 5 (stepAll 7 3 (stepAll 7 2 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1124 : go 7 5 (stepAll 7 4 (stepAll 7 2 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1125 : go 7 5 (stepAll 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1126 : go 7 5 (stepAll 7 6 (stepAll 7 2 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1130 : go 7 5 (stepAll 7 0 (stepAll 7 3 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1131 : go 7 5 (stepAll 7 1 (stepAll 7 3 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1132 : go 7 5 (stepAll 7 2 (stepAll 7 3 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1133 : go 7 5 (stepAll 7 3 (stepAll 7 3 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1134 : go 7 5 (stepAll 7 4 (stepAll 7 3 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1135 : go 7 5 (stepAll 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1136 : go 7 5 (stepAll 7 6 (stepAll 7 3 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1140 : go 7 5 (stepAll 7 0 (stepAll 7 4 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1141 : go 7 5 (stepAll 7 1 (stepAll 7 4 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1142 : go 7 5 (stepAll 7 2 (stepAll 7 4 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1143 : go 7 5 (stepAll 7 3 (stepAll 7 4 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1144 : go 7 5 (stepAll 7 4 (stepAll 7 4 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1145 : go 7 5 (stepAll 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1146 : go 7 5 (stepAll 7 6 (stepAll 7 4 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1150 : go 7 5 (stepAll 7 0 (stepAll 7 5 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1151 : go 7 5 (stepAll 7 1 (stepAll 7 5 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1152 : go 7 5 (stepAll 7 2 (stepAll 7 5 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1153 : go 7 5 (stepAll 7 3 (stepAll 7 5 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1154 : go 7 5 (stepAll 7 4 (stepAll 7 5 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q1155 : go 7 5 (stepAll 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 1 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
