import CoveringLean.K2_Core
import CoveringLean.C1_Data_K5_10_4

/-!
GENERATED by gen.py (frente 1b, 2026-10-02; copy of ~/h/b/gen/gen.py + Final via cert_of_go) -- kernel tier, `decide +kernel` only.
cell: K5_10_4  q=5 n=10 R=4 M=625; data = `CoveringCerts.Data.K5_10_4` (C1_Data_K5_10_4.lean, sha256 in its header).
leaves: all 5^4 prefixes of length 4; each leaf is `go 5 6 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K5_10_4_q1140 : go 5 6 (stepAll 5 0 (stepAll 5 4 (stepAll 5 1 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1141 : go 5 6 (stepAll 5 1 (stepAll 5 4 (stepAll 5 1 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1142 : go 5 6 (stepAll 5 2 (stepAll 5 4 (stepAll 5 1 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1143 : go 5 6 (stepAll 5 3 (stepAll 5 4 (stepAll 5 1 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1144 : go 5 6 (stepAll 5 4 (stepAll 5 4 (stepAll 5 1 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1200 : go 5 6 (stepAll 5 0 (stepAll 5 0 (stepAll 5 2 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1201 : go 5 6 (stepAll 5 1 (stepAll 5 0 (stepAll 5 2 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1202 : go 5 6 (stepAll 5 2 (stepAll 5 0 (stepAll 5 2 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1203 : go 5 6 (stepAll 5 3 (stepAll 5 0 (stepAll 5 2 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1204 : go 5 6 (stepAll 5 4 (stepAll 5 0 (stepAll 5 2 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1210 : go 5 6 (stepAll 5 0 (stepAll 5 1 (stepAll 5 2 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1211 : go 5 6 (stepAll 5 1 (stepAll 5 1 (stepAll 5 2 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1212 : go 5 6 (stepAll 5 2 (stepAll 5 1 (stepAll 5 2 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1213 : go 5 6 (stepAll 5 3 (stepAll 5 1 (stepAll 5 2 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1214 : go 5 6 (stepAll 5 4 (stepAll 5 1 (stepAll 5 2 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1220 : go 5 6 (stepAll 5 0 (stepAll 5 2 (stepAll 5 2 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q1221 : go 5 6 (stepAll 5 1 (stepAll 5 2 (stepAll 5 2 (stepAll 5 1 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

end CoveringKernel
