import CoveringLean.K2_Core
import CoveringLean.C1_Data_K7_9_4

/-!
GENERATED by gen.py (frente 2, 2026-10-01) -- kernel tier, `decide +kernel` only.
cell: K7_9_4  q=7 n=9 R=4 M=1351; data = `CoveringCerts.Data.K7_9_4` (C1_Data_K7_9_4.lean, sha256 in its header).
leaves: all 7^4 prefixes of length 4; each leaf is `go 7 5 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K7_9_4_q3150 : go 7 5 (stepAll 7 0 (stepAll 7 5 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3151 : go 7 5 (stepAll 7 1 (stepAll 7 5 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3152 : go 7 5 (stepAll 7 2 (stepAll 7 5 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3153 : go 7 5 (stepAll 7 3 (stepAll 7 5 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3154 : go 7 5 (stepAll 7 4 (stepAll 7 5 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3155 : go 7 5 (stepAll 7 5 (stepAll 7 5 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3156 : go 7 5 (stepAll 7 6 (stepAll 7 5 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3160 : go 7 5 (stepAll 7 0 (stepAll 7 6 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3161 : go 7 5 (stepAll 7 1 (stepAll 7 6 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3162 : go 7 5 (stepAll 7 2 (stepAll 7 6 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3163 : go 7 5 (stepAll 7 3 (stepAll 7 6 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3164 : go 7 5 (stepAll 7 4 (stepAll 7 6 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3165 : go 7 5 (stepAll 7 5 (stepAll 7 6 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3166 : go 7 5 (stepAll 7 6 (stepAll 7 6 (stepAll 7 1 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3200 : go 7 5 (stepAll 7 0 (stepAll 7 0 (stepAll 7 2 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3201 : go 7 5 (stepAll 7 1 (stepAll 7 0 (stepAll 7 2 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3202 : go 7 5 (stepAll 7 2 (stepAll 7 0 (stepAll 7 2 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3203 : go 7 5 (stepAll 7 3 (stepAll 7 0 (stepAll 7 2 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3204 : go 7 5 (stepAll 7 4 (stepAll 7 0 (stepAll 7 2 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3205 : go 7 5 (stepAll 7 5 (stepAll 7 0 (stepAll 7 2 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3206 : go 7 5 (stepAll 7 6 (stepAll 7 0 (stepAll 7 2 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3210 : go 7 5 (stepAll 7 0 (stepAll 7 1 (stepAll 7 2 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3211 : go 7 5 (stepAll 7 1 (stepAll 7 1 (stepAll 7 2 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3212 : go 7 5 (stepAll 7 2 (stepAll 7 1 (stepAll 7 2 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3213 : go 7 5 (stepAll 7 3 (stepAll 7 1 (stepAll 7 2 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

theorem K7_9_4_q3214 : go 7 5 (stepAll 7 4 (stepAll 7 1 (stepAll 7 2 (stepAll 7 3 (wordItems 4 CoveringCerts.Data.K7_9_4))))) = true := by decide +kernel

end CoveringKernel
