import CoveringLean.K2_Core
import CoveringLean.C1_Data_K5_10_4

/-!
GENERATED by gen.py (frente 1b, 2026-10-02; copy of ~/h/b/gen/gen.py + Final via cert_of_go) -- kernel tier, `decide +kernel` only.
cell: K5_10_4  q=5 n=10 R=4 M=625; data = `CoveringCerts.Data.K5_10_4` (C1_Data_K5_10_4.lean, sha256 in its header).
leaves: all 5^4 prefixes of length 4; each leaf is `go 5 6 (stepAll ... (wordItems 4 W)) = true`.
-/

namespace CoveringKernel

theorem K5_10_4_q4221 : go 5 6 (stepAll 5 1 (stepAll 5 2 (stepAll 5 2 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4222 : go 5 6 (stepAll 5 2 (stepAll 5 2 (stepAll 5 2 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4223 : go 5 6 (stepAll 5 3 (stepAll 5 2 (stepAll 5 2 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4224 : go 5 6 (stepAll 5 4 (stepAll 5 2 (stepAll 5 2 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4230 : go 5 6 (stepAll 5 0 (stepAll 5 3 (stepAll 5 2 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4231 : go 5 6 (stepAll 5 1 (stepAll 5 3 (stepAll 5 2 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4232 : go 5 6 (stepAll 5 2 (stepAll 5 3 (stepAll 5 2 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4233 : go 5 6 (stepAll 5 3 (stepAll 5 3 (stepAll 5 2 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4234 : go 5 6 (stepAll 5 4 (stepAll 5 3 (stepAll 5 2 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4240 : go 5 6 (stepAll 5 0 (stepAll 5 4 (stepAll 5 2 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4241 : go 5 6 (stepAll 5 1 (stepAll 5 4 (stepAll 5 2 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4242 : go 5 6 (stepAll 5 2 (stepAll 5 4 (stepAll 5 2 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4243 : go 5 6 (stepAll 5 3 (stepAll 5 4 (stepAll 5 2 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4244 : go 5 6 (stepAll 5 4 (stepAll 5 4 (stepAll 5 2 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4300 : go 5 6 (stepAll 5 0 (stepAll 5 0 (stepAll 5 3 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4301 : go 5 6 (stepAll 5 1 (stepAll 5 0 (stepAll 5 3 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

theorem K5_10_4_q4302 : go 5 6 (stepAll 5 2 (stepAll 5 0 (stepAll 5 3 (stepAll 5 4 (wordItems 4 CoveringCerts.Data.K5_10_4))))) = true := by decide +kernel

end CoveringKernel
